### ISSUE TITLE
numpy.pad cannot take negative pad_width

### ISSUE THREAD

**Issue by mitmul** [chainer/chainer#138]
I'm trying to implement Spatial Pyramid Pooling function for Chainer by reference to the implementation in Caffe, then I run into a problem. On GPU both with cudnn and without cudnn, negative padding size is allowed to perform im2col. However, on CPU, because numpy.pad cannot take negative pad_width, im2col_cpu cannot be performed with negative padding size.

Test code:

```
import numpy
from chainer import Variable, cuda
import chainer.functions as F

cuda.init()

x = numpy.arange(2 * 3 * 4 * 3, dtype=numpy.float32).reshape(2, 3, 4, 3)
numpy.random.shuffle(x)
x = 2 * x / x.size - 1

pad = (-1, 0)  # has negative value

xv = Variable(cuda.to_gpu(x.astype(numpy.float32)))
y = F.max_pooling_2d(xv, 3, stride=2, pad=pad)
print('on gpu:', y.data.shape)

xv = Variable(x)
y = F.max_pooling_2d(xv, 3, stride=2, pad=pad)
print('on cpu:', y.data.shape)
```

Results:

```
on gpu: (2, 3, 1, 1)
Traceback (most recent call last):
  File "tests/test_negative_pad.py", line 18, in <module>
    y = F.max_pooling_2d(xv, 3, stride=2, pad=pad)
  File "build/bdist.linux-x86_64/egg/chainer/functions/pooling_2d.py", line 227, in max_pooling_2d
  File "build/bdist.linux-x86_64/egg/chainer/function.py", line 166, in __call__
  File "build/bdist.linux-x86_64/egg/chainer/function.py", line 254, in forward
  File "build/bdist.linux-x86_64/egg/chainer/functions/pooling_2d.py", line 84, in forward_cpu
  File "build/bdist.linux-x86_64/egg/chainer/utils/conv.py", line 21, in im2col_cpu
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/numpy/lib/arraypad.py", line 1292, in pad
    pad_width = _validate_lengths(narray, pad_width)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/numpy/lib/arraypad.py", line 1085, in _validate_lengths
    raise ValueError(fmt % (number_elements,))
ValueError: ((0, 0), (0, 0), (-1, 0), (0, 1)) cannot contain negative values.
```

Will this behaviour never be fixed? I think it's better that the difference between behaviours on GPU and on CPU is as small as possible.

**Comment by unnonouno** [comment]
Thank you for reporting a problem!
Of course, the same behaviors are better between CPU and GPU. Which one is better?
I think your suggestion is that the behavior of pycuda is useful.

**Comment by mitmul** [comment]
Yes, I think the negative pad width should be able to be accepted by any pooling functions.
