### ISSUE TITLE
use gpu save image error-when run  https://github.com/zdx3578/chainer-VAE

### ISSUE THREAD

**Issue by zdx3578** [chainer/chainer#1964]
(tensorflow)ubuntu@ip-172-30-2-186:~/work/chainer-VAE$ python train_vae.py --gpu 0 --epoch 2000   --dimz 80  --betac 5
GPU: 0
# dim z: 80
# Minibatch-size: 100
# epoch: 2000

load MNIST dataset
dump computational graph of `main/loss`
epoch       main/loss   validation/main/loss
1           221.22      190.744               
2           182.039     177.44                
3           177.022     174.298               
4           173.123     170.153               
5           169.541     167.768               
Traceback (most recent call last):
  File "train_vae.py", line 161, in <module>
    main()
  File "train_vae.py", line 158, in main
    trainer.run()
  File "/home/ubuntu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/chainer/training/trainer.py", line 292, in run
    entry.extension(self)
  File "train_vae.py", line 124, in save_images
    x1 = model.decode(model.encode(x)[0])
  File "/home/ubuntu/work/chainer-VAE/net.py", line 56, in encode
    h1 = F.tanh(self.le1(x))
  File "/home/ubuntu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/chainer/links/connection/linear.py", line 92, in __call__
    return linear.linear(x, self.W, self.b)
  File "/home/ubuntu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/chainer/functions/connection/linear.py", line 79, in linear
    return LinearFunction()(x, W, b)
  File "/home/ubuntu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/chainer/function.py", line 199, in __call__
    outputs = self.forward(in_data)
  File "/home/ubuntu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/chainer/functions/connection/linear.py", line 36, in forward
    y = x.dot(W.T).astype(x.dtype, copy=False)
  File "cupy/core/core.pyx", line 1003, in cupy.core.core.ndarray.__array__ (cupy/core/core.cpp:20702)
  File "cupy/core/core.pyx", line 284, in cupy.core.core.ndarray.astype (cupy/core/core.cpp:7053)
  File "cupy/core/core.pyx", line 1336, in cupy.core.core.elementwise_copy (cupy/core/core.cpp:49642)
  File "cupy/core/elementwise.pxi", line 771, in cupy.core.core.ufunc.__call__ (cupy/core/core.cpp:40576)
  File "cupy/util.pyx", line 35, in cupy.util.memoize.decorator.ret (cupy/util.cpp:1261)
  File "cupy/core/elementwise.pxi", line 558, in cupy.core.core._get_ufunc_kernel (cupy/core/core.cpp:36778)
  File "cupy/core/elementwise.pxi", line 134, in cupy.core.core._get_kernel_params (cupy/core/core.cpp:29061)
  File "cupy/core/elementwise.pxi", line 84, in cupy.core.core._get_typename (cupy/core/core.cpp:28072)
KeyError: <type 'numpy.object_'>
(tensorflow)ubuntu@ip-172-30-2-186:~/work/chainer-VAE$

**Comment by zdx3578** [comment]
use cpu is ok.
