### ISSUE TITLE
test_reciprocal fails on powerpc

### ISSUE THREAD

**Issue by deepali-c** [chainer/chainer#2086]
`test_reciprocal `fails on `powerpc `with the following error:

```
==================================================================
FAIL: test_reciprocal (test_arithmetic.TestArithmetic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<path>/test_arithmetic.py", line 42, in test_reciprocal
    self.check_unary('reciprocal')
  File "<path>/helper.py", line 404, in test_func
    impl(self, *args, **kw)
  File "<path>/helper.py", line 115, in test_func
    check_func(cupy_result, numpy_result)
  File "<path>/helper.py", line 165, in check_func
    rtol, atol, err_msg, verbose)
  File "<path>/array.py", line 26, in assert_allclose
    rtol=rtol, atol=atol, err_msg=err_msg, verbose=verbose)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1391, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 733, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-07, atol=1e-05

(mismatch 50.0%)
 x: array([[0, 1, 0],
       [1, 0, 1]], dtype=int8)
 y: array([[-1,  1, -1],
       [ 1, -1,  1]], dtype=int8)
----------------------------------------------------------------------
```

**Comment by unnonouno** [comment]
Thank you for reporting the problem. ARM architecture (such as TX1) has the same issue.
This problem happens when it casts special values of floating numbers such as NaN and infinity to integer. Its behavior depends on CPU architecture, and we need to skip comparison.
