### ISSUE TITLE
RuntimeError: CUDA environment is not correctly set up (Windows 10)

### ISSUE THREAD

**Issue by newikov** [chainer/chainer#2096]
Hi guys, 

I can't get Chainer running with Cuda on Windows 10. With cpu it works. 

I have python 3.5, cuda 8, visual studio 2015. 

Getting the following error when trying to run train_mnist.py

Traceback (most recent call last):
  File "C:/Projects/repos/chainer/examples/mnist/train_mnist.py", line 115, in <module>
    main()
  File "C:/Projects/repos/chainer/examples/mnist/train_mnist.py", line 56, in main
    chainer.cuda.get_device(args.gpu).use()  # Make a specified GPU current
  File "C:\Anaconda3\lib\site-packages\chainer\cuda.py", line 178, in get_device
    check_cuda_available()
  File "C:\Anaconda3\lib\site-packages\chainer\cuda.py", line 83, in check_cuda_available
    raise RuntimeError(msg)
RuntimeError: CUDA environment is not correctly set up
(see https://github.com/pfnet/chainer#installation).CuPy is not correctly installed. Please check your environment, uninstall Chainer and reinstall it with `pip install chainer --no-cache-dir -vvvv`.

Any advice maybe what could be wrong?

**Comment by alexberd** [comment]
Got the same issue and fixed it by uninstalling and installing Chainer!
