### ISSUE TITLE
test_where fails with AssertionError

### ISSUE THREAD

**Issue by deepali-c** [chainer/chainer#2117]
test_where fails with the Assertion Error:

`nosetests test_search.py`

```
==================================================================
FAIL: test_where (test_search.TestWhere_param_0)  parameter: {'cond_shape': (2, 3, 4), 'y_shape': (2, 3, 4), 'x_shape': (2, 3, 4)}
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<path>/cupy/testing/helper.py", line 627, in test_func
    impl(self, *args, **kw_copy)
  File "<path>/cupy/testing/helper.py", line 115, in test_func
    check_func(cupy_result, numpy_result)
  File "<path>/cupy/testing/helper.py", line 165, in check_func
    rtol, atol, err_msg, verbose)
  File "<path>/cupy/testing/array.py", line 26, in assert_allclose
    rtol=rtol, atol=atol, err_msg=err_msg, verbose=verbose)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1391, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 733, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 100.0%)
 x: array([[[ 5.488135,  0.      ,  0.      ,  5.448832],
        [ 0.      ,  0.      ,  0.      ,  0.      ],
        [ 0.      ,  0.      ,  0.      ,  5.288949]],...
 y: array([[[ 5.      ,  7.151894,  6.027634,  5.      ],
        [ 4.236548,  6.458941,  4.375872,  8.91773 ],
        [ 9.636628,  3.834415,  7.91725 ,  5.      ]],...
-------------------- >> begin captured stdout << ---------------------
{'x_type': <type 'numpy.float64'>, 'y_type': <type 'numpy.uint16'>, 'cond_type': <type 'numpy.bool_'>}
```
Similar error is seen for the other three parameters of the test case.

**Comment by gwtnb** [comment]
`TestWhere.test_where` was replaced with other test cases. https://github.com/pfnet/chainer/commit/8a31b1078192f41fe2ec472ba12b7be603eb0f16 Could you run test with the latest version?

**Comment by deepali-c** [comment]
I am currently using `v1.18.0 `of `chainer `and I think I will need to continue with it for some more time. Do you think that the test had any such issue before it was replaced with the newer test cases?

**Comment by unnonouno** [comment]
I executed this test with chainer v1.18.0, and it passed. And of course we always checks if all test cases are passed before releasing each version.
Can you tell me details of your environment?
