### ISSUE TITLE
[Solved] RuntimeError: CUDA environment is not correctly set up)

### ISSUE THREAD

**Issue by John1231983** [chainer/chainer#2259]
Hello all, I was installed CUDA 8.0 in Ubuntu 14.04. Then I install chainer 
```
export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
python setup.py install
```
It was successful to install as
```
Installing collected packages: chainer

Successfully installed chainer-1.20.0.1
Cleaning up...
```

However, when I run mnist example with GPU, I got the error. How can I fix it?

```
File "/usr/local/lib/python2.7/dist-packages/chainer-1.20.0-py2.7-linux-x86_64.egg/chainer/cuda.py", line 179, in get_device
    check_cuda_available()
  File "/usr/local/lib/python2.7/dist-packages/chainer-1.20.0-py2.7-linux-x86_64.egg/chainer/cuda.py", line 84, in check_cuda_available
    raise RuntimeError(msg)
RuntimeError: CUDA environment is not correctly set up
(see https://github.com/pfnet/chainer#installation).CuPy is not correctly installed. Please check your environment, uninstall Chainer and reinstall it with `pip install chainer --no-cache-dir -vvvv`.

original error: cannot import name core
```
**Update**: I also tried `sudo CUDA_PATH=/usr/local/cuda pip install chainer` but it cannot solve my issue. In my folder /usr/local/lib64 does not have libcuda.so. It only has

```
$ls -l /usr/local/cuda/lib64/libcud*
libcudadevrt.a       libcudart_static.a   libcudnn.so.5
libcudart.so         libcudnn.so          libcudnn.so.5.0.5
libcudart.so.8.0     libcudnn.so.4        libcudnn.so.5.1.10
libcudart.so.8.0.44  libcudnn.so.4.0.7    libcudnn_static.a

```
I installed cuda from .run in Ubuntu 14.04. Hence, the libcuda.so is in /usr/local/cuda/lib64/stubs
```
libcublas.so  libcusolver.so  libnppicom.so  libnppi.so    libnvgraph.so
libcuda.so    libcusparse.so  libnppidei.so  libnppist.so  libnvidia-ml.so
libcufft.so   libnppc.so      libnppif.so    libnppisu.so  libnvrtc.so
libcufftw.so  libnppial.so    libnppig.so    libnppitc.so
libcurand.so  libnppicc.so    libnppim.so    libnpps.so
```

What should I change the environment?
This is what I found in  [my log file](https://gist.github.com/John1231983/ed031ed2e72e8cf3366665e08a567e5a)
```
**************************************************
    *** WARNING: Cannot link libraries: ['cublas', 'cuda', 'cudart', 'curand', 'nvToolsExt']
    *** WARNING: Skip installing cuda support
    *** WARNING: Check your LDFLAGS environment variable
    **************************************************
    Include directories: ['/usr/local/cuda/include']
Library directories: ['/usr/local/cuda/lib64']
```
**Solved:**  I solved by copy the files in /usr/local/cuda/lib64/stubs to /usr/local/cuda/lib64/ by command
`sudo cp /usr/local/cuda/lib64/stubs/* /usr/local/cuda/lib64/`
Rebuild and it worked well. The reason is that I installed cuda 8.0 from .run file, so the .so files located in /stubs/ also/
**UPDATE Although I can build it successfully, but I cannot run Lenet example in GPU

```
GPU: 0
# unit: 1000
# Minibatch-size: 100
# epoch: 20


You are running using the stub version of curand
Traceback (most recent call last):
  File "/home/toanhoi/PycharmProjects/brain_segmentation/mnist_gpu.py", line 115, in <module>
    main()
  File "/home/toanhoi/PycharmProjects/brain_segmentation/mnist_gpu.py", line 112, in main
.    trainer.run()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/trainer.py", line 289, in run
    update()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/updater.py", line 174, in update
    self.update_core()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/updater.py", line 186, in update_core
    optimizer.update(loss_func, *in_vars)
  File "/usr/local/lib/python2.7/dist-packages/chainer/optimizer.py", line 390, in update
    loss = lossfun(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/chainer/links/model/classifier.py", line 67, in __call__
    self.y = self.predictor(*x)
  File "/home/toanhoi/PycharmProjects/brain_segmentation/mnist_gpu.py", line 24, in __call__
    h1 = F.relu(self.l1(x))
  File "/usr/local/lib/python2.7/dist-packages/chainer/links/connection/linear.py", line 91, in __call__
    self._initialize_params(x.size // x.shape[0])
  File "/usr/local/lib/python2.7/dist-packages/chainer/links/connection/linear.py", line 77, in _initialize_params
    initializer=self._W_initializer)
  File "/usr/local/lib/python2.7/dist-packages/chainer/link.py", line 180, in add_param
    data = initializers.generate_array(initializer, shape, self.xp)
  File "/usr/local/lib/python2.7/dist-packages/chainer/initializers/__init__.py", line 46, in generate_array
    initializer(array)
  File "/usr/local/lib/python2.7/dist-packages/chainer/initializers/normal.py", line 94, in __call__
    Normal(s)(array)
  File "/usr/local/lib/python2.7/dist-packages/chainer/initializers/normal.py", line 31, in __call__
    loc=0.0, scale=self.scale, size=array.shape)
  File "/usr/local/lib/python2.7/dist-packages/cupy/random/distributions.py", line 88, in normal
    rs = generator.get_random_state()
  File "/usr/local/lib/python2.7/dist-packages/cupy/random/generator.py", line 283, in get_random_state
    rs = RandomState(os.getenv('CHAINER_SEED'))
  File "/usr/local/lib/python2.7/dist-packages/cupy/random/generator.py", line 45, in __init__
    self._generator = curand.createGenerator(method)
  File "cupy/cuda/curand.pyx", line 92, in cupy.cuda.curand.createGenerator (cupy/cuda/curand.cpp:1434)
  File "cupy/cuda/curand.pyx", line 96, in cupy.cuda.curand.createGenerator (cupy/cuda/curand.cpp:1372)
  File "cupy/cuda/curand.pyx", line 85, in cupy.cuda.curand.check_status (cupy/cuda/curand.cpp:1207)
  File "cupy/cuda/curand.pyx", line 79, in cupy.cuda.curand.CURANDError.__init__ (cupy/cuda/curand.cpp:1099)
KeyError: 51
```

**Comment by unnonouno** [comment]
Sorry for late reply. I misunderstood that you already solved this problem. 
This error message is curious. I checked the source. At line 79, it convert an error code number to an error message. `51` may be the error code, but it is not defined.

I have a question about your installation. How did you install CUDA on your environment? I recommend to use deb package if you use Ubuntu. Usually it makes `/usr/local/cuda/lib64` directory. In my environment, it is a symbolic link to `/usr/local/cuda/targets/x86_64-linux/lib`.
