### ISSUE TITLE
problem of CUBLAS_STATUS_NOT_INITIALIZED on Mac OSX 10.11.6

### ISSUE THREAD

**Issue by panakino** [chainer/chainer#2286]
Hello, I have troubles with GPU learning on chainer. During installation, there were no errors. I passed MNIST test on GPU.

When I tested code with convolution_nd.py, it gave errors like:

$ python train_test.py -g 0 -i ~/data/

/usr/local/lib/python2.7/site-packages/chainer/cuda.py:89: UserWarning: cuDNN is not enabled.
Please reinstall chainer after you install cudnn
(see https://github.com/pfnet/chainer#installation).
  'cuDNN is not enabled.\n'
Traceback (most recent call last):
...
    e0 = F.relu((self.c0(x)), use_cudnn)
  File "/usr/local/lib/python2.7/site-packages/chainer/links/connection/convolution_nd.py", line 83, in __call__
    use_cudnn=self.use_cudnn, cover_all=self.cover_all)
  File "/usr/local/lib/python2.7/site-packages/chainer/functions/connection/convolution_nd.py", line 350, in convolution_nd
    return func(x, W)
  File "/usr/local/lib/python2.7/site-packages/chainer/function.py", line 199, in __call__
    outputs = self.forward(in_data)
  File "/usr/local/lib/python2.7/site-packages/chainer/functions/connection/convolution_nd.py", line 168, in forward
    return self._forward_xp(x, W, b, cuda.cupy)
  File "/usr/local/lib/python2.7/site-packages/chainer/functions/connection/convolution_nd.py", line 82, in _forward_xp
    y = xp.tensordot(self.col, W, (axes, axes)).astype(x.dtype, copy=False)
  File "/usr/local/lib/python2.7/site-packages/cupy/linalg/product.py", line 193, in tensordot
    return core.tensordot_core(a, b, None, n, m, k, ret_shape)
  File "cupy/core/core.pyx", line 3115, in cupy.core.core.tensordot_core (cupy/core/core.cpp:78291)
  File "cupy/core/core.pyx", line 3178, in cupy.core.core.tensordot_core (cupy/core/core.cpp:77841)
  File "cupy/cuda/device.pyx", line 22, in cupy.cuda.device.get_cublas_handle (cupy/cuda/device.cpp:1444)
  File "cupy/cuda/device.pyx", line 111, in cupy.cuda.device.Device.cublas_handle.__get__ (cupy/cuda/device.cpp:2663)
  File "cupy/cuda/device.pyx", line 112, in cupy.cuda.device.Device.cublas_handle.__get__ (cupy/cuda/device.cpp:2591)
  File "cupy/cuda/cublas.pyx", line 145, in cupy.cuda.cublas.create (cupy/cuda/cublas.cpp:1742)
  File "cupy/cuda/cublas.pyx", line 134, in cupy.cuda.cublas.check_status (cupy/cuda/cublas.cpp:1594)
cupy.cuda.cublas.CUBLASError: CUBLAS_STATUS_NOT_INITIALIZED

I couldn't catch anything from this because main difference with MNIST test was convolution_nd.py/deconvolution_nd.py. Do you have any idea?

**Comment by soramichi** [comment]
Hi,

The first thing is the waning that says cuDNN is not installed and the exception you got are irrelevant.
(They appear independently but due to the sequential printing they look relevant by mistake.)

The exception means that the BLAS (Basic Linear Algebra Subprograms) included in CUDA cannot be initialized from chainer, which means either of the two: (1) Your CUDA installation is somehow broken (2) It's a chainer bug.

To see if (1) is true or not, can you try executing a CUDA example that uses BLAS, such as `NVIDIA_CUDA-8.0_Samples/7_CUDALibraries/batchCUBLAS`? It is included in your cuda directory, or you can re-install it from the cuda installer (https://developer.nvidia.com/cuda-downloads). Go to the directory and do `make` then `./batchCUBLAS`.

**Comment by panakino** [comment]
Thanks for prompt reply.

I tested along with your comment (1), and I got this :

batchCUBLAS Starting...

GPU Device 0: "GeForce GTX TITAN X" with compute capability 5.2


 ==== Running single kernels ==== 

Testing sgemm
#### args: ta=0 tb=0 m=128 n=128 k=128  alpha = (0xbf800000, -1) beta= (0x40000000, 2)
#### args: lda=128 ldb=128 ldc=128
^^^^ elapsed = 0.00010610 sec  GFLOPS=39.533
@@@@ sgemm test OK
Testing dgemm
#### args: ta=0 tb=0 m=128 n=128 k=128  alpha = (0x0000000000000000, 0) beta= (0x0000000000000000, 0)
#### args: lda=128 ldb=128 ldc=128
^^^^ elapsed = 0.00019002 sec  GFLOPS=22.073
@@@@ dgemm test OK

 ==== Running N=10 without streams ==== 

Testing sgemm
#### args: ta=0 tb=0 m=128 n=128 k=128  alpha = (0xbf800000, -1) beta= (0x00000000, 0)
#### args: lda=128 ldb=128 ldc=128
^^^^ elapsed = 0.00038195 sec  GFLOPS=109.814
@@@@ sgemm test OK
Testing dgemm
#### args: ta=0 tb=0 m=128 n=128 k=128  alpha = (0xbff0000000000000, -1) beta= (0x0000000000000000, 0)
#### args: lda=128 ldb=128 ldc=128
^^^^ elapsed = 0.00068879 sec  GFLOPS=60.8937
@@@@ dgemm test OK

 ==== Running N=10 with streams ==== 

Testing sgemm
#### args: ta=0 tb=0 m=128 n=128 k=128  alpha = (0x40000000, 2) beta= (0x40000000, 2)
#### args: lda=128 ldb=128 ldc=128
^^^^ elapsed = 0.00019979 sec  GFLOPS=209.931
@@@@ sgemm test OK
Testing dgemm
#### args: ta=0 tb=0 m=128 n=128 k=128  alpha = (0xbff0000000000000, -1) beta= (0x0000000000000000, 0)
#### args: lda=128 ldb=128 ldc=128
^^^^ elapsed = 0.00043511 sec  GFLOPS=96.3955
@@@@ dgemm test OK

 ==== Running N=10 batched ==== 

Testing sgemm
#### args: ta=0 tb=0 m=128 n=128 k=128  alpha = (0x3f800000, 1) beta= (0xbf800000, -1)
#### args: lda=128 ldb=128 ldc=128
^^^^ elapsed = 0.00237083 sec  GFLOPS=17.6913
@@@@ sgemm test OK
Testing dgemm
#### args: ta=0 tb=0 m=128 n=128 k=128  alpha = (0xbff0000000000000, -1) beta= (0x4000000000000000, 2)
#### args: lda=128 ldb=128 ldc=128
^^^^ elapsed = 0.00044703 sec  GFLOPS=93.825
@@@@ dgemm test OK

Test Summary
0 error(s)



It seems there is no error.

**Comment by soramichi** [comment]
Well, I actually expected batchCUBLAS would fail because it creates a cublas context which chainer fails to initialize in your trace log. Now the situations are bit weird:
(i) Chainer properly finds the cublas library (that's why it can at least try to create a cublas context and then finds the return value is an error)
(ii) The cublas library can be properly used by a sample provided by NVIDIA
(iii) However chainer fails to initialize the cublas library

@panakino 
A workaround might be installing cudnn, because then convolution_nd/deconvolution_nd will use cudnn  instead of cublas and it may work if your're lucky

@maintainers
I suspect this might be suspicious:
https://github.com/pfnet/chainer/blob/master/cupy/cuda/device.pyx#L22
Shouldn't it be `return Device(dev_id).cublas_handle`? I tried to read the cpp code generated by cython but it was not intended to be human-readable, so I couldn't see what happens if the `Device()` constructor is called with no argument.

**Comment by panakino** [comment]
@soramichi 

(1) I already checked feasibility of cudnn (v5.1), and got this errors :

GPU: 0
# Minibatch-size: 1
# epoch: 50

Traceback (most recent call last):
  File "train_unet.py", line 174, in <module>
    main()
  File "train_unet.py", line 103, in main
    trainer.run()
  File "/usr/local/lib/python2.7/site-packages/chainer/training/trainer.py", line 295, in run
    update()
  File "/usr/local/lib/python2.7/site-packages/chainer/training/updater.py", line 174, in update
    self.update_core()
  File "/usr/local/lib/python2.7/site-packages/chainer/training/updater.py", line 186, in update_core
    optimizer.update(loss_func, *in_vars)
  File "/usr/local/lib/python2.7/site-packages/chainer/optimizer.py", line 395, in update
    loss.backward()
  File "/usr/local/lib/python2.7/site-packages/chainer/variable.py", line 399, in backward
    gxs = func.backward(in_data, out_grad)
  File "/usr/local/lib/python2.7/site-packages/chainer/functions/connection/convolution_nd.py", line 289, in backward
    return self._backward_cudnn(x, W, b, gy)
  File "/usr/local/lib/python2.7/site-packages/chainer/functions/connection/convolution_nd.py", line 248, in _backward_cudnn
    zero.data, x_desc.value, gx.data.ptr)
  File "cupy/cuda/cudnn.pyx", line 784, in cupy.cuda.cudnn.convolutionBackwardData_v3 (cupy/cuda/cudnn.cpp:9504)
  File "cupy/cuda/cudnn.pyx", line 797, in cupy.cuda.cudnn.convolutionBackwardData_v3 (cupy/cuda/cudnn.cpp:9316)
  File "cupy/cuda/cudnn.pyx", line 356, in cupy.cuda.cudnn.check_status (cupy/cuda/cudnn.cpp:1987)
cupy.cuda.cudnn.CuDNNError: CUDNN_STATUS_NOT_SUPPORTED: CUDNN_STATUS_NOT_SUPPORTED


(2) Already installed recent version (1.21.0).

Thanks.

**Comment by soramichi** [comment]
That's really strange. How come the exception does not occur in `forward`, which must have been executed at least once before any `backward` is executed.

Just in case, which cuda version do you use? Chainer supports 6.5 and newer, and cudnn 5.1 supports 7.5 and newer.

**Comment by panakino** [comment]
I'm  using CUDA 8.0 with cud v5.1.

**Comment by chenzhekl** [comment]
The same happened on Ubuntu 16.04.1 when transferring the pre-trained VGG to the second GPU. If it is transferred to the first GPU, everything works fine.
