### ISSUE TITLE
CUDNN_STATUS_NOT_SUPPORTED on BatchNormalization layers

### ISSUE THREAD

**Issue by sergsb** [chainer/chainer#2414]
Hi,
I use chainer v. 1.21.0, CUDA 7.5 CUDNN 5105, on Ubuntu 16.04.1 LTS  
I have an error during batch normalization. This problem has been discussed yet [here](https://github.com/pfnet/chainer/issues/1762), but no causes under witch this bug have been reproducible were found. 
I found that this code leads to the error:
```
import chainer
from chainer import links as L
import cupy
print(chainer.cuda.cudnn.cudnn.getVersion()) # =>5103
x = cupy.random.uniform(size=(1025, 5)).astype(cupy.float32)
x = chainer.Variable(x)
l = L.BatchNormalization(5)
l.to_gpu()
l(x, test=True)


5105
Traceback (most recent call last):
  File "cudnn_test.py", line 9, in <module>
    l(x, test=True)
  File "/home/pirotex/.virtualenvs/chainer/local/lib/python2.7/site-packages/chainer/links/normalization/batch_normalization.py", line 139, in __call__
    x, gamma, beta, mean, var, self.eps, self.use_cudnn)
  File "/home/pirotex/.virtualenvs/chainer/local/lib/python2.7/site-packages/chainer/functions/normalization/batch_normalization.py", line 347, in fixed_batch_normalization
    use_cudnn)(x, gamma, beta, mean, var)
  File "/home/pirotex/.virtualenvs/chainer/local/lib/python2.7/site-packages/chainer/function.py", line 199, in __call__
    outputs = self.forward(in_data)
  File "/home/pirotex/.virtualenvs/chainer/local/lib/python2.7/site-packages/chainer/functions/normalization/batch_normalization.py", line 157, in forward
    self.eps)
  File "cupy/cuda/cudnn.pyx", line 890, in cupy.cuda.cudnn.batchNormalizationForwardInference (cupy/cuda/cudnn.cpp:11294)
  File "cupy/cuda/cudnn.pyx", line 905, in cupy.cuda.cudnn.batchNormalizationForwardInference (cupy/cuda/cudnn.cpp:11097)
  File "cupy/cuda/cudnn.pyx", line 356, in cupy.cuda.cudnn.check_status (cupy/cuda/cudnn.cpp:1987)
cupy.cuda.cudnn.CuDNNError: CUDNN_STATUS_NOT_SUPPORTED: CUDNN_STATUS_NOT_SUPPORTED

```

But if we reduce `size` to (1024,5) all works fine. 

It looks like there is a `magic` constant in chainer core or in CuDNN equal to `1024`, and if we use samples size more than `1024` it falls. 

Also this error occurs only if we use `test=False` if we set `test=True` it always works.

**Comment by jekbradbury** [comment]
I believe this is a bug in CUDNN core (batchnorm forward inference fails in training mode with batch size greater than 1024) that was fixed in v5.1.10, although I can't find the comment where an NVIDIA engineer mentioned this..

**Comment by unnonouno** [comment]
Wow really? I'll ask NVIDIA engineer.

**Comment by jekbradbury** [comment]
Looks like I'm not completely correct: it was undocumented but not unintended behavior, and is definitely fixed in CUDNN v6.0rc (but looks like it might not be fixed in 5.1.10). The recommended workaround is to split the batch in half...
See https://github.com/soumith/cudnn.torch/issues/318#issuecomment-275164615, https://github.com/soumith/cudnn.torch/issues/185#issuecomment-220071077

**Comment by unnonouno** [comment]
In my environment cuDNN v5.1.5 causes this error, but v5.1.10 is fixed.

**Comment by cmpute** [comment]
Maximum batch size is 131070 as I tested for cuDNN 7.1.2
