### ISSUE TITLE
BLAS error at backward of F.sum of L.Convolution2d

### ISSUE THREAD

**Issue by toslunar** [chainer/chainer#2744]
The code below terminates unsuccessfully with the message:
> BLAS error: Parameter incX passed to cblas_sgemv was 0, which is invalid.

With `h = h[:,:,:,:]`, it causes no errors.  This behavior seems to be a bug.
```python
import chainer
import chainer.functions as F
import chainer.links as L
import numpy as np

conv = L.Convolution2D(3, 1, 3)

conv.cleargrads()

x = np.random.rand(300).astype(np.float32).reshape(1,3,10,10)
h = conv(x)
print(h.data)
# h = h[:,:,:,:]
y = F.sum(h, axis=(2,3))
print(y.data)
y.backward()
```
[log.txt](https://github.com/pfnet/chainer/files/1007274/log.txt)

**Comment by ISP-Tetsuro-Kitajima** [comment]
in my anaconda(Ubuntu) environment: 

    openssl:    1.0.2k-2
    pip:        9.0.1-py27_1
    python:     2.7.13-0
    readline:   6.2-2
    setuptools: 27.2.0-py27_0
    sqlite:     3.13.0-0
    tk:         8.5.18-0
    wheel:      0.29.0-py27_0
    zlib:       1.2.8-3

```
Collecting chainer
  Downloading chainer-1.24.0.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 737kB/s
Collecting filelock (from chainer)
Collecting nose (from chainer)
  Using cached nose-1.3.7-py2-none-any.whl
Collecting numpy>=1.9.0 (from chainer)
  Using cached numpy-1.12.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting protobuf>=2.6.0 (from chainer)
  Using cached protobuf-3.3.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting six>=1.9.0 (from chainer)
  Using cached six-1.10.0-py2.py3-none-any.whl
```

```
>>> y.backward()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hogehoge/anaconda2/envs/chainer/lib/python2.7/site-packages/chainer/variable.py", line 398, in backward
    gxs = func.backward(in_data, out_grad)
  File "/home/hogehoge/anaconda2/envs/chainer/lib/python2.7/site-packages/chainer/function.py", line 375, in backward
    return self.backward_cpu(inputs, grad_outputs)
  File "/home/hogehoge/anaconda2/envs/chainer/lib/python2.7/site-packages/chainer/functions/connection/convolution_2d.py", line 184, in backward_cpu
    gy, self.col, ((0, 2, 3), (0, 4, 5))).astype(W.dtype, copy=False)
  File "/home/hogehoge/anaconda2/envs/chainer/lib/python2.7/site-packages/numpy/core/numeric.py", line 1395, in tensordot
    res = dot(at, bt)
ValueError: On entry to SGEMV parameter number 8 had an illegal value

>>> np.show_config()
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
blis_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
lapack_mkl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE

```
numpy bug?

**Comment by toslunar** [comment]
In my environment, the above code causes no error in chainer==1.23, (but it does in chainer==1.24).
```
chainer==1.23.0
filelock==2.0.8
nose==1.3.7
numpy==1.12.1
protobuf==3.3.0
six==1.10.0
```

**Comment by unnonouno** [comment]
I could reproduce the error in my environment. I'll fix it.

**Comment by unnonouno** [comment]
I finally found that this is NumPy's bug:
```
x = numpy.zeros(1, 'f')
x = numpy.broadcast_to(x, (1, 2))
y = numpy.zeros((2, 2), 'f')
x.dot(y)
```

It causes this error:
```
ValueError: On entry to SGEMV parameter number 8 had an illegal value
```

Maybe it causes when `strides` is zero.

**Comment by muupan** [comment]
FYI:
- `F.mean` is also affected by this issue.
- You can void this issue by adding `h = h[:]` before `F.sum(h)` or `F.mean(h)`.
- We might need to wait for https://github.com/numpy/numpy/issues/9165 to be solved.

**Comment by kmaehashi** [comment]
Has anyone reported this issue to NumPy team? (it's not yet fixed in NumPy 1.14)

**Comment by niboshi** [comment]
https://github.com/numpy/numpy/issues/9165?

**Comment by kmaehashi** [comment]
Ah, thanks, I overlooked the link. The corresponding PR is #9177.
