### ISSUE TITLE
basic_math's operand cannot be of newint type of Python 2

### ISSUE THREAD

**Issue by toslunar** [chainer/chainer#2807]
```python
>>> from future.builtins import int
>>> import chainer
>>> import numpy as np
>>>
>>> i = int(3)
>>> print(type(i))
<class 'future.types.newint.newint'>
>>> xd = np.array(np.arange(i), dtype=np.float32)
>>> x = chainer.Variable(xd)
>>> print(xd / i)
[ 0.          0.33333334  0.66666669]
>>> print(x / i)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tos/py2/lib/python2.7/site-packages/chainer/functions/math/basic_math.py", line 326, in div
    _check_constant_type(rhs)
  File "/Users/tos/py2/lib/python2.7/site-packages/chainer/functions/math/basic_math.py", line 34, in _check_constant_type
    'value must be scalar, ndarray, or Variable')
ValueError: value must be scalar, ndarray, or Variable
```

possibly related to #1629

**Comment by muupan** [comment]
This problem is due to `numpy.isscalar`: https://github.com/numpy/numpy/issues/8787.

Since `numpy.isscalar` is used many places in Chainer, consistently supporting `future.types.newint.newint` might not be simple: https://github.com/chainer/chainer/search?utf8=%E2%9C%93&q=isscalar&type=
