### ISSUE TITLE
example/mnist/train_mnist.py fails when using GPU

### ISSUE THREAD

**Issue by DenDen047** [chainer/chainer#2809]
When I executed `chainer/chainer/example/mnist/train_mnist.py` with GPU, the following error occurred.
It seems that it uses both of numpy.ndarray and cupy.ndarray.

I used [the latest official docker container](https://hub.docker.com/r/chainer/chainer/)
GPU : TITAN-X

```sh
root@ce05d3cc6624:~/work/chainer/examples/mnist# ./train_mnist.py --gpu=0
GPU: 0
# unit: 1000
# Minibatch-size: 100
# epoch: 20

/usr/local/lib/python2.7/dist-packages/chainer/training/extensions/plot_report.py:24: UserWarning: matplotlib is not installed on your environment, so nothing will be plotted at this time. Please install matplotlib to plot figures.

  $ pip install matplotlib

  warnings.warn('matplotlib is not installed on your environment, '
Traceback (most recent call last):
  File "./train_mnist.py", line 137, in <module>
    main()
  File "./train_mnist.py", line 133, in main
    trainer.run()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/trainer.py", line 295, in run
    update()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/updater.py", line 177, in update
    self.update_core()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/updater.py", line 189, in update_core
    optimizer.update(loss_func, *in_vars)
  File "/usr/local/lib/python2.7/dist-packages/chainer/optimizer.py", line 411, in update
    loss = lossfun(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/chainer/links/model/classifier.py", line 67, in __call__
    self.y = self.predictor(*x)
  File "./train_mnist.py", line 39, in __call__
    h1 = F.relu(self.l1(x))
  File "/usr/local/lib/python2.7/dist-packages/chainer/links/connection/linear.py", line 93, in __call__
    return linear.linear(x, self.W, self.b)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/connection/linear.py", line 107, in linear
    return LinearFunction()(x, W, b)
  File "/usr/local/lib/python2.7/dist-packages/chainer/function.py", line 199, in __call__
    outputs = self.forward(in_data)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/connection/linear.py", line 40, in forward
    .format(type(W), type(x)))
ValueError: numpy and cupy must not be used together
type(W): <type 'numpy.ndarray'>, type(x): <type 'cupy.core.core.ndarray'>
root@ce05d3cc6624:~/work/chainer/examples/mnist#
```

Another error said that there is not `self.init_scope()`, so I modified the MLP class as following:
```python
# Network definition
class MLP(chainer.Chain):

    # def __init__(self, n_units, n_out):
    #     super(MLP, self).__init__()
    #     with self.init_scope():
    #         # the size of the inputs to each layer will be inferred
    #         self.l1 = L.Linear(None, n_units)  # n_in -> n_units
    #         self.l2 = L.Linear(None, n_units)  # n_units -> n_units
    #         self.l3 = L.Linear(None, n_out)  # n_units -> n_out

    def __init__(self, n_units, n_out):
        super(MLP, self).__init__()
        # the size of the inputs to each layer will be inferred
        self.l1 = L.Linear(None, n_units)  # n_in -> n_units
        self.l2 = L.Linear(None, n_units)  # n_units -> n_units
        self.l3 = L.Linear(None, n_out)  # n_units -> n_out

    def __call__(self, x):
        h1 = F.relu(self.l1(x))
        h2 = F.relu(self.l2(h1))
        return self.l3(h2)
```

**Comment by gwtnb** [comment]
Thank you for reporting. I translated your messages to English.

**Comment by gwtnb** [comment]
It seems that you used old Chainer. Could you use Chainer 2.0.0?

**Comment by DenDen047** [comment]
I used Chainer 1.24.

**Comment by gwtnb** [comment]
If you have to use Chainer 1.24, you can run the MNIST example as following:

```
git clone https://github.ocm/chainer/chainer.git
cd chainer
git checkout v1.24.0
cd examples/mnist
python train_mnist.py
```

**Comment by DenDen047** [comment]
I could run `python train_mnist.py`.
But I couldn't run `python train_mnist.py --gpu=0', and the following error occurred.

```sh
root@ce05d3cc6624:~/work/chainer/examples/mnist# ./train_mnist.py --gpu=0
GPU: 0
# unit: 1000
# Minibatch-size: 100
# epoch: 20

/usr/local/lib/python2.7/dist-packages/chainer/training/extensions/plot_report.py:24: UserWarning: matplotlib is not installed on your environment, so nothing will be plotted at this time. Please install matplotlib to plot figures.

  $ pip install matplotlib

  warnings.warn('matplotlib is not installed on your environment, '
Traceback (most recent call last):
  File "./train_mnist.py", line 130, in <module>
    main()
  File "./train_mnist.py", line 126, in main
    trainer.run()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/trainer.py", line 295, in run
    update()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/updater.py", line 177, in update
    self.update_core()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/updater.py", line 189, in update_core
    optimizer.update(loss_func, *in_vars)
  File "/usr/local/lib/python2.7/dist-packages/chainer/optimizer.py", line 411, in update
    loss = lossfun(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/chainer/links/model/classifier.py", line 67, in __call__
    self.y = self.predictor(*x)
  File "./train_mnist.py", line 32, in __call__
    h1 = F.relu(self.l1(x))
  File "/usr/local/lib/python2.7/dist-packages/chainer/links/connection/linear.py", line 92, in __call__
    self._initialize_params(x.size // x.shape[0])
  File "/usr/local/lib/python2.7/dist-packages/chainer/links/connection/linear.py", line 78, in _initialize_params
    initializer=self._W_initializer)
  File "/usr/local/lib/python2.7/dist-packages/chainer/link.py", line 179, in add_param
    data = initializers.generate_array(initializer, shape, self.xp)
  File "/usr/local/lib/python2.7/dist-packages/chainer/initializers/__init__.py", line 46, in generate_array
    initializer(array)
  File "/usr/local/lib/python2.7/dist-packages/chainer/initializers/normal.py", line 99, in __call__
    Normal(s)(array)
  File "/usr/local/lib/python2.7/dist-packages/chainer/initializers/normal.py", line 36, in __call__
    array[...] = xp.random.normal(**args)
  File "/usr/local/lib/python2.7/dist-packages/cupy/random/distributions.py", line 90, in normal
    return (rs.normal(0, 1, size, dtype) * scale + loc).astype(dtype)
  File "/usr/local/lib/python2.7/dist-packages/cupy/random/generator.py", line 105, in normal
    return self._generate_normal(func, size, dtype, loc, scale)
  File "/usr/local/lib/python2.7/dist-packages/cupy/random/generator.py", line 68, in _generate_normal
    func(self._generator, out.data.ptr, out.size, *args)
  File "cupy/cuda/curand.pyx", line 171, in cupy.cuda.curand.generateNormalDouble (cupy/cuda/curand.cpp:3431)
  File "cupy/cuda/curand.pyx", line 179, in cupy.cuda.curand.generateNormalDouble (cupy/cuda/curand.cpp:3313)
  File "cupy/cuda/curand.pyx", line 85, in cupy.cuda.curand.check_status (cupy/cuda/curand.cpp:1438)
cupy.cuda.curand.CURANDError: CURAND_STATUS_LAUNCH_FAILURE
```

**Comment by gwtnb** [comment]
Would you tell us the version of CUDA installed to the host (not in the container)?

**Comment by DenDen047** [comment]
Here.

```sh
$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
```

```sh
% dpkg -l | grep cuda
ii  cuda                                                  8.0.61-1                                            amd64        CUDA meta-package
ii  cuda-8-0                                              8.0.61-1                                            amd64        CUDA 8.0 meta-package
ii  cuda-command-line-tools-8-0                           8.0.61-1                                            amd64        CUDA command-line tools
ii  cuda-core-8-0                                         8.0.61-1                                            amd64        CUDA core tools
ii  cuda-cublas-8-0                                       8.0.61-1                                            amd64        CUBLAS native runtime libraries
ii  cuda-cublas-dev-8-0                                   8.0.61-1                                            amd64        CUBLAS native dev links, headers
ii  cuda-cudart-8-0                                       8.0.61-1                                            amd64        CUDA Runtime native Libraries
ii  cuda-cudart-dev-8-0                                   8.0.61-1                                            amd64        CUDA Runtime native dev links, headers
ii  cuda-cufft-8-0                                        8.0.61-1                                            amd64        CUFFT native runtime libraries
ii  cuda-cufft-dev-8-0                                    8.0.61-1                                            amd64        CUFFT native dev links, headers
ii  cuda-curand-8-0                                       8.0.61-1                                            amd64        CURAND native runtime libraries
ii  cuda-curand-dev-8-0                                   8.0.61-1                                            amd64        CURAND native dev links, headers
ii  cuda-cusolver-8-0                                     8.0.61-1                                            amd64        CUDA solver native runtime libraries
ii  cuda-cusolver-dev-8-0                                 8.0.61-1                                            amd64        CUDA solver native dev links, headers
ii  cuda-cusparse-8-0                                     8.0.61-1                                            amd64        CUSPARSE native runtime libraries
ii  cuda-cusparse-dev-8-0                                 8.0.61-1                                            amd64        CUSPARSE native dev links, headers
ii  cuda-demo-suite-8-0                                   8.0.61-1                                            amd64        Demo suite for CUDA
ii  cuda-documentation-8-0                                8.0.61-1                                            amd64        CUDA documentation
ii  cuda-driver-dev-8-0                                   8.0.61-1                                            amd64        CUDA Driver native dev stub library
ii  cuda-drivers                                          375.26-1                                            amd64        CUDA Driver meta-package
ii  cuda-license-8-0                                      8.0.61-1                                            amd64        CUDA licenses
ii  cuda-misc-headers-8-0                                 8.0.61-1                                            amd64        CUDA miscellaneous headers
ii  cuda-npp-8-0                                          8.0.61-1                                            amd64        NPP native runtime libraries
ii  cuda-npp-dev-8-0                                      8.0.61-1                                            amd64        NPP native dev links, headers
ii  cuda-nvgraph-8-0                                      8.0.61-1                                            amd64        NVGRAPH native runtime libraries
ii  cuda-nvgraph-dev-8-0                                  8.0.61-1                                            amd64        NVGRAPH native dev links, headers
ii  cuda-nvml-dev-8-0                                     8.0.61-1                                            amd64        NVML native dev links, headers
ii  cuda-nvrtc-8-0                                        8.0.61-1                                            amd64        NVRTC native runtime libraries
ii  cuda-nvrtc-dev-8-0                                    8.0.61-1                                            amd64        NVRTC native dev links, headers
ii  cuda-repo-ubuntu1404-8-0-local                        8.0.44-1                                            amd64        cuda repository configuration files
ii  cuda-repo-ubuntu1404-8-0-local-ga2                    8.0.61-1                                            amd64        cuda repository configuration files
ii  cuda-runtime-8-0                                      8.0.61-1                                            amd64        CUDA Runtime 8.0 meta-package
ii  cuda-samples-8-0                                      8.0.61-1                                            amd64        CUDA example applications
ii  cuda-toolkit-8-0                                      8.0.61-1                                            amd64        CUDA Toolkit 8.0 meta-package
ii  cuda-visual-tools-8-0                                 8.0.61-1                                            amd64        CUDA visual tools
rc  libcuda1-367                                          367.57-0ubuntu0.14.04.1                             amd64        NVIDIA CUDA runtime library
ii  libcuda1-375                                          375.26-0ubuntu1                                     amd64        NVIDIA CUDA runtime library
```

**Comment by mrteera** [comment]
I also have the same error as @DenDen047

**Comment by kmaehashi** [comment]
This issue will be solved in https://github.com/chainer/chainer/pull/3902
(see also: https://github.com/chainer/chainer/pull/3898#issuecomment-345194894)
