### ISSUE TITLE
Test failure on test_spatial_transformer_sampler.TestSpatialTransformerSampler

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#2854]
https://travis-ci.org/chainer/chainer/builds/241979452?utm_source=github_status&utm_medium=notification
(Occured in a PR based on `v2` branch. Also confirmed in `master` branch.)

~Looks like this is numeric unstability due to non-deterministic behavior of `cudnnSpatialTfSamplerBackward` function.~ This error has occurred in cpu mode.

```
FAIL: test_backward_cpu (test_spatial_transformer_sampler.TestSpatialTransformerSampler_param_1)  parameter: {'use_cudnn': False}
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/chainer/testing/condition.py", line 74, in wrapper
    fail()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/chainer/testing/condition.py", line 51, in fail
    instance.fail(msg)
AssertionError: 
Fail: 3, Success: 0
The first error message:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/chainer/testing/condition.py", line 60, in <lambda>
    lambda: f(ins, *args[1:], **kwargs),
  File "/home/travis/build/chainer/chainer/tests/chainer_tests/functions_tests/array_tests/test_spatial_transformer_sampler.py", line 81, in test_backward_cpu
    self.check_backward(self.x, self.grid, self.grads)
  File "/home/travis/build/chainer/chainer/tests/chainer_tests/functions_tests/array_tests/test_spatial_transformer_sampler.py", line 77, in check_backward
    (x, grid), (grads,), atol=1e-2, rtol=1e-2, eps=1e-5)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/chainer/gradient_check.py", line 261, in check_backward
    testing.assert_allclose(gx, x.grad, atol=atol, rtol=rtol)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/chainer/testing/array.py", line 24, in assert_allclose
    x, y, atol=atol, rtol=rtol, verbose=verbose)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.01, atol=0.01
(mismatch 100.0%)
 x: array([[[[ 0.      ,  1.745135,  0.018301],
         [ 0.      ,  0.059922,  0.      ],
         [ 0.675761,  0.      ,  0.011499]],...
 y: array([[[[ 0.      ,  1.74235 ,  0.018444],
         [ 0.      ,  0.059806,  0.      ],
         [ 0.674425, -0.      ,  0.01307 ]],...
-------------------- >> begin captured stdout << ---------------------
('error:', 0.030225635)
('error:', 0.02776432)
('error:', 0.025904417)
```

**Comment by yuyu2172** [comment]
From the log, it seems that the test failed during CPU mode. I think cuDNN is not related to this issue.
Due to the nature of the function, the backward pass has been unstable.
How should we improve the stability?

**Comment by niboshi** [comment]
Oh, you're right! Thank you for pointing out.
Can you locate the exact source of numeric unstability?

**Comment by niboshi** [comment]
Ah, I found it's due to random numbers in the test...
I think it can be easily fixed by using fixed random seed.
Actually I'm working on similar problem in cupy: https://github.com/cupy/cupy/pull/82
I will port it after it's fixed in cupy.

**Comment by yuyu2172** [comment]
>Can you locate the exact source of numeric unstability?

I can not really describe the instability mathematically, but it seems that the gradient for the grid is always failing the test.
FYI, I changed the setting of retry option to never retry, and I observed that the backward pass fails once in every ten trial.

**Comment by niboshi** [comment]
Thank you for checking.
We're discussing internally on how to deal with random tests.
But 1/10 failure rate is quite large...
Perhaps this test needs a fix after we decide random test policy.

**Comment by yuyu2172** [comment]
Yes. 1/10 fails so, even with retry(3) option, 1 / 1000 fail.

**Comment by niboshi** [comment]
It seems this has been fixed in the latest v3 branch.
I close this issue.
