### ISSUE TITLE
Copy to another GPU after swapaxes causes an error

### ISSUE THREAD

**Issue by MorinoseiMorizo** [chainer/chainer#2911]
I got the following error when I try to copy a Variable to another GPU after swapaxes.
`ValueError: Array device must be same as the current device: array device = 1 while current = 0`

It looks like a bug on copy or swapaxes functions on Chainer.

* Conditions
  - Chainer version: 2.0.0
  - CuPy version: 1.0.0.1
  - OS/Platform: CentOS 7
  - CUDA/cuDNN version: CUDA 8.0.44, cuDNN 5.1.5

* Code to reproduce
```
import cupy as xp
import chainer
import chainer.functions as F
from chainer import cuda

gpu_a = 0
gpu_b = 1

cuda.check_cuda_available()
cuda.get_device(gpu_a).use()

x = xp.arange(0, 15).reshape(3, 5)
x = F.swapaxes(x, 0, 1)
x = F.copy(x, gpu_b) # It doesn't work
```

* Error messages
```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    x = F.copy(x, gpu_b) # It doesn't work
  File "/path/to/chainer/functions/array/copy.py", line 86, in copy
    return Copy(dst)(x)
  File "/path/to/chainer/function.py", line 200, in __call__
    outputs = self.forward(in_data)
  File "/path/to/chainer/function.py", line 327, in forward
    return self.forward_gpu(inputs)
  File "/path/to/chainer/functions/array/copy.py", line 32, in forward_gpu
    return cuda.copy(x[0], out_device=self.out_device),
  File "/path/to/chainer/cuda.py", line 344, in copy
    cupy.copyto(out, array)
  File "/path/to/cupy/manipulation/basic.py", line 50, in copyto
    core.elementwise_copy(src, dst)
  File "cupy/core/core.pyx", line 1593, in cupy.core.core.elementwise_copy (cupy/core/core.cpp:57847)
  File "cupy/core/elementwise.pxi", line 736, in cupy.core.core.ufunc.__call__ (cupy/core/core.cpp:47475)
  File "cupy/core/elementwise.pxi", line 102, in cupy.core.core._preprocess_args (cupy/core/core.cpp:35238)
ValueError: Array device must be same as the current device: array device = 1 while current = 0
```

**Comment by niboshi** [comment]
Confirmed.
Thank you very much!
