### ISSUE TITLE
MultiprocessIterator crushes when used together with GPU

### ISSUE THREAD

**Issue by yuyu2172** [chainer/chainer#2962]
`MultiprocessIterator` crushes when cupy array creation happens inside a Dataset class.

My environment is 
+ Python 2.7.12 and 3.5.2
+ CUDA 8
+ Chainer 2.0.0
+ CuPy 1.0.0.1

There was a similar issue that had a problem with multiprocessing and multi GPU setting. https://github.com/chainer/chainer/issues/1087

In this case, I am having a problem with multiprocessing and single GPU.

```python
import chainer
import cupy
import numpy as np


class GPUDataset(chainer.dataset.DatasetMixin):

    def __init__(self, values):
        self.values = values

    def __len__(self):
        return len(self.values)

    def get_example(self, i):
        return cupy.asarray(self.values[i])


def main():
    dataset = GPUDataset(np.random.uniform(size=(12, 3)))

    it = chainer.iterators.MultiprocessIterator(
        dataset, batch_size=4, n_processes=1,
        repeat=True, shuffle=False
    )

    example = it.next()
    print('>>>>>>>>>>>>>>>>>>>>>>>>>finished fetching once')
    example = it.next()
    print('>>>>>>>>>>>>>>>>>>>>>>>>>finished fetching twice')


if __name__ == '__main__':
    main()

```

The error message is as follows.

```
>>>>>>>>>>>>>>>>>>>>>>>>>finished fetching once
Process Process-1:
Traceback (most recent call last):
  File "/home/leus/miniconda2/envs/general3/lib/python3.5/multiprocessing/process.py", line 249, in _boots
trap
    self.run()
  File "/home/leus/miniconda2/envs/general3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/leus/install/chainer_dev/chainer/iterators/multiprocess_iterator.py", line 390, in _worker
    data = _pack(dataset[index], mem)
  File "/home/leus/install/chainer_dev/chainer/dataset/dataset_mixin.py", line 67, in __getitem__
    return self.get_example(index)
  File "aaaa.py", line 15, in get_example
    return cupy.asarray(self.values[i])
  File "/home/leus/miniconda2/envs/general3/lib/python3.5/site-packages/cupy/creation/from_data.py", line 
46, in asarray
    return core.array(a, dtype, False)
  File "cupy/core/core.pyx", line 1795, in cupy.core.core.array (cupy/core/core.cpp:58633)
  File "cupy/core/core.pyx", line 1817, in cupy.core.core.array (cupy/core/core.cpp:58404)
  File "cupy/core/core.pyx", line 82, in cupy.core.core.ndarray.__init__ (cupy/core/core.cpp:6387)
  File "cupy/cuda/memory.pyx", line 283, in cupy.cuda.memory.alloc (cupy/cuda/memory.cpp:6076)
  File "cupy/cuda/memory.pyx", line 434, in cupy.cuda.memory.MemoryPool.malloc (cupy/cuda/memory.cpp:9344)
  File "cupy/cuda/memory.pyx", line 449, in cupy.cuda.memory.MemoryPool.malloc (cupy/cuda/memory.cpp:9221)
  File "cupy/cuda/device.pyx", line 18, in cupy.cuda.device.get_device_id (cupy/cuda/device.cpp:1339)
  File "cupy/cuda/runtime.pyx", line 158, in cupy.cuda.runtime.getDevice (cupy/cuda/runtime.cpp:2563)
  File "cupy/cuda/runtime.pyx", line 130, in cupy.cuda.runtime.check_status (cupy/cuda/runtime.cpp:2242)
cupy.cuda.runtime.CUDARuntimeError: cudaErrorInitializationError: initialization error
```

**Comment by niboshi** [comment]
For Python>=3.4, you can avoid this problem with this:
```
if __name__ == '__main__':
    multiprocessing.set_start_method('spawn')
    main()
```
For details: https://github.com/Theano/Theano/wiki/Using-Multiple-GPUs

**Comment by yuyu2172** [comment]
@niboshi 
Thank you for telling me that.
It seems that the link you mentioned answers well to this issue.
