### ISSUE TITLE
Error of ParallelUpdater + debug mode

### ISSUE THREAD

**Issue by shu65** [chainer/chainer#3004]
When I ran train_mnist_data_parallel.py with debug mode of chainer, it did not work with the following error. 

```
Traceback (most recent call last):
  File "train_mnist_data_parallel.py", line 81, in <module>
    main()
  File "train_mnist_data_parallel.py", line 77, in main
    trainer.run()
  File "/home/shu65/local/miniconda2/envs/python35/lib/python3.5/site-packages/chainer/training/trainer.py", line 296, in run
    update()
  File "/home/shu65/local/miniconda2/envs/python35/lib/python3.5/site-packages/chainer/training/updater.py", line 177, in update
    self.update_core()
  File "/home/shu65/local/miniconda2/envs/python35/lib/python3.5/site-packages/chainer/training/updater.py", line 306, in update_core
    loss = loss_func(*in_arrays)
  File "/home/shu65/local/miniconda2/envs/python35/lib/python3.5/site-packages/chainer/links/model/classifier.py", line 70, in __call__
    self.y = self.predictor(*x)
  File "/mnt/data/shu65/workspace/chainer/examples/mnist/train_mnist.py", line 32, in __call__
    h1 = F.relu(self.l1(x))
  File "/home/shu65/local/miniconda2/envs/python35/lib/python3.5/site-packages/chainer/links/connection/linear.py", line 127, in __call__
    return linear.linear(x, self.W, self.b)
  File "/home/shu65/local/miniconda2/envs/python35/lib/python3.5/site-packages/chainer/functions/connection/linear.py", line 107, in linear
    return LinearFunction()(x, W, b)
  File "/home/shu65/local/miniconda2/envs/python35/lib/python3.5/site-packages/chainer/function.py", line 208, in __call__
    for out in outputs):
  File "/home/shu65/local/miniconda2/envs/python35/lib/python3.5/site-packages/chainer/function.py", line 208, in <genexpr>
    for out in outputs):
  File "/home/shu65/local/miniconda2/envs/python35/lib/python3.5/site-packages/cupy/core/fusion.py", line 705, in __call__
    return self._cupy_op(*args, **kwargs)
  File "cupy/core/elementwise.pxi", line 736, in cupy.core.core.ufunc.__call__ (cupy/core/core.cpp:47481)
  File "cupy/core/elementwise.pxi", line 102, in cupy.core.core._preprocess_args (cupy/core/core.cpp:35244)
ValueError: Array device must be same as the current device: array device = 1 while current = 0
```
I think it causes that Function class checks NaN without Device of out.

* Conditions
  - Chainer version: 2.0.1
  - CuPy version:1.0.1
  - OS/Platform: Ubuntu 16.04.2 LTS
  - CUDA/cuDNN version：8.0 

* Code to reproduce
I added chainer.set_debug(True) to train_mnist_data_parallel.py as follows:
```
def main():
    chainer.set_debug(True)

    # This script is almost identical to train_mnist.py. The only difference is
```

**Comment by delta2323** [comment]
I can reproduce the error.

**Comment by delta2323** [comment]
Narrowed the problem

```
import chainer
import cupy
import numpy


class Dummy(chainer.Function):

    def forward(self, *_):
        return cupy.zeros(10),


with chainer.cuda.get_device_from_id(0):
    a = cupy.full((10, 10), numpy.nan)

with chainer.using_config('debug', True):
    with chainer.cuda.get_device_from_id(1):
        Dummy()(a)
```

**Comment by delta2323** [comment]
There are two alternatives for fixing the problem

1. Allow `cupy.isnan` to check values of arrays even if they do not reside in the current device.
2. Switch the current device in `chainer.Function.call` temporarily to the device input arrays are located in.

I prefer the latter choice: as forbidding device is an universal specification of ufanc's, it is unnatural only `isnan` behave differently. Although device switching could be costly, I think it is acceptable as we do it in the debug mode only.
