### ISSUE TITLE
how to load pretrained chainer npz parameter file but modify some layer?

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#3126]
I have pretrained a VGG network in chainer loadable npz file format, but add a new FC layer to last layer , and I modify last layer output class_number.
I have already modify the layer name in order to use chainer loadable file to other unaltered layer.
But I failed.
```
Traceback (most recent call last):
  File "chainercv/trainer/train.py", line 194, in <module>
    main()
  File "chainercv/trainer/train.py", line 85, in main
    mean_file=args.mean)  # 可改为/home/machen/face_expr/result/snapshot_model.npz
  File "/home/machen/face_expr/chainercv/links/model/faster_rcnn/faster_rcnn_vgg.py", line 131, in __init__
    chainer.serializers.load_npz(pretrained_model, self)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/chainer-3.0.0a1-py3.6.egg/chainer/serializers/npz.py", line 140, in load_npz
    d.load(obj)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/chainer-3.0.0a1-py3.6.egg/chainer/serializer.py", line 82, in load
    obj.serialize(self)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/chainer-3.0.0a1-py3.6.egg/chainer/link.py", line 794, in serialize
    d[name].serialize(serializer[name])
  File "/usr/local/anaconda3/lib/python3.6/site-packages/chainer-3.0.0a1-py3.6.egg/chainer/link.py", line 794, in serialize
    d[name].serialize(serializer[name])
  File "/usr/local/anaconda3/lib/python3.6/site-packages/chainer-3.0.0a1-py3.6.egg/chainer/link.py", line 550, in serialize
    data = serializer(name, param.data)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/chainer-3.0.0a1-py3.6.egg/chainer/serializers/npz.py", line 106, in __call__
    dataset = self.npz[key]
  File "/usr/local/anaconda3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 237, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'head/score_mod/W is not a file in the archive'
```

**Comment by fiarabbit** [comment]
Source code will help

**Comment by niboshi** [comment]
Hi, thank you for posting a question!
We consider GitHub issues is not a good place for user support. We recommend posting to [StackOverflow](https://stackoverflow.com/) instead (with `chainer` tag).

There are several reasons:
* It will be more helpful to other users. StackOverflow is focusing on accumluating knowledges.
* We have limited resources and can't handle every users' problems. In StackOverflow, you have more chance to get an answer from many developers. We are watching StackOverflow posts with `chainer` tag, so we will likely be able to help anyway.

Of course, we always welcome bug reports / feature suggestions.
Thank you for your cooperation!
