### ISSUE TITLE
Doesn't check_double_backward work with FunctionNode whose backward is implemented with FunctionNode?

### ISSUE THREAD

**Issue by delta2323** [chainer/chainer#3171]
(This issue is related to #3096, let me know if I should write it there)

[New-style Function Implementation Guideline](https://gist.github.com/beam2d/dd87d97b8d7581f95cd19b1de86c9f4d) recommends that we should use `FunctionNode` to implement `FunctionNode.backward` if an existing function has optimized backward implementation (e.g. using cuDNN). When I tried to rewrite `F.relu` (#3147) to the new-style API, following the guideline and tested the function with `gradient_check.check_double_backward`, I got an error. The following code is the essence (I believe) of the implementation.

* Code to reproduce
```
import chainer
from chainer import function_node
from chainer import gradient_check
import numpy as np


class Dummy(function_node.FunctionNode):

    def forward(self, inputs):
        return inputs

    def backward(self, indexes, gy):
        return DummyGrad().apply(gy)


class DummyGrad(function_node.FunctionNode):

    def forward(self, inputs):
        return inputs

    def backward(self, indexes, gy):
        return gy


def dummy(x):
    y, = Dummy().apply((x,))
    return y


x = np.array([[1, 2], [3, 4]], dtype=np.float32)
gy = np.ones_like(x, dtype=np.float32)
ggx = np.ones_like(x, dtype=np.float32)
gradient_check.check_double_backward(dummy, x, gy, ggx)
```

* Error messages, stack traces, or logs
```
Traceback (most recent call last):
  File "test2.py", line 33, in <module>
    gradient_check.check_double_backward(dummy, x, gy, ggx)
  File "/home/delta/dev/chainer/chainer/gradient_check.py", line 394, in check_double_backward
    dtype=dtype)
  File "/home/delta/dev/chainer/chainer/gradient_check.py", line 277, in check_backward
    'gradients of some arguments are not calculated')
RuntimeError: gradients of some arguments are not calculated
```

I also confirmed that the backward method of `Identity`, which is inserted by `check_double_backward`, and `DummyGrad` is called. Let me know if I use `check_double_backward` wrongly or I misunderstand the guideline.

**Comment by delta2323** [comment]
I put the comment to #3096.
