### ISSUE TITLE
Bug: can't perform doctest in chainer.functions.array

### ISSUE THREAD

**Issue by naoto0804** [chainer/chainer#3300]
When I insert following lines in `chainer.functions.array.where.py` and run doctest, 
```python
if __name__ == "__main__":
    import doctest
    import numpy as np
    # import cupy  # comment out if you don' have GPU
    import chainer
    from chainer import cuda, Function, gradient_check, training, utils, Variable
    from chainer import datasets, iterators, optimizers, serializers
    from chainer import Link, Chain, ChainList
    import chainer.functions as F
    import chainer.links as L
    from chainer.training import extensions
    np.random.seed(0)
    doctest.testmod()
```
following error raises:

```
Traceback (most recent call last):
  File "chainer/functions/array/where.py", line 1, in <module>
    import numpy
  File "/home/inoue/.chainer_dev/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/home/inoue/.chainer_dev/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/inoue/.chainer_dev/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/inoue/.chainer_dev/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/inoue/.chainer_dev/lib/python3.6/site-packages/numpy/core/__init__.py", line 74, in <module>
    from numpy.testing.nosetester import _numpy_tester
  File "/home/inoue/.chainer_dev/lib/python3.6/site-packages/numpy/testing/__init__.py", line 10, in <module>
    from unittest import TestCase
  File "/home/inoue/.local/lib/python3.6/unittest/__init__.py", line 64, in <module>
    from .main import TestProgram, main
  File "/home/inoue/.local/lib/python3.6/unittest/main.py", line 4, in <module>
    import argparse
  File "/home/inoue/.local/lib/python3.6/argparse.py", line 87, in <module>
    import copy as _copy
  File "/home/inoue/experiment/chainer/chainer/functions/array/copy.py", line 1, in <module>
    from chainer import cuda
  File "/home/inoue/experiment/chainer/chainer/__init__.py", line 3, in <module>
    import pkg_resources
  File "/home/inoue/.chainer_dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 71, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/home/inoue/.chainer_dev/lib/python3.6/site-packages/pkg_resources/_vendor/packaging/requirements.py", line
 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/home/inoue/.chainer_dev/lib/python3.6/site-packages/pkg_resources/extern/__init__.py", line 42, in load_mo
dule
    __import__(extant)
  File "/home/inoue/.chainer_dev/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 3402, in <mo
dule>
    _reBracketExpr = Literal("[") + Optional("^").setResultsName("negate") + Group( OneOrMore( _charRange | _single
Char ) ).setResultsName("body") + "]"
  File "/home/inoue/.chainer_dev/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 857, in setR
esultsName
    newself = self.copy()
  File "/home/inoue/.chainer_dev/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 831, in copy
    cpy = copy.copy( self )
AttributeError: module 'copy' has no attribute 'copy'
```

I suspect this is caused by `chainer/functions/array/copy.py`, which prevents importing `copy` module in python.
How can I handle such situation and perform doctest?

**Comment by niboshi** [comment]
I guess you're directly running `chainer/functions/array/where.py`.
How about launching this way (from outside chainer directory tree)?
```
$ python -m chainer.functions.array.where
```

**Comment by naoto0804** [comment]
It works fine. Thank you.
