### ISSUE TITLE
TestMatMulVarVar in test_basic_math is unstable

### ISSUE THREAD

**Issue by ishihara1989** [chainer/chainer#3360]
Hello!

I sent a PR(https://github.com/chainer/chainer/pull/3359), which just adds a function.
Unfortunately appveyor(Environment: PYTHON=C:\Miniconda35, PYTHON_VERSION=3.5.x, PYTHON_ARCH=32) rejected my PR, but the log looks odd. 
The test failed at `test_basic_math`, which shouldn't be affected by my code. The corresponding log is below:

```
======================================================================
FAIL: test_backward_cpu (test_basic_math.transplant_class.<locals>.C)  parameter: {'left_const': False, 'right_const': False, 'y_shape': (2, 4), 'z_shape': (3, 4), 'dtype': <class 'numpy.float16'>, 'x_shape': (3, 2)}
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\chainer\tests\chainer_tests\functions_tests\math_tests\test_basic_math.py", line 1072, in test_backward_cpu
    self.check_backward(self.x, self.y, self.gz)
  File "C:\projects\chainer\tests\chainer_tests\functions_tests\math_tests\test_basic_math.py", line 1067, in check_backward
    op, data, z_grad, dtype=numpy.float64, **options)
  File "C:\Miniconda35\lib\site-packages\chainer-3.0.0b1-py3.5.egg\chainer\gradient_check.py", line 341, in check_backward
    testing.assert_allclose(gx, gx_accum, atol=atol, rtol=rtol)
  File "C:\Miniconda35\lib\site-packages\chainer-3.0.0b1-py3.5.egg\chainer\testing\array.py", line 25, in assert_allclose
    x, y, atol=atol, rtol=rtol, verbose=verbose)
  File "C:\Miniconda35\lib\site-packages\numpy\testing\utils.py", line 1395, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "C:\Miniconda35\lib\site-packages\numpy\testing\utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.001, atol=0.001
(mismatch 100.0%)
 x: array(-0.07159511438119834)
 y: array(-0.07038052380084991)
-------------------- >> begin captured stdout << ---------------------
assert_allclose failed: 
  shape: () ()
  dtype: float64 float64
  i: (0,)
  x[i]: -0.07159511438119834
  y[i]: -0.07038052380084991
  err[i]: 0.0012145905803484236
x: -0.07159511438119834
y: -0.07038052380084991

```

Perhaps `rtol=0.001, atol=0.001` is too strict for `numpy.float16` inputs?

**Comment by bkvogel** [comment]
Thank you for the PR and sorry for the delay in replying. From a quick skim through your code, I think I agree that the error is unrelated and that maybe the tolerances are too strict. I suspect once someone reviews your PR and you submit a change, the error hopefully will not occur again, so no need to worry.
