### ISSUE TITLE
Shape of data and grad mismatch

### ISSUE THREAD

**Issue by PengjieRen** [chainer/chainer#3398]
```
Traceback (most recent call last):
  File "/storage/renpengjie/chainer-summarization/train.py", line 60, in <module>
    trainer.run()
  File "/storage/renpengjie/chainer-summarization/base/trainer.py", line 51, in run
    batch_loss= self.updater.update_core()
  File "/storage/renpengjie/chainer-summarization/base/updater.py", line 104, in update_core
    loss.backward()                     # Backprop
  File "/root/anaconda2/lib/python2.7/site-packages/chainer-3.0.0rc1-py2.7.egg/chainer/variable.py", line 852, in backward
    self._backward_main(retain_grad)
  File "/root/anaconda2/lib/python2.7/site-packages/chainer-3.0.0rc1-py2.7.egg/chainer/variable.py", line 987, in _backward_main
    _check_grad_type(func, x, gx.data)
  File "/root/anaconda2/lib/python2.7/site-packages/chainer-3.0.0rc1-py2.7.egg/chainer/variable.py", line 51, in _check_grad_type
    raise typ(detail + msg)
ValueError: Function `<property object at 0x2b30178b8050>` (_ * _) has a bug.

Please report this error to the issue tracker with the stack trace,
the information of your environment, and your script:
https://github.com/chainer/chainer/issues/new.
Shape of data and grad mismatch
(100, 1) != (100, 1000)
```

**Comment by niboshi** [comment]
Could you provide some code to reproduce this error?

**Comment by PengjieRen** [comment]
Sorry, I think I figure it out. It's my problem

**Comment by niboshi** [comment]
Good to hear that!
Thank you for reporting any way :smiley:
