### ISSUE TITLE
L.NStepLSTM occurred error when pytorch uses together

### ISSUE THREAD

**Issue by odanado** [chainer/chainer#3456]
When I use chainer and pytorch in the same code, I often got a `cupy.cuda.cudnn.CuDNNError` . 
I found the cause that is the order of `import` .
* Conditions
  - Chainer v2.1.0
  - CuPy v1.0.3 
  - Ubuntu16.04 (using nvidia-docker)
  - cuda8.0, cudnn5 (image is nvidia/cuda:8.0-cudnn5-devel)
  -  pytorch 0.2.0_4

* Code to reproduce
```
import chainer
import torch
encoder = chainer.links.NStepLSTM(1, 10, 10, 0.5).to_gpu()
x = chainer.Variable(encoder.xp.random.rand(10, 10, dtype='f'))
_ = encoder(None, None, [x]) # OK
```

```
import torch
import chainer
encoder = chainer.links.NStepLSTM(1, 10, 10, 0.5).to_gpu()
x = chainer.Variable(encoder.xp.random.rand(10, 10, dtype='f'))
_ = encoder(None, None, [x]) # NG
```
* Error messages, stack traces, or logs
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.5/site-packages/chainer/links/connection/n_step_lstm.py", line 123, in __call__
    self.n_layers, self.dropout, hx, cx, ws, bs, trans_x)
  File "/opt/conda/lib/python3.5/site-packages/chainer/functions/connection/n_step_lstm.py", line 132, in n_step_lstm
    use_bi_direction=False, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/chainer/functions/connection/n_step_lstm.py", line 332, in n_step_lstm_base
    ret = rnn(*inputs)
  File "/opt/conda/lib/python3.5/site-packages/chainer/function.py", line 201, in __call__
    outputs = self.forward(in_data)
  File "/opt/conda/lib/python3.5/site-packages/chainer/functions/connection/n_step_rnn.py", line 341, in forward
    x_desc, w_desc, w, lin_layer_id)
  File "/opt/conda/lib/python3.5/site-packages/cupy/cudnn.py", line 312, in get_rnn_lin_layer_matrix_params
    lin_layer_id, mat_desc.value, ptr.ctypes.data)
  File "cupy/cuda/cudnn.pyx", line 1222, in cupy.cuda.cudnn.getRNNLinLayerMatrixParams (cupy/cuda/cudnn.cpp:16036)
  File "cupy/cuda/cudnn.pyx", line 1229, in cupy.cuda.cudnn.getRNNLinLayerMatrixParams (cupy/cuda/cudnn.cpp:15884)
  File "cupy/cuda/cudnn.pyx", line 417, in cupy.cuda.cudnn.check_status (cupy/cuda/cudnn.cpp:2053)
cupy.cuda.cudnn.CuDNNError: CUDNN_STATUS_NOT_SUPPORTED: b'CUDNN_STATUS_NOT_SUPPORTED'
```

**Comment by unnonouno** [comment]
Thank you for reporting problem. cuDNN has global status. I think it conflicts between chainer and pytorch. I'll check it.
