### ISSUE TITLE
xxx_pooling_nd fails with CUDNN_STATUS_BAD_PARAM when size==0 and using cuDNN

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#3554]
### Code
```
import chainer
import numpy
import cupy

x_shape = (1, 1, 1, 0)
x = cupy.ones(x_shape, dtype=numpy.float32)
y = chainer.functions.max_pooling_nd(x, ksize=1, stride=1, pad=0)
```

### Result
```
Traceback (most recent call last):
  File "test-cudnn2.py", line 8, in <module>
    y = chainer.functions.max_pooling_nd(x, ksize=1, stride=1, pad=0)
  File "/data/work/w/repos/chainer/chainer/functions/pooling/max_pooling_nd.py", line 148, in max_pooling_nd
    return MaxPoolingND(ndim, ksize, stride, pad, cover_all)(x)
  File "/data/work/w/repos/chainer/chainer/function.py", line 212, in __call__
    ret = node.apply(inputs)
  File "/data/work/w/repos/chainer/chainer/function_node.py", line 223, in apply
    outputs = self.forward(in_data)
  File "/data/work/w/repos/chainer/chainer/function.py", line 117, in forward
    return self._function.forward(inputs)
  File "/data/work/w/repos/chainer/chainer/function.py", line 319, in forward
    return self.forward_gpu(inputs)
  File "/data/work/w/repos/chainer/chainer/functions/pooling/max_pooling_nd.py", line 50, in forward_gpu
    return super(MaxPoolingND, self).forward_gpu(x)
  File "/data/work/w/repos/chainer/chainer/functions/pooling/pooling_nd.py", line 54, in forward_gpu
    x_desc = cudnn.create_tensor_descriptor(x)
  File "/data/work/w/repos/cupy/cupy/cudnn.py", line 81, in create_tensor_descriptor
    cudnn.setTensor4dDescriptor(desc.value, format, data_type, *arr.shape)
  File "cupy/cuda/cudnn.pyx", line 497, in cupy.cuda.cudnn.setTensor4dDescriptor
  File "cupy/cuda/cudnn.pyx", line 502, in cupy.cuda.cudnn.setTensor4dDescriptor
  File "cupy/cuda/cudnn.pyx", line 445, in cupy.cuda.cudnn.check_status
cupy.cuda.cudnn.CuDNNError: CUDNN_STATUS_BAD_PARAM: b'CUDNN_STATUS_BAD_PARAM'

```

### Environment
Version: current master (5b5bea2)

```
$ /usr/local/cuda/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
```

```
$ cudnnenv version
v7-cuda8
```

**Comment by niboshi** [comment]
I think pooling operations do not support such input.
I made a fix to generate more friendly error message. #3555.
