### ISSUE TITLE
doctest cannot pass without multi-GPU

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#3660]
When doctest is run in single-GPU environment, it will fail on multi-GPU tutorial.

```
$ cd docs && make doctest
```

```
File "tutorial/gpu.rst", line 131, in default
Failed example:
    with cupy.cuda.Device(1):
        x_on_gpu1 = cupy.array([1, 2, 3, 4, 5])
Exception raised:
    Traceback (most recent call last):
      File "/home/niboshi/anaconda/anaconda2/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest default[0]>", line 1, in <module>
        with cupy.cuda.Device(1):
      File "cupy/cuda/device.pyx", line 97, in cupy.cuda.device.Device.__enter__
        self.use()
      File "cupy/cuda/device.pyx", line 112, in cupy.cuda.device.Device.use
        runtime.setDevice(self.id)
      File "cupy/cuda/runtime.pyx", line 185, in cupy.cuda.runtime.setDevice
        check_status(status)
      File "cupy/cuda/runtime.pyx", line 137, in cupy.cuda.runtime.check_status
        raise CUDARuntimeError(status)
    CUDARuntimeError: cudaErrorInvalidDevice: invalid device ordinal
```

**Comment by kmaehashi** [comment]
Maybe document this on contribution guide?
I don't come up with idea to fix this cleanly.

**Comment by niboshi** [comment]
I think that's OK.
Can we also write a hidden test code that fails with more friendly message, prior to the above test?
