### ISSUE TITLE
Chainer functions do not work with arrays with shape=()

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#3701]
### Code:
```
import chainer, numpy

class Func(chainer.FunctionNode):
    def forward(self, inputs):
        x, = inputs
        y = x + 2
        assert isinstance(y, numpy.float64)  # !
        return y,

    def backward(self, indexes, grad_outputs):
        gy, = grad_outputs
        return gy,

x = numpy.ones((), 'f')
y = Func().apply((x,))

print(y)
```
(Same for `chainer.Function` functions)

### Result:
```
Traceback (most recent call last):
  File "test-func.py", line 15, in <module>
    y = Func().apply((x,))
  File "/data/work/w/repos/chainer/chainer/function_node.py", line 241, in apply
    for y in outputs])
  File "/data/work/w/repos/chainer/chainer/function_node.py", line 241, in <listcomp>
    for y in outputs])
  File "/data/work/w/repos/chainer/chainer/variable.py", line 454, in __init__
    raise TypeError(msg)
TypeError: numpy.ndarray or cuda.ndarray are expected.
Actual: <class 'numpy.float64'>
```

### Cause:
As written in the code, even if `x` is `numpy.ndarray`, `x + 2` results in `numpy.float64` instead of `numpy.ndarray`.

### Version:
current master (97ed424af9579c1a6ac5ded6f3e5c5c29985fe33)

**Comment by niboshi** [comment]
I think it's Chainer's convention to use `chainer.utils.force_array` to return array in such situations.
I'm closing the issue.
