### ISSUE TITLE
L.Linear without in_size raises ZeroDivisionError on first input if the batchsize is 0

### ISSUE THREAD

**Issue by toslunar** [chainer/chainer#3863]
This is probably fixed by changing `x.size // x.shape[0]` to `numpy.prod(x.shape[1:])` though it requires numpy.  (Note: The current code is no better than `x[0].size`.)

Motivation: I'd like to initialize a Chain by a 'dry run'.

To reproduce:
```
>>> import chainer
>>> import numpy as np
>>> l=chainer.links.Linear(4)
>>> l(np.ones((2, 3), dtype=np.float32))
variable([[-0.93691719,  1.47195649, -0.66054785,  0.62899256],
          [-0.93691719,  1.47195649, -0.66054785,  0.62899256]])
>>> l(np.ones((0, 3), dtype=np.float32))
variable([], shape=(0, 4))
>>> l=chainer.links.Linear(4)
>>> l(np.ones((0, 3), dtype=np.float32))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/****/lib/python3.6/site-packages/chainer/links/connection/linear.py", line 126, in __call__
    self._initialize_params(x.size // x.shape[0])
ZeroDivisionError: integer division or modulo by zero
>>> chainer.__version__
'3.0.0'
```

**Comment by hvy** [comment]
@toslunar Thank you for reporting. I sent a PR #3871 to fix this issue.
