### ISSUE TITLE
Type check of split_axis doesn't accept indices larger than or equal to size of input array.

### ISSUE THREAD

**Issue by hisaknown** [chainer/chainer#4012]
Type check of `functions.split_axis` raises `InvalidType` when `indices_or_sections` is a list which contains values larger than or equal to the size of `x` along `axis`.

* Conditions
  - Chainer version 3.1.0
* Code to reproduce
```python
import numpy as np
import chainer.functions as F

x = np.arange(10)
F.split_axis(x, [5, 10], axis=0)  # Raises InvalidType
```
* Error message
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\chainer\functions\array\split_axis.py", line 92, in split_axis
    res = SplitAxis(indices_or_sections, axis).apply((x,))
  File "C:\Python36\lib\site-packages\chainer\function_node.py", line 228, in apply
    self._check_data_type_forward(in_data)
  File "C:\Python36\lib\site-packages\chainer\function_node.py", line 296, in _check_data_type_forward
    self.check_type_forward(in_type)
  File "C:\Python36\lib\site-packages\chainer\functions\array\split_axis.py", line 37, in check_type_forward
    type_check.expect(in_types[0].shape[self.axis] > max_index)
  File "C:\Python36\lib\site-packages\chainer\utils\type_check.py", line 519, in expect
    expr.expect()
  File "C:\Python36\lib\site-packages\chainer\utils\type_check.py", line 477, in expect
    '{0} {1} {2}'.format(left, self.inv, right))
chainer.utils.type_check.InvalidType:
Invalid operation is performed in: SplitAxis (Forward)

Expect: in_types[0].shape[0] > max_index
Actual: 10 <= 10
```
----

Expected behavior is returning below like `numpy.split` does:
```
(variable([0, 1, 2, 3, 4]), variable([5, 6, 7, 8, 9]), variable([]))
```
Please note that `numpy.split` also accepts indices larger than the size of the input, not only the index equal to it. (e.g. `numpy.split(x, [5, 10], axis=0)` and  `numpy.split(x, [5, 15], axis=0)` give the same result, without errors.)
**This type check failure occurs also in backprop of `functions.concat` when an empty array is concatenated at the end.**

Could you consider making `functions.split_axis` accept the indices larger than or equal to the size of the input?

**Comment by unnonouno** [comment]
This issue is fixed via #4153
