### ISSUE TITLE
why chainer.functions doesn't have sign

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#4240]
in the document page: https://docs.chainer.org/en/stable/reference/generated/chainer.functions.sign.html?highlight=sign
there is F.sign in API document, but when I type 
>>> F.sign
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'chainer.functions' has no attribute 'sign'

**Comment by niboshi** [comment]
Thank you for reporting!
I guess you are using Chainer < v.3.2.0?
`F.sign` was introduced in v3.2.0.

**Comment by sharpstill** [comment]
@niboshi I use `pip install chainer` to install chainer , which is v3.1.0

**Comment by sharpstill** [comment]
@niboshi I install cupy on windows 10 failed. Can you write an essay how to install cupy on windows. below is my message.
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64>pip install cupy
Collecting cupy
  Using cached cupy-2.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    **************************************************
    *** WARNING: Cannot find nvToolsExt. nvtx was disabled.
    **************************************************
    Options: {'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False}
    Include directories: ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\include']
    Library directories: ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\lib\\x64']
    Unable to find a compatible Visual Studio installation.
    **************************************************
    *** WARNING: Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'curand.h', 'cusparse.h', 'nvrtc.h']
    *** WARNING: Skip installing cuda support
    *** WARNING: Check your CFLAGS environment variable
    **************************************************
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\machen\AppData\Local\Temp\pip-build-99v3gyly\cupy\setup.py", line 32, in <module>
        ext_modules = cupy_setup_build.get_ext_modules()
      File "C:\Users\machen\AppData\Local\Temp\pip-build-99v3gyly\cupy\cupy_setup_build.py", line 378, in get_ext_modules
        extensions = make_extensions(arg_options, compiler, use_cython)
      File "C:\Users\machen\AppData\Local\Temp\pip-build-99v3gyly\cupy\cupy_setup_build.py", line 268, in make_extensions
        raise Exception('Your CUDA environment is invalid. '
    Exception: Your CUDA environment is invalid. Please check above error log.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\machen\AppData\Local\Temp\pip-build-99v3gyly\cupy\
```

**Comment by niboshi** [comment]
Which Python version are you using?
For Visual C++ 14, supported versions are 3.5 and 3.6 ([see here](https://wiki.python.org/moin/WindowsCompilers)).

By the way, you can use `pip install -U chainer` to upgrade the installed package to the latest.

**Comment by sharpstill** [comment]
@niboshi I use anaconda 3.6 on windows, and I have installed visual studio 2015 already
