### ISSUE TITLE
MultiprocessIterator.reset() unavailable after its finalization

### ISSUE THREAD

**Issue by tkanmae** [chainer/chainer#4257]
After updating from Chainer 3.2.0 to 3.3.0, calling `reset()` method of an finalized `MultiprocessIterator` object raises `NotImplementedError`. I noticed this issue when our code failed to call `reset()` on a `MultiprocessIterator` object right after a normal termination of training using `Trainer`. This breaks the code that works with 3.2.0 and prior.

Is this an intended change introduced in 3.3.0?

## Environment
  - Chainer 3.3.0
  - CuPy 2.1.0
  - Python 3.5.2
  - Ubuntu 16.04
  - CUDA v9.0.176, cuDNN v7.0.3

## Error messages
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/alchimie-vision", line 11, in <module>
    load_entry_point('alchimie-vision', 'console_scripts', 'alchimie-vision')()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 87, in augment_usage_errors
    yield
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/alchimie-vision/alchimie_vision/classification/commands/train.py", line 272, in main
    evaluate(model, valid_iter, config)
  File "/home/ubuntu/alchimie-vision/alchimie_vision/classification/commands/train.py", line 187, in evaluate
    probs = predict(model, valid_iter, config)
  File "/home/ubuntu/alchimie-vision/alchimie_vision/classification/commands/train.py", line 179, in predict
    probs.append(p.squeeze())
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/chainer/configuration.py", line 125, in using_config
    yield
  File "/home/ubuntu/alchimie-vision/alchimie_vision/classification/commands/train.py", line 172, in predict
    valid_iter.reset()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/chainer/iterators/multiprocess_iterator.py", line 169, in reset
    'Reset of finalized MultiProcessIterator is currently not '
NotImplementedError: Reset of finalized MultiProcessIterator is currently not supported.
```

**Comment by grafi-tt** [comment]
I believe the change is due to #4145. Supporting `reset()` after finalization for `MultiprocessIterator` is not much hard if we should re-initialize the internal state, but such re-initialization is unacceptable because it make the issue solved by #4145 to appear again.

I created the following minimal example to reproduce the deadlock issue. (But one of my colleagues said he can't reproduce the hang. Apparently it is timing dependant.)

```python
from chainer.iterators import MultiprocessIterator


dataset = list(range(100))
iterator = MultiprocessIterator(dataset, 4, repeat=False, shuffle=False)
for _ in iterator: pass
```

I suppose the fundamental cause of the issue is that a daemon thread won't be scheduled when the interpreter is exiting even if a condition variable waiting for is notified. So the thread waiting for a space in the queue never wakes, even though `MultiprocessIterator.__del__` calls `_Communicator.terminate`, which in turn notifies the condition variable.

I propose the following patch that makes the background thread ignored when the interpreter is exiting. I'm neutral about whether #4145 should be reverted, as calling `finalize` may catch some errors in user codes and/or internal codes.

```patch
diff --git a/chainer/iterators/multiprocess_iterator.py b/chainer/iterators/multiprocess_iterator.py
index 81083c45b..16e653b7c 100644
--- a/chainer/iterators/multiprocess_iterator.py
+++ b/chainer/iterators/multiprocess_iterator.py
@@ -1,4 +1,5 @@
 from __future__ import division
+import atexit
 from collections import namedtuple
 import multiprocessing
 from multiprocessing import sharedctypes
@@ -528,3 +529,10 @@ def _unpack(data, mem):
     elif t is _PackedNdarray:
         data = data.unpack(mem)
     return data
+
+
+def _force_finalize_at_exit():
+    MultiprocessIterator._finalized = True
+
+
+atexit.register(_force_finalize_at_exit)
```
