### ISSUE TITLE
unable to install CUPY

### ISSUE THREAD

**Issue by ykim104** [chainer/chainer#4311]
Hello, I am trying to install cupy but I am running into a problem. I am trying to run a code using chainer and I ran into issues with cupy. (No module found). I thought installing cupy might solve a problem but it has its own issue.

pip install cupy 

gives me this error message: 

`Downloading from URL https://pypi.python.org/packages/51/ce/9c4789dd570935c5fd8c9f71aa4e0761aaaef195ef1f017e4174e7c266dc/cupy-2.3.0.tar.gz#md5=7dcbf8d7451f7acda797f870180441ea (from https://pypi.python.org/simple/cupy/)
  Running setup.py (path:/tmp/pip-build-tLYIDm/cupy/setup.py) egg_info for package cupy
    Running command python setup.py egg_info
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    /tmp/tmpGE0opq/a.cpp:1:23: fatal error: cublas_v2.h: No such file or directory
    compilation terminated.
    Options: {'profile': False, 'annotate': False, 'linetrace': False, 'no_cuda': False}
    **************************************************
    *** WARNING: nvcc not in path.
    *** WARNING: Please set path to nvcc.
    **************************************************
    Include directories: []
    Library directories: []
    command 'x86_64-linux-gnu-gcc' failed with exit status 1
    **************************************************
    *** WARNING: Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'curand.h', 'cusparse.h', 'nvrtc.h', 'nvToolsExt.h']
    *** WARNING: Skip installing cuda support
    *** WARNING: Check your CFLAGS environment variable
    **************************************************
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-tLYIDm/cupy/setup.py", line 32, in <module>
        ext_modules = cupy_setup_build.get_ext_modules()
      File "cupy_setup_build.py", line 378, in get_ext_modules
        extensions = make_extensions(arg_options, compiler, use_cython)
      File "cupy_setup_build.py", line 268, in make_extensions
        raise Exception('Your CUDA environment is invalid. '
    Exception: Your CUDA environment is invalid. Please check above error log.
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-tLYIDm/cupy/
Exception information:
Traceback (most recent call last):
  File "/home/yejinkim/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/yejinkim/.local/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/home/yejinkim/.local/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/yejinkim/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/yejinkim/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/home/yejinkim/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/home/yejinkim/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/yejinkim/.local/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-tLYIDm/cupy/
`

**Comment by ykim104** [comment]
I saw that nvcc was empty. Solved the issue by installing NVIDIA toolkit.
