### ISSUE TITLE
chainer.serializers.save_npz does not work

### ISSUE THREAD

**Issue by kan-bayashi** [chainer/chainer#4314]
* Conditions
  - Python version: 2.7.5
  - Chainer version: 3.3.0
  - CuPy version: 2.3.0
  - Numpy version: 1.14.0
  - OS/Platform CentOS 7
  - CUDA/cuDNN version cuda 8.0 / cuDNN 6

* Code to reproduce
```
import chainer
import chainer.functions as F
import chainer.links as L


class MLP(chainer.Chain):

    def __init__(self, n_units, n_out):
        super(MLP, self).__init__()
        with self.init_scope():
            # the size of the inputs to each layer will be inferred
            self.l1 = L.Linear(None, n_units)  # n_in -> n_units
            self.l2 = L.Linear(None, n_units)  # n_units -> n_units
            self.l3 = L.Linear(None, n_out)  # n_units -> n_out

    def __call__(self, x):
        h1 = F.relu(self.l1(x))
        h2 = F.relu(self.l2(h1))
        return self.l3(h2)


model = MLP(10, 10)

# done not work
chainer.serializers.save_npz("model.npz", model)

# works
chainer.serializers.save_hdf5("model.h5", model)
```

* Error messages, stack traces, or logs
```
$ python test.py
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    chainer.serializers.save_npz("model.npz", model)
  File "/work3/t_hayashi/work/espnet_debug/tools/venv/lib/python2.7/site-packages/chainer/serializers/npz.py", line 73, in save_npz
    save_npz(f, obj, compression)
  File "/work3/t_hayashi/work/espnet_debug/tools/venv/lib/python2.7/site-packages/chainer/serializers/npz.py", line 79, in save_npz
    numpy.savez_compressed(file, **s.target)
  File "/work3/t_hayashi/work/espnet_debug/tools/venv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 659, in savez_compressed
    _savez(file, args, kwds, True)
  File "/work3/t_hayashi/work/espnet_debug/tools/venv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 716, in _savez
    pickle_kwargs=pickle_kwargs)
  File "/work3/t_hayashi/work/espnet_debug/tools/venv/lib/python2.7/site-packages/numpy/lib/format.py", line 562, in write_array
    version)
  File "/work3/t_hayashi/work/espnet_debug/tools/venv/lib/python2.7/site-packages/numpy/lib/format.py", line 308, in _write_array_header
    header = asbytes(_filter_header(header))
  File "/work3/t_hayashi/work/espnet_debug/tools/venv/lib/python2.7/site-packages/numpy/lib/format.py", line 467, in _filter_header
    return tokenize.untokenize(tokens)
  File "/usr/lib64/python2.7/tokenize.py", line 262, in untokenize
    return ut.untokenize(iterable)
  File "/usr/lib64/python2.7/tokenize.py", line 198, in untokenize
    self.add_whitespace(start)
  File "/usr/lib64/python2.7/tokenize.py", line 187, in add_whitespace
    assert row <= self.prev_row
AssertionError
Exception ValueError: 'I/O operation on closed file' in <bound method ZipFile.__del__ of <zipfile.ZipFile object at 0x3ee5710>> ignored
```

If use chainer==3.0.0 and numpy==1.13, it works.
But with numpy==1.14, it does not work.

**Comment by delta2323** [comment]
Hi, thank you for reporting the problem and sorry for late response. I can reproduce your error with MacOSX (10.13.4). I notice that when I upgrade Python version from v2.7.5. to v2.7.14, it disappears, too. So, if you still have the trouble and can upgrade either NumPy or Python, I would recommend to do so.

**Comment by delta2323** [comment]
Hi, thank you for reporting the problem and sorry for late response. I was able to reproduce your error with MacOSX (10.13.4). I also notice that it disappears either by upgrading to NumPy 1.14.3 or to Python 2.7.13. So, if you still have the trouble and can upgrade Python version, I would recommend to do so.

**Comment by kmaehashi** [comment]
If you still have any issue feel free to reopen this issue.
