### ISSUE TITLE
cuDNN deterministic test failure in F.deconvolution_2d

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#4329]
Current master (dba9ca351c0ea0401ae2d7d59abbc862abf77e7b)

I repeated 1000 times and failed at the 196th iteration.
```
_________________________________________________________________ TestDeconvolution2DFunctionCudnnDeterministic_param_0.test_cudnn_deterministic __________________________________________________________________
chainer/testing/parameterized.py:58: in wrap        
    six.raise_from(e_new.with_traceback(e.__traceback__), None)                                          
chainer/testing/parameterized.py:43: in wrap        
    return method(*args, **kwargs)                  
chainer/testing/condition.py:74: in wrapper         
    fail()                                          
chainer/testing/condition.py:51: in fail            
    instance.fail(msg)                              
E   AssertionError: Parameterized test failed.      
E                                                   
E   Base test method: TestDeconvolution2DFunctionCudnnDeterministic.test_cudnn_deterministic             
E   Test parameters:                                
E     c_contiguous: True                            
E     cudnn_deterministic: False                    
E     group: 2                                      
E     nobias: True                                  
E                                                   
E   AssertionError:                                 
E   Fail: 1, Success: 195                           
E                                                   
E   The first error message:                        
E   Traceback (most recent call last):              
E     File "/data/work/w/repos/chainer/chainer/testing/condition.py", line 60, in <lambda>               
E       lambda: f(ins, *args[1:], **kwargs),        
E     File "/data/work/w/repos/chainer/tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py", line 393, in test_cudnn_deterministic                                                       
E       cuda.cupy.testing.assert_array_equal(y1.data, y2.data)                                           
E     File "/data/work/w/repos/cupy/cupy/testing/array.py", line 91, in assert_array_equal               
E       verbose=verbose)                            
E     File "/home/niboshi/anaconda/anaconda3/lib/python3.6/site-packages/numpy/testing/utils.py", line 854, in assert_array_equal                                                                                  
E       verbose=verbose, header='Arrays are not equal')                                                  
E     File "/home/niboshi/anaconda/anaconda3/lib/python3.6/site-packages/numpy/testing/utils.py", line 778, in assert_array_compare                                                                                
E       raise AssertionError(msg)                   
E   AssertionError:                                 
E   Arrays are not equal                            
E                                                   
E   (mismatch 0.011817226890755705%)                
E    x: array([[[[ -3.130819e-01,  -2.397932e-01,  -3.461160e-01, ...,                                   
E               5.865743e-02,   3.421440e-01,  -8.247469e-02],                                           
E            [  2.177014e-01,  -5.023782e-02,  -9.351169e-02, ...,...                                    
E    y: array([[[[ -3.130819e-01,  -2.397932e-01,  -3.461160e-01, ...,                                   
E               5.865743e-02,   3.421440e-01,  -8.247469e-02],                                           
E            [  2.177014e-01,  -5.023782e-02,  -9.351169e-02, ...,...                                    
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by niboshi** [comment]
I found `self.cudnn_deterministic` parameter is not used in this test.
