### ISSUE TITLE
multi-gpu error on examples: cannot overload functions...

### ISSUE THREAD

**Issue by aaronmarkham** [chainer/chainer#4369]
* Conditions
  - Chainer version: latest pip install - chainer-3.3.0.tar.gz
  - CuPy version: latest pip install - cupy-2.3.0.tar.gz
  - OS/Platform: Ubuntu 16.04 (AWS Deep Learning AMI)
  - CUDA/cuDNN version: 9/7
* Code to reproduce
I ran the cifar and mnist examples (after doing `git checkout v3.2.0`), but both result in the same error if I use the gpu option. I also tested if CUDA and cuDNN were available to chainer and both tests were `true`.
* Error messages, stack traces, or logs

```
Exception in main training loop: /usr/local/cuda/include/cuda_fp16.h(133): error: cannot overload functions distinguished by return type alone

/usr/local/cuda/include/cuda_fp16.hpp(648): error: cannot overload functions distinguished by return type alone

/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/cupy/core/include/cupy/carray.cuh(394): warning: statement is unreachable
          detected during instantiation of "void CIndexer<_ndim>::set(ptrdiff_t) [with _ndim=1]" 
/tmp/tmpd1mncg9z/kern.cu(11): here

2 errors detected in the compilation of "/tmp/tmpd1mncg9z/kern.cu".

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/chainer/training/trainer.py", line 299, in run
    update()
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/chainer/training/updater.py", line 234, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/chainer/optimizer.py", line 536, in update
    loss = lossfun(*args, **kwds)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/chainer/links/model/classifier.py", line 114, in __call__
    self.y = self.predictor(*args, **kwargs)
  File "train_mnist.py", line 26, in __call__
    h1 = F.relu(self.l1(x))
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/chainer/links/connection/linear.py", line 128, in __call__
    self._initialize_params(in_size)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/chainer/links/connection/linear.py", line 114, in _initialize_params
    self.W.initialize((self.out_size, in_size))
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/chainer/variable.py", line 1259, in initialize
    data = initializers.generate_array(self.initializer, shape, xp)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/chainer/initializers/__init__.py", line 46, in generate_array
    initializer(array)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/chainer/initializers/normal.py", line 68, in __call__
    Normal(s)(array)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/chainer/initializers/normal.py", line 36, in __call__
    array[...] = xp.random.normal(**args)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/cupy/random/distributions.py", line 94, in normal
    cupy.multiply(x, scale, out=x)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/cupy/core/fusion.py", line 701, in __call__
    return self._cupy_op(*args, **kwargs)
  File "cupy/core/elementwise.pxi", line 823, in cupy.core.core.ufunc.__call__
  File "cupy/util.pyx", line 39, in cupy.util.memoize.decorator.ret
  File "cupy/core/elementwise.pxi", line 622, in cupy.core.core._get_ufunc_kernel
  File "cupy/core/elementwise.pxi", line 33, in cupy.core.core._get_simple_elementwise_kernel
  File "cupy/core/carray.pxi", line 170, in cupy.core.core.compile_with_cache
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 152, in compile_with_cache
    ptx = compile_using_nvrtc(source, options, arch)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 70, in compile_using_nvrtc
    ptx = prog.compile(options)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 233, in compile
    raise CompileException(log, self.src, self.name, options)
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 229, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy/cuda/nvrtc.pyx", line 98, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 108, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 53, in cupy.cuda.nvrtc.check_status
cupy.cuda.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_mnist.py", line 126, in <module>
    main()
  File "train_mnist.py", line 122, in main
    trainer.run()
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/chainer/training/trainer.py", line 313, in run
    six.reraise(*sys.exc_info())
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/chainer/training/trainer.py", line 299, in run
    update()
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/chainer/training/updater.py", line 234, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/chainer/optimizer.py", line 536, in update
    loss = lossfun(*args, **kwds)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/chainer/links/model/classifier.py", line 114, in __call__
    self.y = self.predictor(*args, **kwargs)
  File "train_mnist.py", line 26, in __call__
    h1 = F.relu(self.l1(x))
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/chainer/links/connection/linear.py", line 128, in __call__
    self._initialize_params(in_size)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/chainer/links/connection/linear.py", line 114, in _initialize_params
    self.W.initialize((self.out_size, in_size))
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/chainer/variable.py", line 1259, in initialize
    data = initializers.generate_array(self.initializer, shape, xp)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/chainer/initializers/__init__.py", line 46, in generate_array
    initializer(array)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/chainer/initializers/normal.py", line 68, in __call__
    Normal(s)(array)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/chainer/initializers/normal.py", line 36, in __call__
    array[...] = xp.random.normal(**args)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/cupy/random/distributions.py", line 94, in normal
    cupy.multiply(x, scale, out=x)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/cupy/core/fusion.py", line 701, in __call__
    return self._cupy_op(*args, **kwargs)
  File "cupy/core/elementwise.pxi", line 823, in cupy.core.core.ufunc.__call__
  File "cupy/util.pyx", line 39, in cupy.util.memoize.decorator.ret
  File "cupy/core/elementwise.pxi", line 622, in cupy.core.core._get_ufunc_kernel
  File "cupy/core/elementwise.pxi", line 33, in cupy.core.core._get_simple_elementwise_kernel
  File "cupy/core/carray.pxi", line 170, in cupy.core.core.compile_with_cache
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 152, in compile_with_cache
    ptx = compile_using_nvrtc(source, options, arch)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 70, in compile_using_nvrtc
    ptx = prog.compile(options)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 233, in compile
    raise CompileException(log, self.src, self.name, options)
cupy.cuda.compiler.CompileException: /usr/local/cuda/include/cuda_fp16.h(133): error: cannot overload functions distinguished by return type alone

/usr/local/cuda/include/cuda_fp16.hpp(648): error: cannot overload functions distinguished by return type alone

/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/cupy/core/include/cupy/carray.cuh(394): warning: statement is unreachable
          detected during instantiation of "void CIndexer<_ndim>::set(ptrdiff_t) [with _ndim=1]" 
/tmp/tmpd1mncg9z/kern.cu(11): here

2 errors detected in the compilation of "/tmp/tmpd1mncg9z/kern.cu".
```

**Comment by kmaehashi** [comment]
Sorry for not responding so long.
AWS Deep Learning AMI now supports Chainer by default. Could you try that?
https://aws.amazon.com/about-aws/whats-new/2018/02/aws-deep-learning-amis-introduce-chainer-pytorch-mxnet/

**Comment by aaronmarkham** [comment]
I wrote the Chainer tutorial for the DLAMI. 😸 
https://docs.aws.amazon.com/dlami/latest/devguide/tutorial-chainer.html
I got around this issue by using the v3.3.0 tag instead, after seeing some others found it worked that way. However, after trying it today again, it doesn't work.

```
Traceback (most recent call last):
  File "train_mnist_data_parallel.py", line 78, in <module>
    main()
  File "train_mnist_data_parallel.py", line 53, in main
    updater = training.updaters.ParallelUpdater(
AttributeError: module 'chainer.training.updaters' has no attribute 'ParallelUpdater'
```

So I tried the v3.5.0 tag and that does work, so I'll update the tutorial to have users do that.

I guess you can close this if you don't expect the tutorial to work in those older tags.

Please let me know if you have any suggestions for the tutorial. I plan to push the update tomorrow.

**Comment by kmaehashi** [comment]
> I wrote the Chainer tutorial for the DLAMI. 😸

Oh, I'm sorry for that 😅
Thank you so much for your effort on supporting Chainer on DLAMI!

This kind of `CompileException` usually happens when multiple versions of CUDA are installed on the host and CuPy failed to find the correct version. Please see the comment here: https://github.com/cupy/cupy/issues/1085#issuecomment-378817042.

> I got around this issue by using the v3.3.0 tag instead, after seeing some others found it worked that way. However, after trying it today again, it doesn't work.
> So I tried the v3.5.0 tag and that does work, so I'll update the tutorial to have users do that.

`master` branch in Chainer/CuPy repository is for a development version. I guess you are using examples in `master` branch, which is for Chainer v4.x+, against Chainer v3.x.
To align with other modules' naming convention, we [renamed `chainer.training.ParallelUpdater` to `chainer.training.updaters.ParallelUpdater` in Chainer v4](https://docs.chainer.org/en/latest/upgrade.html#namespace-changes-for-updaters). So, example code using the new name will not work with Chainer v3.

Chainer v4.0.0 will be released on Apr 17th.
