### ISSUE TITLE
Transfer Learning Example

### ISSUE THREAD

**Issue by ilkarman** [chainer/chainer#4429]
I haven't been able to find examples on how to do transfer-learning (e.g. ResNet50 on your own data-set). My attempt is not working but it's hard to isolate the problem.

I want to chop the last FC layer from ResNet50 and add new one with 14 neurons and train with sigmoid_cross_entropy on my multi-label data:

```
class chexnet(chainer.Chain):
    def __init__(self, base_model, out_features=CLASSES):
        super(chexnet, self).__init__()
        with self.init_scope():
            self.base_model = base_model
            in_features = 2048  # How to get this programmatically?
            self.classifier = L.Linear(in_features, out_features)
    
    def __call__(self, x):
        h = self.base_model(x, layers=['pool5']) # How to get this programatically?
        #return F.sigmoid(self.classifier(h))
        return self.classifier(h)  # sigmoid applied in BCE function

def get_symbol():
    base_model = chainer.links.ResNet50Layers(pretrained_model="auto")
    # Change last-layer
    model = chexnet(base_model)
    # CUDA
    chainer.cuda.get_device(0).use()  # Make a specified GPU current
    model.to_gpu()  
    return model

def init_symbol(sym, lr=LR):
    opt = optimizers.Adam(alpha=lr, beta1=0.9, beta2=0.999)
    opt.setup(sym)
    return opt

# Load symbol
chexnet_sym = get_symbol(model_name='resnet50')
# Load optimiser
optimizer = init_symbol(chexnet_sym)

updater = StandardUpdater(train_iter, optimizer, loss_func=F.sigmoid_cross_entropy, device=0)
trainer = training.Trainer(updater, stop_trigger=(EPOCHS, 'epoch'))
trainer.extend(extensions.ProgressBar(update_interval=10))
trainer.run()

Exception in main training loop: 
Invalid operation is performed in: SigmoidCrossEntropy (Forward)

Expect: in_types[0].shape == in_types[1].shape
Actual: (64, 3, 224, 224) != (64, 14)
Traceback (most recent call last):
  File "/anaconda/envs/py35/lib/python3.5/site-packages/chainer/training/trainer.py", line 299, in run
    update()
  File "/anaconda/envs/py35/lib/python3.5/site-packages/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/anaconda/envs/py35/lib/python3.5/site-packages/chainer/training/updater.py", line 234, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/chainer/optimizer.py", line 541, in update
    loss = lossfun(*args, **kwds)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/chainer/functions/loss/sigmoid_cross_entropy.py", line 168, in sigmoid_cross_entropy
    return SigmoidCrossEntropy(normalize, reduce).apply((x, t))[0]
  File "/anaconda/envs/py35/lib/python3.5/site-packages/chainer/function_node.py", line 230, in apply
    self._check_data_type_forward(in_data)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/chainer/function_node.py", line 298, in _check_data_type_forward
    self.check_type_forward(in_type)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/chainer/functions/loss/sigmoid_cross_entropy.py", line 33, in check_type_forward
    x_type.shape == t_type.shape
  File "/anaconda/envs/py35/lib/python3.5/site-packages/chainer/utils/type_check.py", line 524, in expect
    expr.expect()
  File "/anaconda/envs/py35/lib/python3.5/site-packages/chainer/utils/type_check.py", line 482, in expect
    '{0} {1} {2}'.format(left, self.inv, right))
Will finalize trainer extensions and updater before reraising the exception.
```

If it's helpful my notebook is located [here](https://github.com/ilkarman/DeepLearningFrameworks/blob/multi_gpu/notebooks/Chainer_MultiGPU_Large.ipynb) and [this](https://github.com/ilkarman/DeepLearningFrameworks/blob/multi_gpu/notebooks/PyTorch_MultiGPU.ipynb) the working PyTorch version I want to replicate

**Comment by ilkarman** [comment]
This seems to work now like so:

```
class chexnet(ResNet50Layers):
    
    def __init__(self, pretrained_model="auto", out_features=CLASSES):
        super(chexnet, self).__init__(pretrained_model)
        with self.init_scope():
            self.classifier = L.Linear(2048, 14)
    
    def __call__(self, x, t, **kwargs):
        h = super(chexnet, self).__call__(x, layers=['pool5'], **kwargs)['pool5']
        h = self.classifier(h)
        return F.sigmoid_cross_entropy(h, t)


train_iter = chainer.iterators.SerialIterator(train_dataset, BATCHSIZE)
valid_iter = chainer.iterators.SerialIterator(valid_dataset, BATCHSIZE)
test_iter = chainer.iterators.SerialIterator(test_dataset, BATCHSIZE)

updater = StandardUpdater(train_iter, optimizer, device=0)
trainer = training.Trainer(updater, stop_trigger=(EPOCHS, 'epoch'))
trainer.extend(extensions.Evaluator(valid_iter, chexnet_sym, device=0),trigger=(10, 'iteration'))
trainer.extend(extensions.ProgressBar(update_interval=10))
```
