### ISSUE TITLE
Awkward behavior of serializer/deserializer

### ISSUE THREAD

**Issue by fiarabbit** [chainer/chainer#4542]
I found _**chainer.serializers.save_npz()**_ does not emit any warning nor error, while the output npz file cannot be loaded by _**chainer.serializers.load_npz()**_. It happens when the target object owns no persistent object for serialization. For example, an instance of _**chainer.Chain**_ can be serialized but it cannot be deserialized.

It is acceptable that the serializer does not serialize nothing when there is no objects to be serialized, but the error/warning message should be shown on the serialization, not on the deserialization.

Also, I did not find any documentation about this phenomenon. I think it is too unkind for newbies to understand how to serialize their model correctly.

Some reproduction codes follows.

* Conditions
  - Chainer version
    chainer==3.0.0b1
* Code to reproduce
```test1.py
import chainer
from chainer import Variable, Parameter
from chainer import functions as F
from chainer import links as L

import numpy as np

from os import remove
from os.path import exists


class NG_None(chainer.Chain):
    def __init__(self):
        super().__init__()


class NG_Variable(chainer.Chain):
    def __init__(self):
        super().__init__()
        with self.init_scope():
            self.v = Variable(np.array([1, 2, 3]))


class NG_Function(chainer.Chain):
    def __init__(self):
        super().__init__()
        with self.init_scope():
            self.f = F.ReLU()


class OK_Parameter(chainer.Chain):
    def __init__(self):
        super().__init__()
        with self.init_scope():
            self.p = Parameter(np.array([1, 2, 3]))


class OK_Link(chainer.Chain):
    def __init__(self):
        super().__init__()
        with self.init_scope():
            self.l = L.BatchNormalization(1)


def save_and_load(Class):
    try:
        instance_1 = Class()
        chainer.serializers.save_npz("tmp.npz", instance_1)
        chainer.serializers.load_npz("tmp.npz", instance_1)
        print("Succeeded")
    except Exception as e:
        print("Failed")
        raise e
    finally:
        if exists("tmp.npz"):
            remove("tmp.npz")
```
```test1.out.py
>>> save_and_load(chainer.Chain)
Failed
>>> save_and_load(NG_None)
Failed
>>> save_and_load(NG_Variable)
Failed
>>> save_and_load(NG_Function)
Failed
>>> save_and_load(OK_Link)
Succeeded
>>> save_and_load(OK_Parameter)
Succeeded
```
```test1.traceback.py
Traceback (most recent call last):
  File "/home/hashimoto/.python-venv/lib/python3.5/site-packages/numpy/lib/npyio.py", line 426, in load
    return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/hashimoto/PycharmProjects/fMRI_AE/misc/test1.py", line 53, in save_and_load
    raise e
  File "/mnt/c/Users/hashimoto/PycharmProjects/fMRI_AE/misc/test1.py", line 49, in save_and_load
    chainer.serializers.load_npz("tmp.npz", instance_1)
  File "/home/hashimoto/.python-venv/lib/python3.5/site-packages/chainer/serializers/npz.py", line 138, in load_npz
    with numpy.load(filename) as f:
  File "/home/hashimoto/.python-venv/lib/python3.5/site-packages/numpy/lib/npyio.py", line 429, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file 'tmp.npz' as a pickle
```
Also, the behavior below is confusing.
```test2.py
import chainer
from chainer import Variable, Parameter
from chainer import functions as F
from chainer import links as L

import numpy as np

from os import remove
from os.path import exists


class NG_Mixed(chainer.Chain):
    def __init__(self, v: Variable, f: chainer.Function, p: Parameter, l: chainer.Link):
        super().__init__()
        with self.init_scope():
            self.v = v
            self.f = f
            self.p = p
            self.l = l


def test_mixed():
    try:
        instance_1 = NG_Mixed(Variable(np.array([0])), F.ReLU(), Parameter(np.array([0])), L.BatchNormalization(1))
        chainer.serializers.save_npz("tmp.npz", instance_1)
        instance_2 = NG_Mixed(Variable(np.array([1])), F.ReLU(), Parameter(np.array([1])), L.BatchNormalization(1))
        chainer.serializers.load_npz("tmp.npz", instance_2)
        assert (instance_1.p.data == instance_2.p.data).all()
        assert (instance_1.v.data == instance_2.v.data).all()
        print("Succeeded")
    except Exception as e:
        print("Failed")
        raise e
    finally:
        if exists("tmp.npz"):
            remove("tmp.npz")
```
```test2.out.py
>>> test_mixed()
Failed
```
```test2.traceback.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/hashimoto/PycharmProjects/fMRI_AE/misc/test2.py", line 33, in test_mixed
    raise e
  File "/mnt/c/Users/hashimoto/PycharmProjects/fMRI_AE/misc/test2.py", line 29, in test_mixed
    assert (instance_1.v.data == instance_2.v.data).all()
AssertionError
```

**Comment by kmaehashi** [comment]
Thank you for the report.
I think this is a NumPy bug; `numpy.load` does not recognize empty ZIP file (with magic `PK\x05\x06`).

**Comment by fiarabbit** [comment]
@kmaehashi 
Thank you for your reply. I totally understood this peculiar behavior.
