### ISSUE TITLE
upy array

### ISSUE THREAD

**Issue by nogu-atsu** [chainer/chainer#4648]
```
>>> import cupy as xp
>>> a = xp.arange(5)
>>> a[[0,1,2,3,4,5,6]]
array([0, 1, 2, 3, 4, 0, 1])
```
```
>>> import numpy as np
>>> b = np.arnge(5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'numpy' has no attribute 'arnge'
>>> b = np.arange(5)
>>> b[[0,1,2,3,4,5,6]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: index 5 is out of bounds for axis 1 with size 5
>>>
```

**Comment by kmaehashi** [comment]
Thank you for the feedback.
This is currently by design. See https://docs-cupy.chainer.org/en/latest/reference/difference.html#out-of-bounds-indices for details.

**Comment by nogu-atsu** [comment]
Thank you for your reply. I understand the differences between numpy and cupy.
