### ISSUE TITLE
chainer.training.ParallelUpdater does not properly work w/ cupy.core.elementwise

### ISSUE THREAD

**Issue by fiarabbit** [chainer/chainer#4669]
**"Data-parallel Computation on Multiple GPUs with `Trainer` (and `ParallelUpdater`)"**, which is one of topic in [the official document](https://docs.chainer.org/en/stable/guides/gpu.html), does not work properly when the model contains any function-call of `cupy.core.elementwise`.

In _cupy/cupy/core/elementwise.pxi line 127_, it checks if the device between the current device and the device of the array. However, the `ParallelUpdater` does not manage the current device, so the backward process of `cupy.elementwise()` fails. 

The reproduction code below. Note F.mean_absolute_error() contains cupy.elementwise().

```example.py
import chainer
import chainer.links as L
import chainer.functions as F

from chainer.optimizers import Adam
from chainer.iterators import SerialIterator
from chainer.training import Trainer, ParallelUpdater

import numpy as np


class Model(chainer.Chain):
    def __init__(self):
        super().__init__()
        with self.init_scope():
            self.l1 = L.Linear(5, 5)

    def __call__(self, x):
        s = list(x.shape)
        s.pop()
        loss = F.mean_absolute_error(self.l1(x), x.reshape(s))
        return loss


class Dataset(chainer.dataset.DatasetMixin):
    def __init__(self):
        super().__init__()

    def __len__(self):
        return 1024

    def get_example(self, i):
        return np.arange(5, dtype=np.float32).reshape((5, 1))

model = Model()
optimizer = Adam()
optimizer.setup(model)

train_dataset = Dataset()
train_iterator = SerialIterator(train_dataset, 2)

updater = ParallelUpdater(train_iterator, optimizer, devices={"main": 0, "second": 1})
trainer = Trainer(updater)
trainer.run()
```
```traceback.py
Exception in main training loop: Array device must be same as the current device: array device = 1 while current = 0
Traceback (most recent call last):
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/training/trainer.py", line 306, in run
    update()
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/training/updaters/standard_updater.py", line 149, in update
    self.update_core()
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/training/updaters/parallel_updater.py", line 136, in update_core
    loss.backward(loss_scale=self.loss_scale)
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/variable.py", line 963, in backward
    self._backward_main(retain_grad, loss_scale)
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/variable.py", line 1092, in _backward_main
    target_input_indexes, out_grad, in_grad)
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/function_node.py", line 548, in backward_accumulate
    gxs = self.backward(target_input_indexes, grad_outputs)
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/functions/loss/mean_absolute_error.py", line 37, in backward
    gx0 = coeff * cuda.get_array_module(gy.data).sign(self.diff)
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/cupy/core/fusion.py", line 713, in __call__
    return self._cupy_op(*args, **kwargs)
  File "cupy/core/elementwise.pxi", line 786, in cupy.core.core.ufunc.__call__
  File "cupy/core/elementwise.pxi", line 135, in cupy.core.core._preprocess_args
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "b", line 44, in <module>
    trainer.run()
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/training/trainer.py", line 320, in run
    six.reraise(*sys.exc_info())
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/training/trainer.py", line 306, in run
    update()
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/training/updaters/standard_updater.py", line 149, in update
    self.update_core()
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/training/updaters/parallel_updater.py", line 136, in update_core
    loss.backward(loss_scale=self.loss_scale)
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/variable.py", line 963, in backward
    self._backward_main(retain_grad, loss_scale)
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/variable.py", line 1092, in _backward_main
    target_input_indexes, out_grad, in_grad)
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/function_node.py", line 548, in backward_accumulate
    gxs = self.backward(target_input_indexes, grad_outputs)
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/functions/loss/mean_absolute_error.py", line 37, in backward
    gx0 = coeff * cuda.get_array_module(gy.data).sign(self.diff)
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/cupy/core/fusion.py", line 713, in __call__
    return self._cupy_op(*args, **kwargs)
  File "cupy/core/elementwise.pxi", line 786, in cupy.core.core.ufunc.__call__
  File "cupy/core/elementwise.pxi", line 135, in cupy.core.core._preprocess_args
ValueError: Array device must be same as the current device: array device = 1 while current = 0
```

**Comment by andremoeller** [comment]
I ran into this as well attempting to adapt the RNN example in text_classification to use multiple gpus using `ParallelUpdater`: https://github.com/chainer/chainer/tree/master/examples/text_classification

**Comment by fiarabbit** [comment]
@andremoeller 
I could reproduce the situation.
When https://github.com/chainer/chainer/tree/master/examples/text_classification is run with `ParallelUpdater`, the following trace appears.
(Maybe due to _chainer/functions/array/permutate.py_)

```trace.py
Exception in main training loop: Array device must be same as the current device: array device = 0 while current = 1
Traceback (most recent call last):
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/training/trainer.py", line 306, in run
    update()
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/training/updaters/standard_updater.py", line 149, in update
    self.update_core()
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/training/updaters/parallel_updater.py", line 126, in update_core
    loss = loss_func(**in_arrays)
  File "/home/ubuntu/chainer/examples/text_classification/nets.py", line 90, in __call__
    concat_outputs = self.predict(xs)
  File "/home/ubuntu/chainer/examples/text_classification/nets.py", line 100, in predict
    concat_encodings = F.dropout(self.encoder(xs), ratio=self.dropout)
  File "/home/ubuntu/chainer/examples/text_classification/nets.py", line 137, in __call__
    last_h, last_c, ys = self.encoder(None, None, exs)
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/links/connection/n_step_lstm.py", line 76, in __call__
    (hy, cy), ys = self._call([hx, cx], xs, **kwargs)
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/links/connection/n_step_rnn.py", line 206, in _call
    for h in result[:-1]]
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/links/connection/n_step_rnn.py", line 206, in <listcomp>
    for h in result[:-1]]
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/functions/array/permutate.py", line 134, in permutate
    y, = Permutate(axis, inv).apply((x, indices))
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/function_node.py", line 258, in apply
    outputs = self.forward(in_data)
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/functions/array/permutate.py", line 74, in forward
    return self._permutate(x, inds, self.inv),
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/functions/array/permutate.py", line 63, in _permutate
    indices = _inverse_indices(indices)
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/functions/array/permutate.py", line 35, in _inverse_indices
    )(indices, r)
  File "cupy/core/elementwise.pxi", line 551, in cupy.core.core.ElementwiseKernel.__call__
  File "cupy/core/elementwise.pxi", line 135, in cupy.core.core._preprocess_args
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "mgpu.py", line 137, in <module>
    main()
  File "mgpu.py", line 133, in main
    trainer.run()
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/training/trainer.py", line 320, in run
    six.reraise(*sys.exc_info())
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/training/trainer.py", line 306, in run
    update()
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/training/updaters/standard_updater.py", line 149, in update
    self.update_core()
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/training/updaters/parallel_updater.py", line 126, in update_core
    loss = loss_func(**in_arrays)
  File "/home/ubuntu/chainer/examples/text_classification/nets.py", line 90, in __call__
    concat_outputs = self.predict(xs)
  File "/home/ubuntu/chainer/examples/text_classification/nets.py", line 100, in predict
    concat_encodings = F.dropout(self.encoder(xs), ratio=self.dropout)
  File "/home/ubuntu/chainer/examples/text_classification/nets.py", line 137, in __call__
    last_h, last_c, ys = self.encoder(None, None, exs)
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/links/connection/n_step_lstm.py", line 76, in __call__
    (hy, cy), ys = self._call([hx, cx], xs, **kwargs)
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/links/connection/n_step_rnn.py", line 206, in _call
    for h in result[:-1]]
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/links/connection/n_step_rnn.py", line 206, in <listcomp>
    for h in result[:-1]]
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/functions/array/permutate.py", line 134, in permutate
    y, = Permutate(axis, inv).apply((x, indices))
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/function_node.py", line 258, in apply
    outputs = self.forward(in_data)
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/functions/array/permutate.py", line 74, in forward
    return self._permutate(x, inds, self.inv),
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/functions/array/permutate.py", line 63, in _permutate
    indices = _inverse_indices(indices)
  File "/home/ubuntu/.python-venv/lib/python3.5/site-packages/chainer/functions/array/permutate.py", line 35, in _inverse_indices
    )(indices, r)
  File "cupy/core/elementwise.pxi", line 551, in cupy.core.core.ElementwiseKernel.__call__
  File "cupy/core/elementwise.pxi", line 135, in cupy.core.core._preprocess_args
ValueError: Array device must be same as the current device: array device = 0 while current = 1
```

**Comment by fiarabbit** [comment]
@Hakuyume 
Thank you very much for your PR.

**Comment by kmaehashi** [comment]
In this case, `self.diff` used here is the problem. https://github.com/chainer/chainer/blob/v5.0.0a1/chainer/functions/loss/mean_absolute_error.py#L27-L38

When the forward step has run with current device = GPU-1 set, `self.diff` resides on GPU-1.
However, during the backward call, the current device becomes GPU-0. This is because we're switching the device using retained inputs of FunctionNode, although F.mean_absolute_error does not retain any inputs. The PR by Hakuyume-san fixes this issue by switching device using grads of outputs of FunctionNode, not retained inputs.
