### ISSUE TITLE
`import chainer` fails when matplotlib version is old

### ISSUE THREAD

**Issue by iwiwi** [chainer/chainer#4670]
```
>>> import chainer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../chainer/__init__.py", line 28, in <module>
    from chainer import training  # NOQA
  File ".../chainer/training/__init__.py", line 2, in <module>
    from chainer.training import extensions  # NOQA
  File ".../chainer/training/extensions/__init__.py", line 30, in <module>
    from chainer.training.extensions.variable_statistics_plot import VariableStatisticsPlot  # NOQA
  File ".../chainer/training/extensions/variable_statistics_plot.py", line 16, in <module>
    _plot_color = matplotlib.colors.to_rgba('#1f77b4')  # C0 color
AttributeError: module 'matplotlib.colors' has no attribute 'to_rgba'
```

It is resolved after upgrading matplotlib.

## Conditions
* chainer: 4.0.0
* matplotlib: 1.5.3

**Comment by iwiwi** [comment]
Thanks for working on it!
