### ISSUE TITLE
nvrtc: error: failed to open libnvrtc-builtins.so

### ISSUE THREAD

**Issue by erdenebileg11** [chainer/chainer#4813]
I am trying to run simple chainer code on single GPU (NVIDIA GTX 1070 Ti).

OS: ubuntu 17.10
NVIDIA driver: 396.24
CUDA: cuda-9.2
python: 2.7.14
chainer: 4.1.0

I see the following error:

Exception in main training loop: nvrtc: error: failed to open libnvrtc-builtins.so.
  Make sure that libnvrtc-builtins.so is installed correctly.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/trainer.py", line 306, in run
    update()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/updaters/standard_updater.py", line 149, in update
    self.update_core()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/updaters/standard_updater.py", line 160, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/usr/local/lib/python2.7/dist-packages/chainer/optimizer.py", line 640, in update
    loss = lossfun(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/chainer/links/model/classifier.py", line 114, in __call__
    self.y = self.predictor(*args, **kwargs)
  File "item.py", line 24, in __call__
    h1 = F.relu(self.l1(x))
  File "/usr/local/lib/python2.7/dist-packages/chainer/links/connection/linear.py", line 128, in __call__
    self._initialize_params(in_size)
  File "/usr/local/lib/python2.7/dist-packages/chainer/links/connection/linear.py", line 114, in _initialize_params
    self.W.initialize((self.out_size, in_size))
  File "/usr/local/lib/python2.7/dist-packages/chainer/variable.py", line 1411, in initialize
    data = initializers.generate_array(self.initializer, shape, xp)
  File "/usr/local/lib/python2.7/dist-packages/chainer/initializers/__init__.py", line 46, in generate_array
    initializer(array)
  File "/usr/local/lib/python2.7/dist-packages/chainer/initializers/normal.py", line 68, in __call__
    Normal(s)(array)
  File "/usr/local/lib/python2.7/dist-packages/chainer/initializers/normal.py", line 36, in __call__
    array[...] = xp.random.normal(**args)
  File "/usr/local/lib/python2.7/dist-packages/cupy/random/distributions.py", line 94, in normal
    cupy.multiply(x, scale, out=x)
  File "/usr/local/lib/python2.7/dist-packages/cupy/core/fusion.py", line 717, in __call__
    return self._cupy_op(*args, **kwargs)
  File "cupy/core/elementwise.pxi", line 839, in cupy.core.core.ufunc.__call__
  File "cupy/util.pyx", line 39, in cupy.util.memoize.decorator.ret
  File "cupy/core/elementwise.pxi", line 638, in cupy.core.core._get_ufunc_kernel
  File "cupy/core/elementwise.pxi", line 33, in cupy.core.core._get_simple_elementwise_kernel
  File "cupy/core/carray.pxi", line 146, in cupy.core.core.compile_with_cache
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 135, in compile_with_cache
    base = _preprocess('', options, arch)
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 98, in _preprocess
    result = prog.compile(options)
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 245, in compile
    raise CompileException(log, self.src, self.name, options)
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "item.py", line 125, in <module>
    main()
  File "item.py", line 121, in main
    trainer.run()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/trainer.py", line 320, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/trainer.py", line 306, in run
    update()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/updaters/standard_updater.py", line 149, in update
    self.update_core()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/updaters/standard_updater.py", line 160, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/usr/local/lib/python2.7/dist-packages/chainer/optimizer.py", line 640, in update
    loss = lossfun(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/chainer/links/model/classifier.py", line 114, in __call__
    self.y = self.predictor(*args, **kwargs)
  File "item.py", line 24, in __call__
    h1 = F.relu(self.l1(x))
  File "/usr/local/lib/python2.7/dist-packages/chainer/links/connection/linear.py", line 128, in __call__
    self._initialize_params(in_size)
  File "/usr/local/lib/python2.7/dist-packages/chainer/links/connection/linear.py", line 114, in _initialize_params
    self.W.initialize((self.out_size, in_size))
  File "/usr/local/lib/python2.7/dist-packages/chainer/variable.py", line 1411, in initialize
    data = initializers.generate_array(self.initializer, shape, xp)
  File "/usr/local/lib/python2.7/dist-packages/chainer/initializers/__init__.py", line 46, in generate_array
    initializer(array)
  File "/usr/local/lib/python2.7/dist-packages/chainer/initializers/normal.py", line 68, in __call__
    Normal(s)(array)
  File "/usr/local/lib/python2.7/dist-packages/chainer/initializers/normal.py", line 36, in __call__
    array[...] = xp.random.normal(**args)
  File "/usr/local/lib/python2.7/dist-packages/cupy/random/distributions.py", line 94, in normal
    cupy.multiply(x, scale, out=x)
  File "/usr/local/lib/python2.7/dist-packages/cupy/core/fusion.py", line 717, in __call__
    return self._cupy_op(*args, **kwargs)
  File "cupy/core/elementwise.pxi", line 839, in cupy.core.core.ufunc.__call__
  File "cupy/util.pyx", line 39, in cupy.util.memoize.decorator.ret
  File "cupy/core/elementwise.pxi", line 638, in cupy.core.core._get_ufunc_kernel
  File "cupy/core/elementwise.pxi", line 33, in cupy.core.core._get_simple_elementwise_kernel
  File "cupy/core/carray.pxi", line 146, in cupy.core.core.compile_with_cache
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 135, in compile_with_cache
    base = _preprocess('', options, arch)
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 98, in _preprocess
    result = prog.compile(options)
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 245, in compile
    raise CompileException(log, self.src, self.name, options)
cupy.cuda.compiler.CompileException: nvrtc: error: failed to open libnvrtc-builtins.so.
  Make sure that libnvrtc-builtins.so is installed correctly.

**Comment by kmaehashi** [comment]
Try setting LD_LIBRARY_PATH appropriately, e.g.
```
export LD_LIBRARY_PATH=/usr/local/cuda-9.2/lib64:$LD_LIBRARY_PATH
```

**Comment by erdenebileg11** [comment]
`export `LD_LIBRARY_PATH=/usr/local/cuda-9.2/lib64:$LD_LIBRARY_PATH`

I tried this line, but it is same error

**Comment by erdenebileg11** [comment]
Here is the output of the command:

![screenshot from 2018-05-28 14-46-35](https://user-images.githubusercontent.com/1563052/40599000-f8757964-6285-11e8-8d7d-b7c4b26721ee.png)

**Comment by fiarabbit** [comment]
I found what's wrong with your code.
Why do you use "sudo" to run?

sudo removes all the environment variables, so your "export LD_LIBRARY_PATH" is ignored in https://github.com/chainer/chainer/issues/4813#issuecomment-392414882

Therefore, only you have to do is 
```train.py
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
python item.py --gpu 0
```

**Comment by erdenebileg11** [comment]
Thank you so much for your effort. Because of the below permission error I used the "sudo" command.

![screenshot from 2018-05-28 14-53-07](https://user-images.githubusercontent.com/1563052/40599236-2fd3e6ec-6287-11e8-9084-f1590d9e2aa6.png)

**Comment by fiarabbit** [comment]
The error message says that you do not have a right permission onto "~/Documents/research/result" to write.
It's not a problem related to chainer, and https://wiki.archlinux.org/index.php/File_permissions_and_attributes will be helpful.

In very short,
```
sudo chown -R erdenebileg .
sudo chmod -R 770 .
```
will help you, but make sure the meaning of these command before you execute.

**Comment by erdenebileg11** [comment]
Finally I solved the issue. Thank you very much @fiarabbit @kmaehashi
