### ISSUE TITLE
`F.logsumexp` fails on 0-dim input

### ISSUE THREAD

**Issue by toslunar** [chainer/chainer#5015]
Use `chainer.utils.force_array`.
```
>>> chainer.functions.logsumexp(chainer.Variable(np.array(3, 'f')), axis=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tos/GitHub/chainer/chainer/functions/math/logsumexp.py", line 91, in logsumexp
    return LogSumExp(axis).apply((x,))[0]
  File "/Users/tos/GitHub/chainer/chainer/function_node.py", line 257, in apply
    outputs = self.forward(in_data)
  File "/Users/tos/GitHub/chainer/chainer/functions/math/logsumexp.py", line 47, in forward
    xp.exp(y, out=y)
TypeError: return arrays must be of ArrayType
```

**Comment by toslunar** [comment]
Fixed by #5190.
