### ISSUE TITLE
Chainer backward basic

### ISSUE THREAD

**Issue by khanh1412** [chainer/chainer#5031]
Hi, I have read basic tutorial on this link:
https://docs.chainer.org/en/v1.22.0/tutorial/basic.html#core-concept

Here is my code:
`import numpy as np`
`import chainer`
`x_np = np.array([1,2,3], dtype = np.float32)`
`x = chainer.Variable(x)`
`y = x**2`
`print(y.data, type(y.data))` // output: [1. 4. 9.] <class 'numpy.ndarray'>
`y.backward()`

stderr:
Traceback (most recent call last):
  File "./test.py", line 10, in <module>
    y.backward(retain_grad = True)
  File "/usr/local/lib/python3.6/site-packages/chainer/variable.py", line 966, in backward
    self._backward_main(retain_grad, loss_scale)
  File "/usr/local/lib/python3.6/site-packages/chainer/variable.py", line 1095, in _backward_main
    target_input_indexes, out_grad, in_grad)
  File "/usr/local/lib/python3.6/site-packages/chainer/function_node.py", line 548, in backward_accumulate
    gxs = self.backward(target_input_indexes, grad_outputs)
  File "/usr/local/lib/python3.6/site-packages/chainer/functions/math/basic_math.py", line 609, in backward
    return PowVarConstGrad(self.value).apply((inputs[0], gy[0]))
  File "/usr/local/lib/python3.6/site-packages/chainer/function_node.py", line 243, in apply
    self._check_data_type_forward(in_data)
  File "/usr/local/lib/python3.6/site-packages/chainer/function_node.py", line 320, in _check_data_type_forward
    self.check_type_forward(in_type)
  File "/usr/local/lib/python3.6/site-packages/chainer/functions/math/basic_math.py", line 624, in check_type_forward
    in_types[0].dtype == in_types[1].dtype,
AttributeError: 'NoneType' object has no attribute 'dtype'

chainer.__version__ "4.2.0"
numpy.__version__ "1.14.3"

Thanks for your help!

**Comment by fiarabbit** [comment]
In very short, Variable.backward() only works when the size of Variable is 1.
I think what you wanted to do was below.
```main.py
import numpy as np
from chainer import Variable
from chainer import functions as F

x = Variable(np.array([1, 2, 3], dtype=np.float32))
y = x ** 2
loss = F.sum(y)
loss.backward()
print("x.grad: {}".format(x.grad))
```
```out.py
x.grad: [2. 4. 6.]
```

**Comment by fiarabbit** [comment]
And you'd better reference [latest documentation ](https://docs.chainer.org/en/stable/) instead of [chainer v1's documentation](https://docs.chainer.org/en/v1.22.0/)

**Comment by khanh1412** [comment]
@fiarabbit Oh, thank you
