### ISSUE TITLE
cupy.cuda.runtime.CUDARuntimeError: cudaErrorMemoryAllocation: out of memory

### ISSUE THREAD

**Issue by akaneko1019** [chainer/chainer#5038]
* Conditions

```
  - Chainer version : 5.0.0b1
  - CuPy version : 5.0.0b1
  - OS/Platform : Ubuntu18.04 in nvidiaDocker
  - CUDA/cuDNN version : 8.0/6 
  - etc : Docker nvidia/cuda:8.0-cudnn6-devel
  - gpu : nvidia GTX1070Ti 8GB
  - MainMemory : 32GB
```
* Code to reproduce
```python
input_data = [chainer.cuda.cupy.asarray(tuple_dataset[:i+start_pos], dtype=chainer.cuda.cupy.float32) for i in range(len(tuple_dataset) - start_pos)]
input_data = [chainer.variable.Variable(v) for v in input_data]
```
* Error messages, stack traces, or logs
```
Traceback (most recent call last):
  File "cupy/cuda/memory.pyx", line 810, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 735, in cupy.cuda.memory.SingleDeviceMemoryPool._alloc
  File "cupy/cuda/memory.pyx", line 423, in cupy.cuda.memory._malloc
  File "cupy/cuda/memory.pyx", line 424, in cupy.cuda.memory._malloc
  File "cupy/cuda/memory.pyx", line 58, in cupy.cuda.memory.Memory.__init__
  File "cupy/cuda/runtime.pyx", line 212, in cupy.cuda.runtime.malloc
  File "cupy/cuda/runtime.pyx", line 135, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorMemoryAllocation: out of memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cupy/cuda/memory.pyx", line 816, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 735, in cupy.cuda.memory.SingleDeviceMemoryPool._alloc
  File "cupy/cuda/memory.pyx", line 423, in cupy.cuda.memory._malloc
  File "cupy/cuda/memory.pyx", line 424, in cupy.cuda.memory._malloc
  File "cupy/cuda/memory.pyx", line 58, in cupy.cuda.memory.Memory.__init__
  File "cupy/cuda/runtime.pyx", line 212, in cupy.cuda.runtime.malloc
  File "cupy/cuda/runtime.pyx", line 135, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorMemoryAllocation: out of memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cupy/cuda/memory.pyx", line 822, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 735, in cupy.cuda.memory.SingleDeviceMemoryPool._alloc
  File "cupy/cuda/memory.pyx", line 423, in cupy.cuda.memory._malloc
  File "cupy/cuda/memory.pyx", line 424, in cupy.cuda.memory._malloc
  File "cupy/cuda/memory.pyx", line 58, in cupy.cuda.memory.Memory.__init__
  File "cupy/cuda/runtime.pyx", line 212, in cupy.cuda.runtime.malloc
  File "cupy/cuda/runtime.pyx", line 135, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorMemoryAllocation: out of memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "taxi-nsteplstm.py", line 508, in <module>
    pred1 = predict_typeA(test_dataset,pre_skip,gpu)
  File "taxi-nsteplstm.py", line 355, in predict_typeA
    pred = model.predictor(input_data)
  File "taxi-nsteplstm.py", line 91, in predictor
    hy, cy, ys = self.lstm(self.hx, self.cx, x)
  File "/usr/local/lib/python3.5/dist-packages/chainer/links/connection/n_step_lstm.py", line 76, in __call__
    (hy, cy), ys = self._call([hx, cx], xs, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/chainer/links/connection/n_step_rnn.py", line 203, in _call
    result = self.rnn(*args)
  File "/usr/local/lib/python3.5/dist-packages/chainer/links/connection/n_step_lstm.py", line 120, in rnn
    return rnn.n_step_lstm(*args)
  File "/usr/local/lib/python3.5/dist-packages/chainer/functions/connection/n_step_lstm.py", line 179, in n_step_lstm
    use_bi_direction=False, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/chainer/functions/connection/n_step_lstm.py", line 438, in n_step_lstm_base
    hy, cy, ys = rnn(n_layers, states, lengths)(hx, cx, w, xs)
  File "/usr/local/lib/python3.5/dist-packages/chainer/function.py", line 235, in __call__
    ret = node.apply(inputs)
  File "/usr/local/lib/python3.5/dist-packages/chainer/function_node.py", line 258, in apply
    outputs = self.forward(in_data)
  File "/usr/local/lib/python3.5/dist-packages/chainer/function.py", line 135, in forward
    return self._function.forward(inputs)
  File "/usr/local/lib/python3.5/dist-packages/chainer/functions/connection/n_step_rnn.py", line 365, in forward
    (len(xs), n_units * self.rnn_direction), dtype=xs.dtype)
  File "/usr/local/lib/python3.5/dist-packages/cupy/creation/basic.py", line 20, in empty
    return cupy.ndarray(shape, dtype=dtype, order=order)
  File "cupy/core/core.pyx", line 96, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 468, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 964, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 985, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 765, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 828, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
cupy.cuda.memory.OutOfMemoryError: out of memory to allocate 25908213248 bytes (total 27003945472 bytes)
```

**question**

In the above code, an error of memory shortage occurs at the timing of executing the code of the second line.
Does anyone know why?

The contents of tuple_dataset are tuples of (dataset A, dataset B), and the shape number is (8064, 1) respectively.
Both dataset A and dataset B are "numpy array float 32".
The size of tuple_dataset is 61432 bytes.

Note that this is the data to be passed to predict the learned model in NStepLSTM.

If there are missing codes etc, I will add it.

**Comment by akaneko1019** [comment]
I was misunderstanding. There was memory shortage when delivering to NStepLSTM after that.
Simply pass the size you pass.
I am very sorry.
