### ISSUE TITLE
`ignore_label` of `F.softmax_cross_entropy` has to be in the range [-n, n)

### ISSUE THREAD

**Issue by toslunar** [chainer/chainer#5127]
* Conditions
  - Chainer version: master
* Code to reproduce
```
>>> x = np.random.randn(2, 4)
>>> chainer.functions.softmax_cross_entropy(x, np.array([2, -1]))
variable(1.48807391)
>>> chainer.functions.softmax_cross_entropy(x, np.array([2, -2]), ignore_label=-2)
variable(1.48807391)
>>> chainer.functions.softmax_cross_entropy(x, np.array([2, 4]), ignore_label=4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tos/GitHub/chainer/chainer/functions/loss/softmax_cross_entropy.py", line 381, in softmax_cross_entropy
    normalize, cache_score, class_weight, ignore_label, reduce)(x, t)
  File "/Users/tos/GitHub/chainer/chainer/function.py", line 235, in __call__
    ret = node.apply(inputs)
  File "/Users/tos/GitHub/chainer/chainer/function_node.py", line 257, in apply
    outputs = self.forward(in_data)
  File "/Users/tos/GitHub/chainer/chainer/function.py", line 135, in forward
    return self._function.forward(inputs)
  File "/Users/tos/GitHub/chainer/chainer/function.py", line 344, in forward
    return self.forward_cpu(inputs)
  File "/Users/tos/GitHub/chainer/chainer/functions/loss/softmax_cross_entropy.py", line 94, in forward_cpu
    log_p = log_yd[numpy.maximum(t.ravel(), 0), numpy.arange(t.size)]
IndexError: index 4 is out of bounds for axis 0 with size 4
```

**Comment by lebron-james** [comment]
i also meet this issue, i wanna know how did you solve it?

**Comment by toslunar** [comment]
`forward_gpu` and `backward_gpu` seem OK.  Use GPUs 😄
