### ISSUE TITLE
incompatibilty of dilate parameter and convolutionBackwardData

### ISSUE THREAD

**Issue by fiarabbit** [chainer/chainer#5128]
This issue is inspired from [stackoverflow](https://stackoverflow.com/questions/51415107/what-problems-can-lead-to-a-cudnnerror-with-convolutionnd/51438957)

As mentioned in #3874, dilate parameter > 1 is incompatible with deterministic version of  cudnn convolutionBackwardData().

The problem is resolved by #3875, but the problem still remains in functions/connection/deconvolution_nd.py.

The similar patch should be applied.

**Comment by fiarabbit** [comment]
Replication code is given below.

- chainer==v5.0.0b3
- cupy==v5.0.0b3

```replica.py
import chainer
from chainer import functions as F
import numpy, cupy

xp = cupy
dtype = numpy.float32

n = 2
c_in = 3
c_out = 2
size_in = (4, 3)
ksize = (3, 3)
x_shape = (n, c_in) + size_in
W_shape = (c_out, c_in) + ksize
b_shape = (c_out,)
dilate = 2
pad = ((ksize[0] // 2) * dilate, (ksize[1] // 2) * dilate)

x = chainer.Variable(xp.random.randn(*x_shape).astype(dtype))
W = chainer.Variable(xp.random.randn(*W_shape).astype(dtype))

y = F.convolution_nd(x, W, dilate=dilate, pad=pad)
y.grad = xp.ones(y.shape, dtype=y.dtype)

with chainer.using_config('use_cudnn', 'always'), \
     chainer.using_config('cudnn_deterministic', True):
    y.backward()
```
```stacktrace.py
Traceback (most recent call last):
  File "replica.py", line 27, in <module>
    y.backward()
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "~/.chainer-latest/lib/python3.5/site-packages/chainer/configuration.py", line 127, in using_config
    yield
  File "replica.py", line 27, in <module>
    y.backward()
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "~/.chainer-latest/lib/python3.5/site-packages/chainer/configuration.py", line 127, in using_config
    yield
  File "replica.py", line 27, in <module>
    y.backward()
  File "~/.chainer-latest/lib/python3.5/site-packages/chainer/variable.py", line 956, in backward
    self._backward_main(retain_grad, loss_scale)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "~/.chainer-latest/lib/python3.5/site-packages/chainer/configuration.py", line 127, in using_config
    yield
  File "~/.chainer-latest/lib/python3.5/site-packages/chainer/variable.py", line 956, in backward
    self._backward_main(retain_grad, loss_scale)
  File "~/.chainer-latest/lib/python3.5/site-packages/chainer/variable.py", line 1085, in _backward_main
    target_input_indexes, out_grad, in_grad)
  File "~/.chainer-latest/lib/python3.5/site-packages/chainer/function_node.py", line 545, in backward_accumulate
    gxs = self.backward(target_input_indexes, grad_outputs)
  File "~/.chainer-latest/lib/python3.5/site-packages/chainer/functions/connection/convolution_nd.py", line 172, in backward
    dilate=self.dilate, groups=self.groups)
  File "~/.chainer-latest/lib/python3.5/site-packages/chainer/functions/connection/deconvolution_nd.py", line 371, in deconvolution_nd
    y, = func.apply(args)
  File "~/.chainer-latest/lib/python3.5/site-packages/chainer/function_node.py", line 257, in apply
    outputs = self.forward(in_data)
  File "~/.chainer-latest/lib/python3.5/site-packages/chainer/functions/connection/deconvolution_nd.py", line 181, in forward
    return self._forward_cudnn(x, W, b)
  File "~/.chainer-latest/lib/python3.5/site-packages/chainer/functions/connection/deconvolution_nd.py", line 155, in _forward_cudnn
    tensor_core=tensor_core)
  File "cupy/cudnn.pyx", line 973, in cupy.cudnn.convolution_backward_data
  File "cupy/cuda/cudnn.pyx", line 1303, in cupy.cuda.cudnn.getConvolutionBackwardDataWorkspaceSize
  File "cupy/cuda/cudnn.pyx", line 573, in cupy.cuda.cudnn.check_status
cupy.cuda.cudnn.CuDNNError: CUDNN_STATUS_NOT_SUPPORTED
```

**Comment by kmaehashi** [comment]
Fixed via https://github.com/chainer/chainer/pull/5129
