### ISSUE TITLE
GPU computation in L.NStepLSTM may fail if not on the current device

### ISSUE THREAD

**Issue by toslunar** [chainer/chainer#5347]
`xp.array` outside `FunctionNode` leads to this kind of bugs.

* Conditions
```
Platform: Linux-4.4.0-103-generic-x86_64-with-debian-stretch-sid
Chainer: 5.0.0b4
NumPy: 1.16.0.dev0+91454d6
CuPy:
  CuPy Version          : 5.0.0b4
  CUDA Root             : /usr/local/cuda
  CUDA Build Version    : 9000
  CUDA Driver Version   : 9000
  CUDA Runtime Version  : 9000
  cuDNN Build Version   : 7104
  cuDNN Version         : 7104
  NCCL Build Version    : 2005
```
* Code to reproduce
```
>>> lstm = chainer.links.NStepLSTM(1, 9, 9, 0)
>>> lstm.to_gpu(1)
<chainer.links.connection.n_step_lstm.NStepLSTM object at 0x2baa76604c88>
>>> x = chainer.Variable(numpy.random.rand(3, 9).astype('f'))
>>> x.to_gpu(1)
```
* Error messages, stack traces, or logs
```
>>> lstm(None, None, [x])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kataoka/chainer/chainer/link.py", line 204, in __call__
    return forward(*args, **kwargs)
  File "/home/kataoka/chainer/chainer/links/connection/n_step_lstm.py", line 70, in forward
    (hy, cy), ys = self._call([hx, cx], xs, **kwargs)
  File "/home/kataoka/chainer/chainer/links/connection/n_step_rnn.py", line 209, in _call
    for h in result[:-1]]
  File "/home/kataoka/chainer/chainer/links/connection/n_step_rnn.py", line 209, in <listcomp>
    for h in result[:-1]]
  File "/home/kataoka/chainer/chainer/functions/array/permutate.py", line 134, in permutate
    y, = Permutate(axis, inv).apply((x, indices))
  File "/home/kataoka/chainer/chainer/function_node.py", line 257, in apply
    outputs = self.forward(in_data)
  File "/home/kataoka/chainer/chainer/functions/array/permutate.py", line 74, in forward
    return self._permutate(x, inds, self.inv),
  File "/home/kataoka/chainer/chainer/functions/array/permutate.py", line 63, in _permutate
    indices = _inverse_indices(indices)
  File "/home/kataoka/chainer/chainer/functions/array/permutate.py", line 35, in _inverse_indices
    )(indices, r)
  File "cupy/core/_kernel.pyx", line 513, in cupy.core._kernel.ElementwiseKernel.__call__
  File "cupy/core/_kernel.pyx", line 74, in cupy.core._kernel._preprocess_args
ValueError: Array device must be same as the current device: array device = 0 while current = 1
```

**Comment by fiarabbit** [comment]
This issue is not perfectly resolved (see #6262). If `n_layers>1`, `dropout!=0`, and `config.train==True`, `permutate` still fails with CUDA error.
