### ISSUE TITLE
`backward` of HuberLoss fails when dimension of inputs >= 3

### ISSUE THREAD

**Issue by nel215** [chainer/chainer#5487]
`backward` of HuberLoss fails when dimension of inputs >= 3. Should [this reshape](https://github.com/chainer/chainer/blob/v5.0.0rc1/chainer/functions/loss/huber_loss.py#L57) be `gy = gy.reshape(gy.shape[:1] + (1,) + gy.shape[1:])` ?

* Conditions
  - Platform: Linux-4.4.0-137-generic-x86_64-with-debian-stretch-sid
  - Chainer: 5.0.0rc1
  - NumPy: 1.15.2
  - CuPy: Not Available

* Code to reproduce
```
from chainer import Parameter
from chainer import functions as F

shape = (2, 3, 4)
x = Parameter(np.ones(shape))
y = Parameter(np.zeros(shape))
z = F.mean(F.huber_loss(x, y, 1.0))
z.backward()
```

* Error messages, stack traces, or logs
```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    z.backward()
  File "/chainer/chainer/variable.py", line 963, in backward
    self._backward_main(retain_grad, loss_scale)
  File "/chainer/chainer/variable.py", line 1040, in _backward_main
    func, target_input_indexes, out_grad, in_grad)
  File "/chainer/chainer/_backprop_utils.py", line 106, in backprop_step
    target_input_indexes, grad_outputs)
  File "/chainer/chainer/functions/loss/huber_loss.py", line 58, in backward
    gx = chainer.functions.broadcast_to(gy, gx.shape) * gx
  File "/chainer/chainer/functions/array/broadcast.py", line 132, in broadcast_to
    y, = BroadcastTo(shape).apply((x,))
  File "/chainer/chainer/function_node.py", line 245, in apply
    self._check_data_type_forward(in_data)
  File "/chainer/chainer/function_node.py", line 330, in _check_data_type_forward
    self.check_type_forward(in_type)
  File "/chainer/chainer/functions/array/broadcast.py", line 74, in check_type_forward
    type_check.expect(in_types[0].ndim <= ndim)
  File "/chainer/chainer/utils/type_check.py", line 546, in expect
    expr.expect()
  File "/chainer/chainer/utils/type_check.py", line 483, in expect
    '{0} {1} {2}'.format(left, self.inv, right))
chainer.utils.type_check.InvalidType:
Invalid operation is performed in: BroadcastTo (Forward)
```

**Comment by toslunar** [comment]
It's documented that the shapes must be (N, K).
Nevertheless, any failure in `backward` is a bug.

BTW,
- `F.expand_dims` looks better.
- automatic broadcast could be used below.
