### ISSUE TITLE
Out of memory error with Chainer-5.0-Cupy-5.0-Python2.7

### ISSUE THREAD

**Issue by surajkota** [chainer/chainer#5621]
Hi,

I am trying to run synthetic data training with Chainer on a 8 GPU machine. The [scripts](https://github.com/surajkota/deep-learning-benchmark-mirror/blob/master/chainer_examples/imagenet/train_imagenet_data_parallel.py) I am running are modification of [imagenet example scripts from chainers official repository](https://github.com/chainer/chainer/tree/v5/examples/imagenet) to run synthetic data.

For, python2.7
Training processes errors out with **out of memory error for more than 16 batch size** and below is the stack trace

Python3.6
I am able to go upto **128** batch size with same setup

Same scripts run fine for Chainer==4.5 & CuPy==4.5 for both python2.7 and python3.6 upto 128 batch size
Note that running mnist passes but resnet fails for batch size more than 16 within first few epochs. 

**Stack trace:**

```
Epoch: [3] 	 Batch_speed: 3158.273 samples/sec
Epoch: [3] 	 Speed: 3099.142 samples/sec 	 Time cost=0.323
Exception in main training loop: out of memory to allocate 205520896 bytes (total 16068929536 bytes)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/chainer/training/trainer.py", line 315, in run
    update()
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/chainer/training/updaters/standard_updater.py", line 165, in update
    self.update_core()
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/chainer/training/updaters/multiprocess_parallel_updater.py", line 237, in update_core
    loss = _calc_loss(self._master, batch)
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/chainer/training/updaters/multiprocess_parallel_updater.py", line 271, in _calc_loss
    return model(*in_arrays)
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/chainer/link.py", line 242, in __call__
    out = forward(*args, **kwargs)
  File "/home/ubuntu/chainer/examples/imagenet/resnet50.py", line 101, in forward
    h = self.res2(h)
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/chainer/link.py", line 242, in __call__
    out = forward(*args, **kwargs)
  File "/home/ubuntu/chainer/examples/imagenet/resnet50.py", line 78, in forward
    x = f(x)
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/chainer/link.py", line 242, in __call__
    out = forward(*args, **kwargs)
  File "/home/ubuntu/chainer/examples/imagenet/resnet50.py", line 36, in forward
    h1 = self.bn3(self.conv3(h1))
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/chainer/link.py", line 242, in __call__
    out = forward(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/chainer/links/normalization/batch_normalization.py", line 299, in forward
    running_var=self.avg_var, decay=decay, axis=self.axis)
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/chainer/functions/normalization/batch_normalization.py", line 832, in batch_normalization
    axis).apply((x, gamma, beta))[0]
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/chainer/function_node.py", line 263, in apply
    outputs = self.forward(in_data)
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/chainer/functions/normalization/batch_normalization.py", line 204, in forward
    y = cuda.cupy.empty_like(x)
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/cupy/creation/basic.py", line 42, in empty_like
    return cupy.ndarray(a.shape, dtype)
  File "cupy/core/core.pyx", line 150, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 517, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1064, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1085, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 899, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 920, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 694, in cupy.cuda.memory._try_malloc

```

I checked the output of nvidia-smi and it increases for a while and then some of the processes crash making GPU utilization 0 for the GPUs which it was using. Other processes keep running and GPU utilization also looks good

For example if only Process _Worker-1 crashed the output would look like this:
```
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:17.0 Off |                    0 |
| N/A   45C    P0    56W / 300W |  16045MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:00:18.0 Off |                    0 |
| N/A   45C    P0    67W / 300W |  15795MiB / 16160MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:00:19.0 Off |                    0 |
| N/A   46C    P0    67W / 300W |  15771MiB / 16160MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:00:1A.0 Off |                    0 |
| N/A   51C    P0    73W / 300W |  15771MiB / 16160MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla V100-SXM2...  On   | 00000000:00:1B.0 Off |                    0 |
| N/A   51C    P0    68W / 300W |  15771MiB / 16160MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla V100-SXM2...  On   | 00000000:00:1C.0 Off |                    0 |
| N/A   49C    P0    71W / 300W |  15771MiB / 16160MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla V100-SXM2...  On   | 00000000:00:1D.0 Off |                    0 |
| N/A   45C    P0    71W / 300W |  15575MiB / 16160MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla V100-SXM2...  On   | 00000000:00:1E.0 Off |                    0 |
| N/A   50C    P0    71W / 300W |  15575MiB / 16160MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      9516      C   python                                     16034MiB |
|    1      9582      C   python                                     15784MiB |
|    2      9583      C   python                                     15760MiB |
|    3      9584      C   python                                     15760MiB |
|    4      9585      C   python                                     15760MiB |
|    5      9586      C   python                                     15760MiB |
|    6      9587      C   python                                     15564MiB |
|    7      9588      C   python                                     15564MiB |
+-----------------------------------------------------------------------------+
```

The program becomes like a zombiee process after this and I need to find the pid to kill it.

  - Chainer version - 5.0.0
  - CuPy version - 5.0.0
  - OS/Platform - Ubuntu 16.04
  - CUDA/cuDNN version - 9.0.176/7.3.1.20

**Replication steps**

```
pip install chainer==5.0.0
pip install cupy=5.0.0
```

```
git clone https://github.com/surajkota/deep-learning-benchmark-mirror
python train_imagenet_data_parallel.py --arch resnet50 --dataset synthetic --epoch 30 --loaderjob 30 --samples 10000 --batchsize 128 ~/ ~/ -g 0 1 2 3 4 5 6 7
```

**Instance type:** 
AWS EC2 p3.16xlarge 
it has 8 NVIDIA Tesla V100 GPUs, 64 Intel Xeon E5-2686 v4 (Broadwell) processors, 488 GB RAM

CPU info:
```
processor	: 61
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
stepping	: 1
microcode	: 0xb00002a
cpu MHz		: 1514.496
cache size	: 46080 KB
physical id	: 1
siblings	: 32
core id		: 13
cpu cores	: 16
apicid		: 91
initial apicid	: 91
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq monitor est ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single kaiser fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx xsaveopt ida
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips	: 4600.12
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

```

Let me know if more information is needed

I have filed the same issue with CuPy, I was [suggested to post it on Chainer's repo](https://github.com/cupy/cupy/issues/1772#issuecomment-435642222)

TIA

**Comment by kmaehashi** [comment]
Thanks for reporting an issue. I'll look into it.

Btw, may I ask if you have any special reasons to use Python 2.7?

**Comment by yy29** [comment]
Hi, I'm also facing with similar issue after I installed the latest version of Chainer+Cupy.
I'm running a custom version of fully convolution network and the GPU memory usage checked through nvidia-smi gave me about 4 times more than the previous version I used.

The version I'm using with GPU memory problem is
Python 2.7
Chainer 5.0.0
Cupy 5.0.0

The version I was using without any specific memory problem is
Python 2.7
Chainer 4.2.0
Cupy 4.5.0

Thanks

**Comment by surajkota** [comment]
hello,

Do we have any update on this issue?

> if you have any special reasons to use Python 2.7?
Legacy

**Comment by ericmjl** [comment]
With Chainer 5, CuPy 5, Python 3.6, I am also facing OutOfMemoryErrors on a message passing neural network model. When I profile memory usage, I see the following usage:

```
    FunctionName  UsedBytes  AcquiredBytes  Occurrence
       CooMatMul     6.58GB         2.57GB        2034
  LinearFunction     2.55GB         2.17GB        4066
            Tanh     4.62GB         4.33GB        3048
         Reshape      0.00B          0.00B        1524
MeanSquaredError    44.15MB          0.00B        1016
             Sub    10.91MB          0.00B         508
     BroadcastTo      0.00B          0.00B         508
             Mul    10.91MB          0.00B         508
     MulConstant    10.91MB          0.00B         508
  LinearGradData   224.73MB          0.00B        1524
LinearGradWeight  1016.00KB          0.00B        2032
             Sum  1016.00KB          0.00B        2032
        TanhGrad     2.31GB         2.16GB        1524
             Add   508.00KB          0.00B        1016
```

I am not quite sure why CooMatMul accumulates acquired and used bytes as I go through the training loop:

```python
optimizer = Adam().setup(mpnn)
with hook:
    losses = []
    for i in tqdmn(range(550)):
        chainer.cuda.memory_pool.free_all_blocks()    
        prediction = mpnn(Fs, As_Coo, Ss_Coo)

        # Calculate the loss with softmax_cross_entropy
        loss = F.mean_squared_error(prediction.reshape(-1), targets)
        losses.append(loss)

        # Calculate the gradients in the network
        mpnn.cleargrads()
        loss.backward()

        # Update all the trainable parameters
        optimizer.update()
```

**Comment by takagi** [comment]
I reproduce the case on my local:
```
Python2
Chainer==4.5 & CuPy==4.5, batch=32 => OK
Chainer==5.0 & CuPy==5.0, batch=32 => NG
Chainer==5.0 & CuPy==5.0, batch=16 => OK

Python3
Chainer==5.0 & CuPy==5.0, batch=32 => OK
```

Although Python2 might be discontinued in near future, I'll look into this case to find if there would be unexpected something.

**Comment by surajkota** [comment]
Thanks takagi@ for looking into it. Let us know if we can help in anyway. 

With python 3.6 I can go up to 138 batch size, till Chainer 4.5, I could go up to 128 batch size in Python 2.7 as well.

**Comment by takagi** [comment]
I profiled memory usage of functions and found much difference for all functions, not for a specific one, between 5.0.0 and 4.5.0 
```
$ pip2 install chainer==5.0.0 cupy==5.0.0 numpy==1.15.4
$ python2 train_imagenet_data_parallel.py --arch resnet50 --dataset synthetic --epoch 1 --loaderjob 1 --samples 1000 --batchsize 32 ~/ ~/ -g 0 1 2 3
Epoch: [0] 	 Batch_speed: 36.804 samples/sec
Epoch: [0] 	 Batch_speed: 326.431 samples/sec
Epoch: [0] 	 Batch_speed: 1009.129 samples/sec
Epoch: [0] 	 Batch_speed: 529.291 samples/sec
Epoch: [0] 	 Batch_speed: 330.712 samples/sec
Epoch: [0] 	 Batch_speed: 322.949 samples/sec
Epoch: [0] 	 Batch_speed: 323.138 samples/sec
Epoch: [1] 	 Batch_speed: 326.181 samples/sec
Epoch: [1] 	 Speed: 172.100 samples/sec 	 Time cost=5.811
           FunctionName  UsedBytes  AcquiredBytes  Occurrence
  Convolution2DFunction    25.94GB         2.22GB         848
     BatchNormalization    20.20GB         2.15GB         848
                   ReLU    17.32GB         3.54GB         784
           MaxPooling2D   980.00MB        24.50MB          16
                    Add    10.62GB         3.58GB         384
       AveragePooling2D   100.00MB          0.00B          16
                Reshape      0.00B          0.00B          24
         LinearFunction    67.46MB          0.00B          16
    SoftmaxCrossEntropy     2.95MB          0.00B          16
               Accuracy    12.00KB          0.00B           8
         LinearGradData     2.00MB          0.00B           8
       LinearGradWeight    62.50MB          0.00B           8
                    Sum    36.00KB          0.00B          16
   AveragePooling2DGrad    98.00MB          0.00B           8
              ReLUGrad2     8.66GB        36.75MB         392
 BatchNormalizationGrad    10.10GB          0.00B         424
Deconvolution2DFunction     9.75GB       857.50MB         416
     Convolution2DGradW   717.21MB        24.00MB         424
       MaxPooling2DGrad   784.00MB          0.00B           8
$ pip2 install chainer==4.5.0 cupy==4.5.0 numpy==1.15.4
$ python2 train_imagenet_data_parallel.py --arch resnet50 --dataset synthetic --epoch 1 --loaderjob 1 --samples 1000 --batchsize 32 ~/ ~/ -g 0 1 2 3
Epoch: [0] 	 Batch_speed: 36.501 samples/sec
Epoch: [0] 	 Batch_speed: 336.357 samples/sec
Epoch: [0] 	 Batch_speed: 1341.145 samples/sec
Epoch: [0] 	 Batch_speed: 518.724 samples/sec
Epoch: [0] 	 Batch_speed: 346.009 samples/sec
Epoch: [0] 	 Batch_speed: 336.122 samples/sec
Epoch: [0] 	 Batch_speed: 330.467 samples/sec
Epoch: [1] 	 Batch_speed: 315.111 samples/sec
Epoch: [1] 	 Speed: 173.196 samples/sec 	 Time cost=5.774
           FunctionName  UsedBytes  AcquiredBytes  Occurrence
  Convolution2DFunction    25.94GB       882.07MB         848
     BatchNormalization    20.20GB       673.75MB         848
                   ReLU    17.32GB       808.50MB         784
           MaxPooling2D   980.00MB        24.50MB          16
                    Add    10.62GB       894.25MB         384
       AveragePooling2D   100.00MB          0.00B          16
                Reshape      0.00B          0.00B          24
         LinearFunction    65.51MB          0.00B          16
    SoftmaxCrossEntropy     2.95MB          0.00B          16
               Accuracy    12.00KB          0.00B           8
         LinearGradData     2.00MB          0.00B           8
       LinearGradWeight    62.50MB          0.00B           8
                    Sum    36.00KB          0.00B          16
   AveragePooling2DGrad    98.00MB          0.00B           8
              ReLUGrad2     8.66GB        12.25MB         392
 BatchNormalizationGrad    10.10GB          0.00B         424
Deconvolution2DFunction     9.75GB       367.50MB         416
     Convolution2DGradW   717.21MB          0.00B         424
       MaxPooling2DGrad   784.00MB          0.00B           8
```

**Comment by takagi** [comment]
I look in CuPy's memory management routines.

**Comment by takagi** [comment]
I observed how memory blocks are allocated in ReLU backward computation, that is `ReLuGrad2`'s forward computation. The reason I selected the part is that `ReLUGrad2` has reasonable difference in acquired bytes above and `ReLUGrad2.forward_gpu` has just a call to a CuPy operation.

**Python2; Chainer 4.5 & CuPy 4.5**
```Python
class ReLUGrad2(function_node.FunctionNode):
    ...
    def forward_gpu(self, inputs):
        with memory_hooks.DebugPrintHook():
            gx = cuda.elementwise(
                'T y, T gy', 'T gx',
                'gx = y > 0 ? gy : (T)0',
                'relu_bwd')(self.b, inputs[0])
        return gx,
    ...
```
```
$ python2 train_imagenet_data_parallel.py --arch resnet50 --dataset synthetic --epoch 1 --loaderjob 1 --samples 1000 --batchsize 32 ~/ ~/ -g 0 1 2 3 | grep \"alloc\"
{"hook":"alloc","device_id":3,"mem_size":12845056,"mem_ptr":153213075456}
{"hook":"alloc","device_id":0,"mem_size":12845056,"mem_ptr":153213075456}
{"hook":"alloc","device_id":2,"mem_size":12845056,"mem_ptr":153213075456}
{"hook":"alloc","device_id":1,"mem_size":12845056,"mem_ptr":153213075456}
```
**Python2; Chainer 5.0 & CuPy 5.0**
```Python
class ReLUGrad2(function_node.FunctionNode):
    ...
    def forward_gpu(self, inputs):
        with memory_hooks.DebugPrintHook():
            gx = _relu_grad2_kernel(self.b, inputs[0])
        return gx,
    ...
```
```
$ python2 train_imagenet_data_parallel.py --arch resnet50 --dataset synthetic --epoch 1 --loaderjob 1 --samples 1000 --batchsize 32 ~/ ~/ -g 0 1 2 3 | grep \"alloc\"
{"hook":"alloc","device_id":0,"mem_size":12845056,"mem_ptr":153213075456}
{"hook":"alloc","device_id":1,"mem_size":12845056,"mem_ptr":153213075456}
{"hook":"alloc","device_id":3,"mem_size":12845056,"mem_ptr":153213075456}
{"hook":"alloc","device_id":2,"mem_size":12845056,"mem_ptr":153213075456}
{"hook":"alloc","device_id":0,"mem_size":12845056,"mem_ptr":155705016320}
{"hook":"alloc","device_id":1,"mem_size":12845056,"mem_ptr":155589410816}
{"hook":"alloc","device_id":2,"mem_size":12845056,"mem_ptr":155589410816}
{"hook":"alloc","device_id":3,"mem_size":12845056,"mem_ptr":155589410816}
{"hook":"alloc","device_id":1,"mem_size":12845056,"mem_ptr":157888675840}
{"hook":"alloc","device_id":2,"mem_size":12845056,"mem_ptr":157888675840}
{"hook":"alloc","device_id":3,"mem_size":12845056,"mem_ptr":157892870144}
{"hook":"alloc","device_id":0,"mem_size":12845056,"mem_ptr":158145576960}
{"hook":"alloc","device_id":1,"mem_size":12845056,"mem_ptr":160316391424}
{"hook":"alloc","device_id":2,"mem_size":12845056,"mem_ptr":160320585728}
{"hook":"alloc","device_id":3,"mem_size":12845056,"mem_ptr":160324780032}
```
It looks that memory size requested to allocate does not get larger, but a number of actual allocation from GPU becomes larger. From this, I suspect that allocated memory blocks might not be returned to the pool properly.

**Comment by takagi** [comment]
@surajkota Would you try the latest `v5` branch on your Python2 environment? The problem should be away.

**Comment by saydulk** [comment]
same problem 

![screenshot from 2019-01-30 23-49-25](https://user-images.githubusercontent.com/1058663/52001467-b0944e00-24e9-11e9-9f08-50a60b713bec.png)

**Comment by surajkota** [comment]
Thanks takagi@, okuta@ and chainer community for prioritizing the issue.

I will follow the instructions here: https://docs.chainer.org/en/stable/install.html#using-tarball to build chainer from master branch
do I need to build both Chainer and Cupy from source?

**Comment by takagi** [comment]
Would you try to build `v5` Chainer first, which does not take so much time? I think #6105 is the most effective fix.

**Comment by kwasnydam** [comment]
> With Chainer 5, CuPy 5, Python 3.6, I am also facing OutOfMemoryErrors on a message passing neural network model. When I profile memory usage, I see the following usage:
> 
> ```
>     FunctionName  UsedBytes  AcquiredBytes  Occurrence
>        CooMatMul     6.58GB         2.57GB        2034
>   LinearFunction     2.55GB         2.17GB        4066
>             Tanh     4.62GB         4.33GB        3048
>          Reshape      0.00B          0.00B        1524
> MeanSquaredError    44.15MB          0.00B        1016
>              Sub    10.91MB          0.00B         508
>      BroadcastTo      0.00B          0.00B         508
>              Mul    10.91MB          0.00B         508
>      MulConstant    10.91MB          0.00B         508
>   LinearGradData   224.73MB          0.00B        1524
> LinearGradWeight  1016.00KB          0.00B        2032
>              Sum  1016.00KB          0.00B        2032
>         TanhGrad     2.31GB         2.16GB        1524
>              Add   508.00KB          0.00B        1016
> ```
> I am not quite sure why CooMatMul accumulates acquired and used bytes as I go through the training loop:
> 
> ```python
> optimizer = Adam().setup(mpnn)
> with hook:
>     losses = []
>     for i in tqdmn(range(550)):
>         chainer.cuda.memory_pool.free_all_blocks()    
>         prediction = mpnn(Fs, As_Coo, Ss_Coo)
> 
>         # Calculate the loss with softmax_cross_entropy
>         loss = F.mean_squared_error(prediction.reshape(-1), targets)
>         losses.append(loss)
> 
>         # Calculate the gradients in the network
>         mpnn.cleargrads()
>         loss.backward()
> 
>         # Update all the trainable parameters
>         optimizer.update()
> ```

Not sure if you still need help on that, but it seems you are adding the loss variable, which is a part of the computational graph, to the list, so that the memory and the graph can not be released properly. You should retrieve only the data from the loss variable (append loss.data)

**Comment by Azuki-Azusa** [comment]
> > With Chainer 5, CuPy 5, Python 3.6, I am also facing OutOfMemoryErrors on a message passing neural network model. When I profile memory usage, I see the following usage:
> > ```
> >     FunctionName  UsedBytes  AcquiredBytes  Occurrence
> >        CooMatMul     6.58GB         2.57GB        2034
> >   LinearFunction     2.55GB         2.17GB        4066
> >             Tanh     4.62GB         4.33GB        3048
> >          Reshape      0.00B          0.00B        1524
> > MeanSquaredError    44.15MB          0.00B        1016
> >              Sub    10.91MB          0.00B         508
> >      BroadcastTo      0.00B          0.00B         508
> >              Mul    10.91MB          0.00B         508
> >      MulConstant    10.91MB          0.00B         508
> >   LinearGradData   224.73MB          0.00B        1524
> > LinearGradWeight  1016.00KB          0.00B        2032
> >              Sum  1016.00KB          0.00B        2032
> >         TanhGrad     2.31GB         2.16GB        1524
> >              Add   508.00KB          0.00B        1016
> > ```
> > 
> > 
> > I am not quite sure why CooMatMul accumulates acquired and used bytes as I go through the training loop:
> > ```python
> > optimizer = Adam().setup(mpnn)
> > with hook:
> >     losses = []
> >     for i in tqdmn(range(550)):
> >         chainer.cuda.memory_pool.free_all_blocks()    
> >         prediction = mpnn(Fs, As_Coo, Ss_Coo)
> > 
> >         # Calculate the loss with softmax_cross_entropy
> >         loss = F.mean_squared_error(prediction.reshape(-1), targets)
> >         losses.append(loss)
> > 
> >         # Calculate the gradients in the network
> >         mpnn.cleargrads()
> >         loss.backward()
> > 
> >         # Update all the trainable parameters
> >         optimizer.update()
> > ```
> 
> Not sure if you still need help on that, but it seems you are adding the loss variable, which is a part of the computational graph, to the list, so that the memory and the graph can not be released properly. You should retrieve only the data from the loss variable (append loss.data)

Thank you！Your method is helpful.
