### ISSUE TITLE
tuple index out of range in NstepBilstm

### ISSUE THREAD

**Issue by MADONOKOUKI** [chainer/chainer#5697]
I'm trying to use NStepLSTM like as follows. I Input 6 images and try to extract feature from pre-trained model. Also use BiLSTM I try to calculate similarity of first image and last image. Lastly I got this errror. My code is like this.
```
Traceback (most recent call last):
  File "train2.py", line 105, in <module>
    main()
  File "train2.py", line 94, in main
    trainer.run()
  File "/root/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/chainer/training/trainer.py", line 348, in run
    six.reraise(*exc_info)
  File "/root/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/root/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/chainer/training/trainer.py", line 315, in run
    update()
  File "/var/docker/share/madono/summer/siamese_for_amt/standard_updater.py", line 165, in update
    self.update_core()
  File "/var/docker/share/madono/summer/siamese_for_amt/standard_updater.py", line 177, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/root/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/chainer/optimizer.py", line 680, in update
    loss = lossfun(*args, **kwds)
  File "/root/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/chainer/link.py", line 242, in __call__
    out = forward(*args, **kwargs)
  File "/var/docker/share/madono/summer/siamese_for_amt/Classifier.py", line 58, in forward
    self.loss = self.lossfun(yi, ti)
  File "/root/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/chainer/functions/loss/softmax_cross_entropy.py", line 412, in softmax_cross_entropy
    loss, = func.apply((x, t))
  File "/root/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/chainer/function_node.py", line 245, in apply
    self._check_data_type_forward(in_data)
  File "/root/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/chainer/function_node.py", line 322, in _check_data_type_forward
    self.check_type_forward(in_type)
  File "/root/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/chainer/functions/loss/softmax_cross_entropy.py", line 78, in check_type_forward
    x_type.shape[0] == t_type.shape[0],
IndexError: tuple index out of range
```
```
import argparse
import numpy
import cupy
import chainer
import chainer.functions as F
import chainer.links as L


class BiLSTMAMT(chainer.Chain):

    def __init__(self):
        super(BiLSTMAMT, self).__init__()
        with self.init_scope():
          self.feature_extract = L.ResNet152Layers()
         # self.temporal = L.NStepBiLSTM(n_layers=5, in_size=10,
          #            out_size=20, dropout=0.5)
          self.temporal = L.NStepLSTM(5,1000,10,dropout=0.5)
          self.fc1 = L.Linear(1000,2)
          self.trans_fc = L.Linear(20,10)
          self.fc2 = L.Linear(10, 2)

    def __call__(self,x):
        layer = None
        hx = None
        cx = None
        xs_f = []
        for i in range(6):
          h1 = self.feature_extract(x[:,i,:,:,:].reshape(4,3,96,96),layers=['fc6'])['fc6']
          h1.unchain_backward()
          xs_f.append(h1)

        hy, cy, ys = self.temporal(hx=hx, cx=cx, xs=xs_f)
        h3 = [F.softmax(self.fc2(item)) for item in ys]
        return h3
```
And I calculate my loss like
```
self.y = None
        self.loss = None
        self.accuracy = None

        self.y = self.predictor(*args, **kwargs)
#        self.loss = self.lossfun(self.y, t) + chainer.functions.hinge(self.y,t)
#        print(self.loss)
        for yi, ti in zip(self.y[0], t):
          if self.loss is not None:
            self.loss += self.lossfun(yi, ti)
          else:
            print(yi, ti)
```

**Comment by fiarabbit** [comment]
According to the [contribution guide](http://docs.chainer.org/en/stable/contribution.html), any general question is preferred to be raised at the StackOverflow with a `chainer` tag.

```
Warning

If you have a question on usages of Chainer, it is highly recommended to send a post to
StackOverflow or Chainer User Group instead of the issue tracker. The issue tracker is not a place
to share knowledge on practices. We may suggest these places and immediately close how-to
question issues.
```

**Comment by MADONOKOUKI** [comment]
@fiarabbit I didn't know that, thanks! I'll ask it on StackOverflow or Chainer User Group instead of the issue tracker!
