### ISSUE TITLE
Broadcasting failed when using GPU version on linux

### ISSUE THREAD

**Issue by linfengyu77** [chainer/chainer#5703]
I found an error when using cupy and this problem only occurs in Linux version. The program running without errors under windows. This issue running with Chainer 5.0.0, CuPy 5.0.0, CUDA 9.0, cuDNN 9.0.

Reproduction code:
```python
import numpy as np
import chainer
import chainer.functions as F
from chainer import cuda, optimizers, serializers, Variable
from chainer import training

class Updater(chainer.training.StandardUpdater):

    def __init__(self, *args, **kwargs):
        self.model = kwargs.pop('models')
        xp = self.model.xp
        super(Updater, self).__init__(*args, **kwargs)

    def update_core(self):
        xp = self.model.xp
        train_batch = self.get_iterator('main').next()
        mask_batch = self.get_iterator('mask_train').next()
        batchsize = len(train_batch)
        w_in = 256
        x_train = xp.zeros((batchsize, 1, w_in, w_in)).astype(np.float32)
        mask_train = xp.zeros((batchsize, 1, w_in, w_in)).astype(np.float32)
        for i in range(batchsize):
            x_train[i, :] = xp.asarray(train_batch[i])
            mask_train[i, :] = xp.asarray(mask_batch[i])
```

Error messages:
```
Exception in main training loop: Broadcasting failed
Traceback (most recent call last):
  File "/public/software/python3/lib/python3.6/site-packages/chainer/training/trainer.py", line 315, in run
    update()
  File "/public/software/python3/lib/python3.6/site-packages/chainer/training/updaters/standard_updater.py", line 165, in update
    self.update_core()
  File "/home/fengw/GM_Unet/updater.py", line 38, in update_core
    mask_train[i,:] = xp.asarray(mask_batch[i])
  File "cupy/core/core.pyx", line 1688, in cupy.core.core.ndarray.__setitem__
  File "cupy/core/core.pyx", line 3531, in cupy.core.core._scatter_op
  File "cupy/core/_kernel.pyx", line 795, in cupy.core._kernel.ufunc.__call__
  File "cupy/core/core.pyx", line 2616, in cupy.core.core.broadcast.__init__
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "train.py", line 132, in <module>
    main()
  File "train.py", line 128, in main
    trainer.run()
  File "/public/software/python3/lib/python3.6/site-packages/chainer/training/trainer.py", line 329, in run
    six.reraise(*sys.exc_info())
  File "/public/software/python3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/public/software/python3/lib/python3.6/site-packages/chainer/training/trainer.py", line 315, in run
    update()
  File "/public/software/python3/lib/python3.6/site-packages/chainer/training/updaters/standard_updater.py", line 165, in update
    self.update_core()
  File "/home/updater.py", line 38, in update_core
    mask_train[i,:] = xp.asarray(mask_batch[i])
  File "cupy/core/core.pyx", line 1688, in cupy.core.core.ndarray.__setitem__
  File "cupy/core/core.pyx", line 3531, in cupy.core.core._scatter_op
  File "cupy/core/_kernel.pyx", line 795, in cupy.core._kernel.ufunc.__call__
  File "cupy/core/core.pyx", line 2616, in cupy.core.core.broadcast.__init__
ValueError: Broadcasting failed
```

**Comment by fiarabbit** [comment]
According to the [contribution guide](http://docs.chainer.org/en/stable/contribution.html), any general question is preferred to be raised at the StackOverflow with a `chainer` tag.

```
Warning

If you have a question on usages of Chainer, it is highly recommended to send a post to
StackOverflow or Chainer User Group instead of the issue tracker. The issue tracker is not a place
to share knowledge on practices. We may suggest these places and immediately close how-to
question issues.
```

In addition, this code only gives the definition of the Updater and is not a (ideally minimal) reproduction code.

In my opinion, this is caused by the difference between `numpy.asarray` and `cupy.asarray`. I guess in your MS Windows environment, `xp` stood for `numpy`, but in the Linux environment, `xp` stood for `cupy`.

**Comment by toslunar** [comment]
`ValueError: Broadcasting failed` depending on OS is strange enough to suspect bugs in Chainer or in CuPy.
Did you used the same device id (`GPU #0`, etc.)?

**Comment by linfengyu77** [comment]
> `ValueError: Broadcasting failed` depending on OS is strange enough to suspect bugs in Chainer or in CuPy.
> Did you used the same device id (`GPU #0`, etc.)?

yes, i used the same GUP id under both of windows and linux environment. I also tried to installed cupy-CUDA90 5.0.0 on the Linux, but it's still the same problem.

**Comment by takagi** [comment]
Would you show an entire reproduction code as well as the updater definition?
