### ISSUE TITLE
`chainerx.ndarray.__setitem__` raises `AttributeError` if CuPy is unavailable.

### ISSUE THREAD

**Issue by toslunar** [chainer/chainer#5884]
```
>>> x = chainerx.array([3])
>>> x[0] = 4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tos/GitHub/chainer/chainerx/_fallback_workarounds.py", line 134, in __setitem__
    if cupy is not None and isinstance(self, cupy.ndarray):
AttributeError: module 'cupy' has no attribute 'ndarray'
>>> chainer.print_runtime_info()
Platform: Darwin-18.2.0-x86_64-i386-64bit
Chainer: 6.0.0b1
NumPy: 1.15.4
CuPy: Not Available
iDeep: Not Available
>>> chainerx.is_available()
True
```

If CuPy is available, it raises with the expected message (while the type could be `NotImplementedError`)
```
>>> x = chainerx.array([3])
>>> x[0] = 4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'chainerx.ndarray' object does not support item assignment
```

**Comment by niboshi** [comment]
Which commit are you using?
I can't reproduce the reported behavior (I'm using current master 2e1c2838dcd14dc182766525f8511ce3e33617d9).

* Without CuPy
```
>>> x = chainerx.array([3])
>>> x[0] = 4
>>> x = chainerx.array([3], device='cuda')
>>> x[0] = 4
...
RuntimeError: ChainerX fallback implementation for cuda backend requires cupy to be installed.
```

* With CuPy
```
>>> x = chainerx.array([3], device='cuda')
>>> x[0] = 4
```
