### ISSUE TITLE
Fallbacks of ChainerX on GetItem fail when indices contains chainerx.ndarray

### ISSUE THREAD

**Issue by muupan** [chainer/chainer#5944]
When chainerx with `native` backend falls back to numpy:
```
>>> chainer.Variable(chainerx.zeros(3, device='native'))[numpy.arange(3)]
variable([0., 0., 0.])
>>> chainer.Variable(chainerx.zeros(3, device='native'))[chainerx.arange(3, device='native')]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fujita/.local/share/virtualenvs/chainerrl_20180827-9TPAa4mI/lib/python3.5/site-packages/chainer/functions/array/get_item.py", line 143, in get_item
    return GetItem(slices).apply((x,))[0]
  File "/home/fujita/.local/share/virtualenvs/chainerrl_20180827-9TPAa4mI/lib/python3.5/site-packages/chainer/function_node.py", line 315, in apply
    outputs = self.forward(in_data)
  File "/home/fujita/.local/share/virtualenvs/chainerrl_20180827-9TPAa4mI/lib/python3.5/site-packages/chainer/functions/array/get_item.py", line 41, in forward
    return utils.force_array(xs[0][self.slices]),
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

When chainerx with `cuda:0` backend falls back to cupy:
```
>>> chainer.Variable(chainerx.zeros(3, device='cuda:0'))[cupy.arange(3)]
variable([0., 0., 0.])
>>> chainer.Variable(chainerx.zeros(3, device='cuda:0'))[chainerx.arange(3, device='cuda:0')]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fujita/.local/share/virtualenvs/chainerrl_20180827-9TPAa4mI/lib/python3.5/site-packages/chainer/functions/array/get_item.py", line 143, in get_item
    return GetItem(slices).apply((x,))[0]
  File "/home/fujita/.local/share/virtualenvs/chainerrl_20180827-9TPAa4mI/lib/python3.5/site-packages/chainer/function_node.py", line 315, in apply
    outputs = self.forward(in_data)
  File "/home/fujita/.local/share/virtualenvs/chainerrl_20180827-9TPAa4mI/lib/python3.5/site-packages/chainer/functions/array/get_item.py", line 41, in forward
    return utils.force_array(xs[0][self.slices]),
  File "cupy/core/core.pyx", line 1650, in cupy.core.core.ndarray.__getitem__
  File "cupy/core/core.pyx", line 3255, in cupy.core.core._simple_getitem
TypeError: Invalid index type: <class 'chainerx.ndarray'>
```

I want these to work so I can write numpy/cupy/chainerx-agnostic code.

**Comment by niboshi** [comment]
We intentionally didn't support automatic fallback of tuples.
If we support tuples, we will have to make additional complicated decisions:
* Should we support lists or dicts? What about list-like or dict-like?
* What if the tuple has mixed types of `ndarray`s?

The simplest (somewhat tentative) decision was to only support bare `ndarray`s.
Of course, if that would be useful for users, we should consider supporting tuples. But at the same time, the bahavior should be easily understood for users as well.

**Comment by muupan** [comment]
I think this issue can be also fixed by chainerx supporting advanced indexing.

**Comment by muupan** [comment]
Does it still needs a discussion? The issue is that `GetItem` does not work as expected due to the lack of advanced indexing support.

**Comment by beam2d** [comment]
I think advanced indexing should definitely be supported in ChainerX (either in a fallback or direct way). The expected behavior is:

- Passing a chainerx ndarray on the same device should work as advanced indexing.
- Basic indexing should work as is, and should be mixed with advanced indexing.
- Passing numpy/cupy ndarray on the same device does not need to work (the current fallback works in this way, but I don't think it is an expected behavior for users).

I don't think we need any discussions for directly implementing it in ChainerX eventually; just the implementation would be complex and takes time to complete. Fixing the existing fallback mechanism would be easier to start from, though we need to make some decisions as @niboshi noted. I think it is as easy/difficult as directly implementing it in ChainerX, though, because it is just about deciding the API spec. I personally think 1) just supporting tuple is fine, and 2) it should support ChainerX ndarrays as indexes, and 3) it does not need to support numpy/cupy ndarrays (besides concerns on compatibility against the current behavior).

**Comment by beam2d** [comment]
It looks https://github.com/chainer/chainer/pull/6769 contains the fallback fix for this issue.

**Comment by hvy** [comment]
#6986 has now been fixed by https://github.com/chainer/chainer/pull/6991. I think we can close this issue as fixed as well?

**Comment by muupan** [comment]
Thank you so much for fixing the issue!
