### ISSUE TITLE
UserWarning: Shared memory size is too small. Please set shared_mem option for MultiprocessIterator.

### ISSUE THREAD

**Issue by zhangxiaodi** [chainer/chainer#5996]
Expect shared memory size: 131072 bytes. Actual shared memory size: 98304 bytes. UserWarning)

I use p100，16G memory！

the error information is follow.
```
Exception in main training loop: Unsupported dtype object
Traceback (most recent call last):
File "/home/user012/anaconda3/envs/GAN_znb/lib/python3.6/site-packages/chainer/training/trainer.py", line 299, in run
update()
File "/home/user012/anaconda3/envs/GAN_znb/lib/python3.6/site-packages/chainer/training/updater.py", line 223, in update
self.update_core()
File "/home/user012/GAN_poster/sngan_projection/updater.py", line 94, in update_core
x_real, y_real = self.get_batch(xp)
File "/home/user012/GAN_poster/sngan_projection/updater.py", line 73, in get_batch
print(type(xp.asarray(x)))
File "/home/user012/anaconda3/envs/GAN_znb/lib/python3.6/site-packages/cupy/creation/from_data.py", line 61, in asarray
return core.array(a, dtype, False)
File "cupy/core/core.pyx", line 2017, in cupy.core.core.array
File "cupy/core/core.pyx", line 2048, in cupy.core.core.array
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
File "train.py", line 136, in 
main()
File "train.py", line 132, in main
trainer.run()
File "/home/user012/anaconda3/envs/GAN_znb/lib/python3.6/site-packages/chainer/training/trainer.py", line 313, in run
six.reraise(*sys.exc_info())
File "/home/user012/anaconda3/envs/GAN_znb/lib/python3.6/site-packages/six.py", line 693, in reraise
raise value
File "/home/user012/anaconda3/envs/GAN_znb/lib/python3.6/site-packages/chainer/training/trainer.py", line 299, in run
update()
File "/home/user012/anaconda3/envs/GAN_znb/lib/python3.6/site-packages/chainer/training/updater.py", line 223, in update
self.update_core()
File "/home/user012/GAN_poster/sngan_projection/updater.py", line 94, in update_core
x_real, y_real = self.get_batch(xp)
File "/home/user012/GAN_poster/sngan_projection/updater.py", line 73, in get_batch
print(type(xp.asarray(x)))
File "/home/user012/anaconda3/envs/GAN_znb/lib/python3.6/site-packages/cupy/creation/from_data.py", line 61, in asarray
return core.array(a, dtype, False)
File "cupy/core/core.pyx", line 2017, in cupy.core.core.array
File "cupy/core/core.pyx", line 2048, in cupy.core.core.array
ValueError: Unsupported dtype object
```

what should i do, i have no idea to solve it!

**Comment by beam2d** [comment]
Is the stacktrace correct one? It does not look related to memory size.

As for `MultiprocessIterator`, you can pass `shared_mem` argument to enlarge the memory size. See https://docs.chainer.org/en/stable/reference/generated/chainer.iterators.MultiprocessIterator.html#chainer.iterators.MultiprocessIterator.

**Comment by fiarabbit** [comment]
This is a moved issue from cupy/cupy#1948.
@zhangxiaodi I think cupy/cupy#1948 should be closed.

**Comment by zhangxiaodi** [comment]
After i modify the memory size Setting , there have no this UserWarning. But the error still exit.
I don't know how to debug it. The process of getbatch is running well at first. After several minute，the error is follow to here. So what problem should be consider in this error.  

Exception in main training loop: Unsupported dtype object
Traceback (most recent call last):
  File "/home/user012/anaconda3/envs/GAN_znb/lib/python3.6/site-packages/chainer/training/trainer.py", line 299, in run
    update()
  File "/home/user012/anaconda3/envs/GAN_znb/lib/python3.6/site-packages/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/home/user012/GAN_poster/sngan_projection/updater.py", line 94, in update_core
    x_real, y_real = self.get_batch(xp)
  File "/home/user012/GAN_poster/sngan_projection/updater.py", line 73, in get_batch
    print(type(xp.asarray(x)))
  File "/home/user012/anaconda3/envs/GAN_znb/lib/python3.6/site-packages/cupy/creation/from_data.py", line 61, in asarray
    return core.array(a, dtype, False)
  File "cupy/core/core.pyx", line 2017, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2048, in cupy.core.core.array
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "train.py", line 136, in <module>
    main()
  File "train.py", line 132, in main
    trainer.run()
  File "/home/user012/anaconda3/envs/GAN_znb/lib/python3.6/site-packages/chainer/training/trainer.py", line 313, in run
    six.reraise(*sys.exc_info())
  File "/home/user012/anaconda3/envs/GAN_znb/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/user012/anaconda3/envs/GAN_znb/lib/python3.6/site-packages/chainer/training/trainer.py", line 299, in run
    update()
  File "/home/user012/anaconda3/envs/GAN_znb/lib/python3.6/site-packages/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/home/user012/GAN_poster/sngan_projection/updater.py", line 94, in update_core
    x_real, y_real = self.get_batch(xp)
  File "/home/user012/GAN_poster/sngan_projection/updater.py", line 73, in get_batch
    print(type(xp.asarray(x)))
  File "/home/user012/anaconda3/envs/GAN_znb/lib/python3.6/site-packages/cupy/creation/from_data.py", line 61, in asarray
    return core.array(a, dtype, False)
  File "cupy/core/core.pyx", line 2017, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2048, in cupy.core.core.array
ValueError: Unsupported dtype object

**Comment by suhaslohit** [comment]
@zhangxiaodi Were you able to fix this? I am seeing the same errors in the code I am using.Thanks.

**Comment by yfchen97** [comment]
> @zhangxiaodi Were you able to fix this? I am seeing the same errors in the code I am using.Thanks.
Were you able to fix this? I am seeing the same errors in the code I am using.Could you give me some advices?
