### ISSUE TITLE
Dtype of data and grad mismatch grad: float64 != data: float32

### ISSUE THREAD

**Issue by abusaadah** [chainer/chainer#6212]
Below is the forward and backward code:

```py
from chainer import function
from chainer.utils import type_check
from chainer import cuda
import numpy

def _as_mat(x):
    if x.ndim == 2:
        return x
    return x.reshape(len(x), -1)

class LinearFunction(function.Function):
    
    def check_type_forward(self, in_types):
        n_in = in_types.size()
        type_check.expect(2 <= n_in, n_in <= 3)
        x_type, w_type = in_types[:2]

        type_check.expect(
            x_type.dtype.kind == 'f',
            w_type.dtype.kind == 'f',
            x_type.ndim >= 2,
            w_type.ndim == 2,
            type_check.prod(x_type.shape[1:]) == w_type.shape[1],
        )
        if type_check.eval(n_in) == 3:
            b_type = in_types[2]
            type_check.expect(
                b_type.dtype == x_type.dtype,
                b_type.ndim == 1,
                b_type.shape[0] == w_type.shape[0],
            )

    def __init__(self, coeffs, bcoeffs=None, ocoeffs=None):
        self.coeffs = coeffs
        self.bcoeffs = bcoeffs
        self.ocoeffs = ocoeffs
        
    def forward(self, inputs):
        x = _as_mat(inputs[0])
        W = inputs[1]

        xp = cuda.get_array_module(*x)

        olen, ilen = W.shape
        if self.coeffs is None:
            self.coeffs = numpy.ones(ilen)
        coeffs = numpy.copy(self.coeffs)
        coeffs = numpy.expand_dims(coeffs, 0)        
        coeffs = numpy.broadcast_to(coeffs, W.shape)
        M = xp.asarray(coeffs,numpy.float32).reshape(W.shape)
        self.M = M
        W = self.M*W
        
        if not type_check.same_types(*inputs):
            raise ValueError('numpy and cupy must not be used together\n'
                             'type(W): {0}, type(x): {1}'
                             .format(type(W), type(x)))

        y = x.dot(W.T).astype(x.dtype, copy=False)
        if len(inputs) == 3:
            b = inputs[2]
            y += b
        return y,

    def backward(self, inputs, grad_outputs):
        x = _as_mat(inputs[0])
        W = inputs[1]
        
        if self.bcoeffs is not None:
            xp = cuda.get_array_module(*x)
            coeffs = numpy.copy(self.bcoeffs)
            coeffs = numpy.expand_dims(coeffs, 0)
            coeffs = numpy.broadcast_to(coeffs, W.shape)
            self.mW = xp.asarray(coeffs,numpy.float32).reshape(W.shape)
        if self.ocoeffs is not None:
            xp = cuda.get_array_module(*x)
            coeffs = numpy.copy(self.ocoeffs)
            self.mb = xp.asarray(coeffs,numpy.float32)

        W = self.mW * W
        gy = grad_outputs[0].

        if not type_check.same_types(*inputs):
            raise ValueError('numpy and cupy must not be used together\n'
                             'type(W): {0}, type(x): {1}'
                             .format(type(W), type(x)))

        gx = gy.dot(W).astype(x.dtype, copy = False).reshape(inputs[0].shape)
        gW = gy.T.dot(x).astype(W.dtype, copy = False)
        
        if hasattr(self,'mW'):
            gW = self.mW * gW
            if hasattr(self,'mb'):
                xp = cuda.get_array_module(*x)
                gW = xp.broadcast_to(xp.expand_dims(self.ocoeffs[0], 1),gW.shape) * gW
        # print('gW',gW.sum(0).sum(0))
        if len(inputs) == 3:
            gb = gy.sum(0)
            if hasattr(self,'mb'):
                gb = self.ocoeffs[0] * gb
            return gx, gW, gb
        else:
            return gx, gW

def linear(x, coeffs, W, b=None, bcoeffs=None, ocoeffs=None):
    
    if b is None:
        return LinearFunction(coeffs, bcoeffs=bcoeffs, ocoeffs=ocoeffs)(x, W)
    else:
        return LinearFunction(coeffs, bcoeffs=bcoeffs, ocoeffs=ocoeffs)(x, W, b)
```

When the model is run, the following error is returned:

```
Exception in main training loop: Function `<property object at 0x116e35098>` (LinearFunction) has a bug.

Please report this error to the issue tracker with the stack trace,
the information of your environment, and your script:
https://github.com/chainer/chainer/issues/new.
Dtype of data and grad mismatch
grad: float64 != data: float32
Traceback (most recent call last):
  File "/Users/Abdullahi/anaconda3/lib/python3.6/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/Users/Abdullahi/anaconda3/lib/python3.6/site-packages/chainer/training/updaters/standard_updater.py", line 149, in update
    self.update_core()
  File "/Users/Abdullahi/anaconda3/lib/python3.6/site-packages/chainer/training/updaters/standard_updater.py", line 160, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/Users/Abdullahi/anaconda3/lib/python3.6/site-packages/chainer/optimizer.py", line 655, in update
    loss.backward(loss_scale=self._loss_scale)
  File "/Users/Abdullahi/anaconda3/lib/python3.6/site-packages/chainer/variable.py", line 966, in backward
    self._backward_main(retain_grad, loss_scale)
  File "/Users/Abdullahi/anaconda3/lib/python3.6/site-packages/chainer/variable.py", line 1095, in _backward_main
    target_input_indexes, out_grad, in_grad)
  File "/Users/Abdullahi/anaconda3/lib/python3.6/site-packages/chainer/function_node.py", line 548, in backward_accumulate
    gxs = self.backward(target_input_indexes, grad_outputs)
  File "/Users/Abdullahi/anaconda3/lib/python3.6/site-packages/chainer/function.py", line 145, in backward
    variable._check_grad_type(self, x, gx)
  File "/Users/Abdullahi/anaconda3/lib/python3.6/site-packages/chainer/variable.py", line 53, in _check_grad_type
    raise typ(detail + msg)
Will finalize trainer extensions and updater before reraising the exception.
[JTraceback (most recent call last):
  File "/Users/Abdullahi/Documents/idp_detnet/examples/run_mlp.py", line 14, in <module>
    mlp.run(args)
  File "/Users/Abdullahi/Documents/idp_detnet/examples/mlp.py", line 37, in run
    util.load_or_train_model(model, train, test[i], args)
  File "/Users/Abdullahi/Documents/idp_detnet/examples/util.py", line 205, in load_or_train_model
    train_model(model, train, test, args)
  File "/Users/Abdullahi/Documents/idp_detnet/examples/util.py", line 179, in train_model
    trainer.run()
  File "/Users/Abdullahi/anaconda3/lib/python3.6/site-packages/chainer/training/trainer.py", line 330, in run
    six.reraise(*sys.exc_info())
  File "/Users/Abdullahi/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/Abdullahi/anaconda3/lib/python3.6/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/Users/Abdullahi/anaconda3/lib/python3.6/site-packages/chainer/training/updaters/standard_updater.py", line 149, in update
    self.update_core()
  File "/Users/Abdullahi/anaconda3/lib/python3.6/site-packages/chainer/training/updaters/standard_updater.py", line 160, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/Users/Abdullahi/anaconda3/lib/python3.6/site-packages/chainer/optimizer.py", line 655, in update
    loss.backward(loss_scale=self._loss_scale)
  File "/Users/Abdullahi/anaconda3/lib/python3.6/site-packages/chainer/variable.py", line 966, in backward
    self._backward_main(retain_grad, loss_scale)
  File "/Users/Abdullahi/anaconda3/lib/python3.6/site-packages/chainer/variable.py", line 1095, in _backward_main
    target_input_indexes, out_grad, in_grad)
  File "/Users/Abdullahi/anaconda3/lib/python3.6/site-packages/chainer/function_node.py", line 548, in backward_accumulate
    gxs = self.backward(target_input_indexes, grad_outputs)
  File "/Users/Abdullahi/anaconda3/lib/python3.6/site-packages/chainer/function.py", line 145, in backward
    variable._check_grad_type(self, x, gx)
  File "/Users/Abdullahi/anaconda3/lib/python3.6/site-packages/chainer/variable.py", line 53, in _check_grad_type
    raise typ(detail + msg)
TypeError: Function `<property object at 0x116e35098>` (LinearFunction) has a bug.

Please report this error to the issue tracker with the stack trace,
the information of your environment, and your script:
https://github.com/chainer/chainer/issues/new.
Dtype of data and grad mismatch
grad: float64 != data: float32
```

**Comment by niboshi** [comment]
The error message says there's a mismatch between gradients and inputs.
Please check the dtypes of `gx`, `gW` and `gb`, and confirm they match `x`, `W` and `b` respectively.

**Comment by abusaadah** [comment]
@niboshi gx, gW and gb are of the same dtypes (float32) as x, W, and b. The mismatch is pointing to the training loop, I couldn't figure out how. The same code worked for a multi-layer perceptron. I only modified the main model to do some signal processing for MIMO signal detection.

**Comment by fiarabbit** [comment]
@abusaadah No, the error message says `grad: float64 != data: float32`: i.e., the second argument of your `LinearFunction.backward` (`grad_outputs`) is float64, and it causes the error.

I guess that the succeeding links/functions after your `LinearFunction` modify the `dtype` of `Variable` (or just you put float64-array to `loss.grad`). Please check 1. the `loss.array.dtype` and 2. what happens when you set `loss.grad = np.ones(loss.shape, dtype=np.float32)` by yourself.

**Comment by abusaadah** [comment]
Hi Yuki,

Thank you for your amazing contribution. Do you mean I should change the
grad_outputs dtype to float64 right from the beginning?

Kind regards,
Abdullahi

**Comment by fiarabbit** [comment]
@abusaadah If you need more _help_ (rather than regarding this as a _bug_), I think we should move to StackOverflow because of the contribution guide.
In addition, full but minimal code to reproduce is necessary for the further investigation of the bug.

The code in the top of this issue does not include the declaration of the whole model, the loss, nor the dataset. At this moment, I cannot find the cause of the error.

**Comment by abusaadah** [comment]
Dear Yuki,

I have the code written in different files and import them as modules. If
you wouldn't mind, I can send you the entire folder. It's actually my
research project and it's been over four months now I'm trying to get it
work, but without success. I'm badly in need of help.

Thanks for your precious time.
Abdullahi

**Comment by fiarabbit** [comment]
IMO, you'd better close this issue and post a question to StackOverflow, because according to the [contribution guide](http://docs.chainer.org/en/stable/contribution.html), any general question is preferred to be raised at the StackOverflow with a `chainer` tag.
```
Warning

If you have a question on usages of Chainer, it is highly recommended to send a post to
StackOverflow or Chainer User Group instead of the issue tracker. The issue tracker is not a place
to share knowledge on practices. We may suggest these places and immediately close how-to
question issues.
```

**Comment by abusaadah** [comment]
Hi,

Thank you very much for your help and support.

Abdullahi

**Comment by abusaadah** [comment]
@niboshi gx, gW and gb are of the same dtypes (float32) as x, W, and b. The mismatch is pointing to the training loop, I couldn't figure out how. The same code worked for a multi-layer perceptron. I only modified the main model to do some signal processing for MIMO signal detection.
