### ISSUE TITLE
Cupy Compilation Error

### ISSUE THREAD

**Issue by ling-pan** [chainer/chainer#6525]
Hi, I am wondering why running with chainer encounters the following error about cupy:

  File "cupy/core/core.pyx", line 1689, in cupy.core.core.ndarray.__setitem__
  File "cupy/core/core.pyx", line 3599, in cupy.core.core._scatter_op
  File "cupy/core/_kernel.pyx", line 830, in cupy.core._kernel.ufunc.__call__
  File "cupy/util.pyx", line 50, in cupy.util.memoize.decorator.ret
  File "cupy/core/_kernel.pyx", line 619, in cupy.core._kernel._get_ufunc_kernel
  File "cupy/core/_kernel.pyx", line 51, in cupy.core._kernel._get_simple_elementwise_kernel
  File "cupy/core/carray.pxi", line 164, in cupy.core.core.compile_with_cache
  File "******/anaconda3/envs/chainerrl/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 164, in compile_with_cache
    ptx = compile_using_nvrtc(source, options, arch)
  File "******/anaconda3/envs/chainerrl/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 82, in compile_using_nvrtc
    ptx = prog.compile(options)
  File "******/anaconda3/envs/chainerrl/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 245, in compile
    raise CompileException(log, self.src, self.name, options)
cupy.cuda.compiler.CompileException: ******/anaconda3/envs/chainerrl/lib/python3.6/site-packages/cupy/core/include/cupy/carray.cuh(281): warning: statement is unreachable
          detected during instantiation of "void CIndexer<_ndim>::set(ptrdiff_t) [with _ndim=1]"
/tmp/tmpueticplp/kern.cu(11): here

/tmp/tmpueticplp/kern.cu(14): error: no suitable conversion function from "const in0_type" to "out0_type" exists

1 error detected in the compilation of "/tmp/tmpueticplp/kern.cu".

My info are as follows:
**Platform: Linux-3.10.0-957.1.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Chainer: 6.0.0b3
NumPy: 1.16.2
CuPy:
  CuPy Version          : 5.3.0
  CUDA Root             : /usr/local/cuda-8.0
  CUDA Build Version    : 8000
  CUDA Driver Version   : 10010
  CUDA Runtime Version  : 8000
  cuDNN Build Version   : 7102
  cuDNN Version         : 7102
  NCCL Build Version    : 2213
  NCCL Runtime Version  : (unknown)
iDeep: Not Available**

I have tried setting the path of cuda in ~/.bashrc, however, it does not work.

Thanks a lot for your help!

**Comment by fiarabbit** [comment]
Could you give some (short) reproduction code? Also, could you tell me how you installed `chainer` and `cupy`? Currently, `chainer` requires exactly the same version of `cupy`, i.e. `cupy==v6.0.0b3` for `cupy==v6.0.0b3`.

**Comment by ling-pan** [comment]
I noticed the warning that the version of cupy needs to match that of chainer. I have tried updating the version of cupy to be 6.0.0b3, but the problem still exists. I install chainer through the setup file in chainerrl ([https://github.com/chainer/chainerrl/blob/master/setup.py](url)).
I have tried some deepcopy in my code, and I am not sure whether this incurs the error.

**Comment by ling-pan** [comment]
I install chainer from the setup file in chainerrl [(https://github.com/chainer/chainerrl/blob/master/setup.py)](url).
I have tried up updating cupy to version 6.0.0b3 as below:
Platform: Linux-3.10.0-957.1.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Chainer: 6.0.0b3
NumPy: 1.16.2
CuPy:
CuPy Version : 6.0.0b3
CUDA Root : /usr/local/cuda-8.0
CUDA Build Version : 8000
CUDA Driver Version : 10010
CUDA Runtime Version : 8000
cuDNN Build Version : 6021
cuDNN Version : 6021
NCCL Build Version : 2213
NCCL Runtime Version : (unknown)
iDeep: Not Available

However, the code can't run normally with the following error:
File "******/anaconda3/envs/chainerrl/lib/python3.6/site-packages/cupy/creation/basic.py", line 205, in zeros_like
order, strides, memptr = _new_like_order_and_strides(a, dtype, order)
File "******/anaconda3/envs/chainerrl/lib/python3.6/site-packages/cupy/creation/basic.py", line 35, in _new_like_order_and_strides
order = chr(_update_order_char(a, ord(order)))
TypeError: Argument 'x' has incorrect type (expected cupy.core.core.ndarray, got numpy.ndarray)

**Comment by fiarabbit** [comment]
> Could you give some (short) reproduction code?
How about this?  The error you got 

i.e.
```error.py
File "******/anaconda3/envs/chainerrl/lib/python3.6/site-packages/cupy/creation/basic.py", line 205, in zeros_like
order, strides, memptr = _new_like_order_and_strides(a, dtype, order)
File "******/anaconda3/envs/chainerrl/lib/python3.6/site-packages/cupy/creation/basic.py", line 35, in _new_like_order_and_strides
order = chr(_update_order_char(a, ord(order)))
```

tells `cupy` works fine according to its specification. In other words, the error seems to be triggered by the code you run.

**Comment by ling-pan** [comment]
Thanks for your reply. I tried running the code without using gpu, and I use cpu only. In this case, the code runs normally. I guess maybe it is not triggered by my code?

**Comment by fiarabbit** [comment]
@ling-pan No, it is not. It depends on your code.

For example,
```example.py
import numpy, cupy

mydata = numpy.empty((3,), dtype='f')

gpu = True
if not gpu:
    xp = numpy
else:
    xp = cupy

mydata_like = xp.zeros_like(mydata)
```

This code works fine when `gpu==False`, but this code fails with the same error to yours when `gpu==True`.

```stacktrace.py
Traceback (most recent call last):
  File "fuga.py", line 11, in <module>
    mydata_like = xp.zeros_like(mydata)
  File "/home/hashimoto/.local/source/cupy/cupy/creation/basic.py", line 205, in zeros_like
    order, strides, memptr = _new_like_order_and_strides(a, dtype, order)
  File "/home/hashimoto/.local/source/cupy/cupy/creation/basic.py", line 35, in _new_like_order_and_strides
    order = chr(_update_order_char(a, ord(order)))
TypeError: Argument 'x' has incorrect type (expected cupy.core.core.ndarray, got numpy.ndarray)
```

In the conventional use-case, your data is read as `numpy.ndarray`, so this mis-match between `numpy` and `cupy`  happens (especially when you do not follow chainer-like implementation). For the further help, chainer-slack will be more useful rather than discussion in this issue.

**Comment by ling-pan** [comment]
Thanks a lot! I will look deeper and check chainer-slack!

**Comment by kmaehashi** [comment]
This issue sounds specific to CuPy, not Chainer.
Let's continue discussion here https://github.com/cupy/cupy/issues/2100, or use Chainer slack.
