### ISSUE TITLE
cupy.cuda.runtime.CUDARuntimeError: cudaErrorNoDevice: no CUDA-capable device is detected

### ISSUE THREAD

**Issue by harshalcse** [chainer/chainer#6596]
I am using AWS p3 type 2xlarge instance type with following GPU details:
root@awsml04:~# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
![nvidia-smi](https://user-images.githubusercontent.com/5838252/54760928-157d4200-4c17-11e9-80be-fa51ec76e9ed.PNG)

* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
  - CuPy version
    cupy==5.3.0
  - OS/Platform
   Ubuntu 16.04 x86_64
  - CUDA version 
    CUDA 9.0
  - cuDNN version: 7.3.1
  -NCCL version:  2.3.5 
* Code to reproduce
* Error messages, stack traces, or logs : 

```
Exception in main training loop: cudaErrorNoDevice: no CUDA-capable device is detected
Traceback (most recent call last):
  File "/root/.see-master/lib/python3.5/site-packages/chainer/training/trainer.py", line 302, in run
    entry.extension(self)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/.see-master/lib/python3.5/site-packages/chainer/reporter.py", line 98, in scope
    yield
  File "/root/.see-master/lib/python3.5/site-packages/chainer/training/trainer.py", line 299, in run
    update()
  File "/root/.see-master/lib/python3.5/site-packages/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/root/.see-master/lib/python3.5/site-packages/chainer/training/updaters/multiprocess_parallel_updater.py", line 195, in update_core
    self.setup_workers()
  File "/root/.see-master/lib/python3.5/site-packages/chainer/training/updaters/multiprocess_parallel_updater.py", line 186, in setup_workers
    with cuda.Device(self._devices[0]):
  File "cupy/cuda/device.pyx", line 106, in cupy.cuda.device.Device.__enter__
  File "cupy/cuda/runtime.pyx", line 164, in cupy.cuda.runtime.getDevice
  File "cupy/cuda/runtime.pyx", line 136, in cupy.cuda.runtime.check_status
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "chainer/train_svhn.py", line 258, in <module>
    trainer.run()
  File "/root/.see-master/lib/python3.5/site-packages/chainer/training/trainer.py", line 313, in run
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/root/.see-master/lib/python3.5/site-packages/chainer/training/trainer.py", line 302, in run
    entry.extension(self)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/.see-master/lib/python3.5/site-packages/chainer/reporter.py", line 98, in scope
    yield
  File "/root/.see-master/lib/python3.5/site-packages/chainer/training/trainer.py", line 299, in run
    update()
  File "/root/.see-master/lib/python3.5/site-packages/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/root/.see-master/lib/python3.5/site-packages/chainer/training/updaters/multiprocess_parallel_updater.py", line 195, in update_core
    self.setup_workers()
  File "/root/.see-master/lib/python3.5/site-packages/chainer/training/updaters/multiprocess_parallel_updater.py", line 186, in setup_workers
    with cuda.Device(self._devices[0]):
  File "cupy/cuda/device.pyx", line 106, in cupy.cuda.device.Device.__enter__
  File "cupy/cuda/runtime.pyx", line 164, in cupy.cuda.runtime.getDevice
  File "cupy/cuda/runtime.pyx", line 136, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorNoDevice: no CUDA-capable device is detected

```

**Comment by crcrpar** [comment]
Could you check the number of GPUs your instance have?

The reason I ask this is that [MultiprocessParallelUpdater](https://docs.chainer.org/en/stable/reference/generated/chainer.training.updaters.MultiprocessParallelUpdater.html#chainer-training-updaters-multiprocessparallelupdater) assumes that a machine has multiple GPUs.

> This is an implementation of Updater that uses multiple GPUs with multi-process data parallelism. It uses Nvidia NCCL for communication between multiple GPUs.

**Comment by fiarabbit** [comment]
@crcrpar Doesn't `MultiprocessParallelUpdater` work with a single GPU?

**Comment by harshalcse** [comment]
@crcrpar @fiarabbit please suggest exact workaround ? Is it ok to use `singleProcessUpdate` ?

**Comment by fiarabbit** [comment]
@harshalcse It is impossible to suggest the _exact_ workaround, because we cannot access your environment. (and there is `singleProcessUpdater`).

I'm `YukiHashimoto`, who watches your StackOverflowQuestion.

First, you should be aware that your recognition about your environment differs from the reality. You do not link `cupy` to `cuDNN`, as the warning suggested. In SO, you said that you intend to use `python3`, but in the script above you do not specify the version of python. We cannot disentangle the cause of the error if the execution python differs case by case. (The very important thing is that `python` means `python2` by default in Ubuntu 16.04.)

Second, I think the cause of your trouble is the wrong `LD_LIBRARY_PATH`. The following is cited from SO.
```hoge.sh
# echo $LD_LIBRARY_PATH
/usr/local/cuda/lib64{LD_LIBRARY_PATH:+:/usr/local/cuda-9.0/lib64:/usr/local/cuda/lib64{LD_LIBRARY_PATH:+:/usr/lib64/openmpi/lib/:/usr/local/cuda/lib64:/usr/local/lib:/usr/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/mpi/lib:/lib/:}}
```
As you can see, the `LD_LIBRARY_PATH` is not a path nor a path list.

Finally, the execution user is a little bit troublesome. The citation above suggests that you run your script as `root`. However, generally it is not recommended to use `su` to run a script, because changing user cause unintentional collapse of environment variables as well as the security issue. If there is a special reason, the information should be given.

**Comment by kmaehashi** [comment]
@harshalcse Could you please avoid multi-posting questions? It makes difficult for us to track the issue.

* https://github.com/cupy/cupy/issues/2106
* https://stackoverflow.com/questions/55218824/cuda-runtime-error-cudaerrornodevice-no-cuda-capable-device-is-detected
* https://groups.google.com/forum/#!msg/cupy/0jJ-Gc39gTQ/lQmoLrC6CwAJ
* https://groups.google.com/d/msg/cupy-ja/8fIUd9Bg0gk/NsItKmm8AAAJ
* https://github.com/Bartzi/see/issues/65#issuecomment-475189053

If you are not familiar with CUDA installation, I'd suggest you to start with Deep Learning AMI provided by AWS, which provides pre-installed Chainer that works out-of-box.
https://docs.aws.amazon.com/dlami/latest/devguide/gs.html

**Comment by harshalcse** [comment]
@kmaehashi I already used Deep Learing AMI which having preinstalled all Deep Learning Frameworks .

**Comment by fiarabbit** [comment]
@harshalcse 
According to the [contribution guide](http://docs.chainer.org/en/stable/contribution.html), any general question is preferred to be raised at the StackOverflow with a `chainer` tag. In other words, this issue (and also the question currently raised in SO) should also be closed.

```
Warning

If you have a question on usages of Chainer, it is highly recommended to send a post to
StackOverflow or Chainer User Group instead of the issue tracker. The issue tracker is not a place
to share knowledge on practices. We may suggest these places and immediately close how-to
question issues.
```

Also, please use code block (quotes with "\`\`\` \`\`\`") instead of quotation (quotes with ">") for the stack  trace.

**Comment by harshalcse** [comment]
@fiarabbit please provide link for chainer user group so that I will post my questions there?

**Comment by fiarabbit** [comment]
@harshalcse https://groups.google.com/forum/#!forum/chainer
You can find this link (and other helpful link) at https://github.com/chainer/chainer (https://github.com/chainer/chainer/blob/master/README.md)
