### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'isenabled'

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#6720]
https://jenkins.preferred.jp/job/chainer/job/chainer_pr/119/TEST=CHAINERX_chainer-py3,label=mn1-p100/console

```
14:32:34 Traceback (most recent call last):
14:32:34   File "cupy/cuda/memory.pyx", line 597, in cupy.cuda.memory.PooledMemory.free
14:32:34   File "cupy/cuda/memory.pyx", line 969, in cupy.cuda.memory.SingleDeviceMemoryPool.free
14:32:34   File "cupy/cuda/memory.pyx", line 791, in cupy.cuda.memory.LockAndNoGc.__enter__
14:32:34 AttributeError: 'NoneType' object has no attribute 'isenabled'
14:32:34 Exception ignored in: 'cupy.cuda.memory.PooledMemory.__dealloc__'
14:32:34 Traceback (most recent call last):
14:32:34   File "cupy/cuda/memory.pyx", line 597, in cupy.cuda.memory.PooledMemory.free
14:32:34   File "cupy/cuda/memory.pyx", line 969, in cupy.cuda.memory.SingleDeviceMemoryPool.free
14:32:34   File "cupy/cuda/memory.pyx", line 791, in cupy.cuda.memory.LockAndNoGc.__enter__
14:32:34 AttributeError: 'NoneType' object has no attribute 'isenabled'
14:32:34 Traceback (most recent call last):
14:32:34   File "cupy/cuda/memory.pyx", line 597, in cupy.cuda.memory.PooledMemory.free
14:32:34   File "cupy/cuda/memory.pyx", line 969, in cupy.cuda.memory.SingleDeviceMemoryPool.free
14:32:34   File "cupy/cuda/memory.pyx", line 791, in cupy.cuda.memory.LockAndNoGc.__enter__
14:32:34 AttributeError: 'NoneType' object has no attribute 'isenabled'
14:32:34 Exception ignored in: 'cupy.cuda.memory.PooledMemory.__dealloc__'
14:32:34 Traceback (most recent call last):
14:32:34   File "cupy/cuda/memory.pyx", line 597, in cupy.cuda.memory.PooledMemory.free
14:32:34   File "cupy/cuda/memory.pyx", line 969, in cupy.cuda.memory.SingleDeviceMemoryPool.free
14:32:34   File "cupy/cuda/memory.pyx", line 791, in cupy.cuda.memory.LockAndNoGc.__enter__
14:32:34 AttributeError: 'NoneType' object has no attribute 'isenabled'
14:32:34 Traceback (most recent call last):
14:32:34   File "cupy/cuda/memory.pyx", line 597, in cupy.cuda.memory.PooledMemory.free
14:32:34   File "cupy/cuda/memory.pyx", line 969, in cupy.cuda.memory.SingleDeviceMemoryPool.free
14:32:34   File "cupy/cuda/memory.pyx", line 791, in cupy.cuda.memory.LockAndNoGc.__enter__
14:32:34 AttributeError: 'NoneType' object has no attribute 'isenabled'
14:32:34 Exception ignored in: 'cupy.cuda.memory.PooledMemory.__dealloc__'
14:32:34 Traceback (most recent call last):
14:32:34   File "cupy/cuda/memory.pyx", line 597, in cupy.cuda.memory.PooledMemory.free
14:32:34   File "cupy/cuda/memory.pyx", line 969, in cupy.cuda.memory.SingleDeviceMemoryPool.free
14:32:34   File "cupy/cuda/memory.pyx", line 791, in cupy.cuda.memory.LockAndNoGc.__enter__
14:32:34 AttributeError: 'NoneType' object has no attribute 'isenabled'
14:32:34 Traceback (most recent call last):
14:32:34   File "cupy/cuda/memory.pyx", line 597, in cupy.cuda.memory.PooledMemory.free
14:32:34   File "cupy/cuda/memory.pyx", line 969, in cupy.cuda.memory.SingleDeviceMemoryPool.free
14:32:34   File "cupy/cuda/memory.pyx", line 791, in cupy.cuda.memory.LockAndNoGc.__enter__
14:32:34 AttributeError: 'NoneType' object has no attribute 'isenabled'
14:32:34 Exception ignored in: 'cupy.cuda.memory.PooledMemory.__dealloc__'
14:32:34 Traceback (most recent call last):
14:32:34   File "cupy/cuda/memory.pyx", line 597, in cupy.cuda.memory.PooledMemory.free
14:32:34   File "cupy/cuda/memory.pyx", line 969, in cupy.cuda.memory.SingleDeviceMemoryPool.free
14:32:34   File "cupy/cuda/memory.pyx", line 791, in cupy.cuda.memory.LockAndNoGc.__enter__
14:32:34 AttributeError: 'NoneType' object has no attribute 'isenabled'
```

**Comment by kmaehashi** [comment]
I think the docker image needs to be recreated.
https://github.com/cupy/cupy/pull/2116
