### ISSUE TITLE
`test_batch_renormalization` is flaky

### ISSUE THREAD

**Issue by imos** [chainer/chainer#6910]
This is part of https://github.com/chainer/chainer/issues/6903 effort.

- Failure example:  https://ci.preferred.jp/chainer.py37/2214/
- Failure test case: `BatchRenormalizationTest_param_21_{dtype=float64, ndim=2, test=False}.test_forward_multi_gpu`
- Tolerance:
```
E   Not equal to tolerance rtol=0.001, atol=0.0001
E   
E   Mismatch: 6.67%
E   Max absolute difference: 0.00052644
E   Max relative difference: 0.00564455
```

**Comment by imos** [comment]
@toslunar Friendly ping.

**Comment by imos** [comment]
@toslunar Friendly ping.

**Comment by toslunar** [comment]
#7202 will partially address the issue.

**Comment by toslunar** [comment]
I reproduced test failures after #7202 is merged.

**Comment by niboshi** [comment]
https://jenkins.preferred.jp/job/chainer/job/chainer_pr/1839/TEST=chainer-py3,label=mn1-p100/console

>`FAIL tests/chainer_tests/links_tests/normalization_tests/test_batch_renormalization.py::BatchRenormalizationTest_param_11_{dtype=float32, ndim=1, test=False}::test_forward_gpu`

```
18:07:41 _ BatchRenormalizationTest_param_11_{dtype=float32, ndim=1, test=False}.test_forward_gpu _
18:07:41 chainer/testing/parameterized.py:89: in new_method
18:07:41     utils._raise_from(e.__class__, s.getvalue(), e)
18:07:41 chainer/utils/__init__.py:106: in _raise_from
18:07:41     six.raise_from(new_exc.with_traceback(orig_exc.__traceback__), None)
18:07:41 chainer/testing/parameterized.py:78: in new_method
18:07:41     return base_method(self, *args, **kwargs)
18:07:41 chainer/testing/condition.py:80: in wrapper
18:07:41     fail()
18:07:41 chainer/testing/condition.py:51: in fail
18:07:41     instance.fail(msg)
18:07:41 E   AssertionError: Parameterized test failed.
18:07:41 E   
18:07:41 E   Base test method: BatchRenormalizationTest.test_forward_gpu
18:07:41 E   Test parameters:
18:07:41 E     dtype: <class 'numpy.float32'>
18:07:41 E     ndim: 1
18:07:41 E     test: False
18:07:41 E   
18:07:41 E   
18:07:41 E   (caused by)
18:07:41 E   AssertionError: 
18:07:41 E   Fail: 3, Success: 0
18:07:41 E   
18:07:41 E   The first error message:
18:07:41 E   Traceback (most recent call last):
18:07:41 E     File "/work/chainer/chainer/testing/array.py", line 27, in assert_allclose
18:07:41 E       x, y, atol=atol, rtol=rtol, verbose=verbose)
18:07:41 E     File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1510, in assert_allclose
18:07:41 E       verbose=verbose, header=header, equal_nan=equal_nan)
18:07:41 E     File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 836, in assert_array_compare
18:07:41 E       raise AssertionError(msg)
18:07:41 E   AssertionError: 
18:07:41 E   Not equal to tolerance rtol=0.001, atol=0.0001
18:07:41 E   
18:07:41 E   Mismatch: 3.33%
18:07:41 E   Max absolute difference: 0.00054932
18:07:41 E   Max relative difference: 0.00133648
18:07:41 E    x: array([[[-2.084918,  0.409576],
18:07:41 E           [-0.363258, -0.557226],
18:07:41 E           [ 1.296712,  5.226429]],...
18:07:41 E    y: array([[[-2.08488 ,  0.409581],
18:07:41 E           [-0.363256, -0.557228],
18:07:41 E           [ 1.296163,  5.22588 ]],...
18:07:41 E   
18:07:41 E   During handling of the above exception, another exception occurred:
18:07:41 E   
18:07:41 E   Traceback (most recent call last):
18:07:41 E     File "/work/chainer/chainer/testing/condition.py", line 60, in <lambda>
18:07:41 E       lambda: f(ins, *args[1:], **kwargs),
18:07:41 E     File "/work/chainer/tests/chainer_tests/links_tests/normalization_tests/test_batch_renormalization.py", line 107, in test_forward_gpu
18:07:41 E       self.check_forward(cuda.to_gpu(self.x))
18:07:41 E     File "/work/chainer/tests/chainer_tests/links_tests/normalization_tests/test_batch_renormalization.py", line 97, in check_forward
18:07:41 E       y_expect, y.data, **self.check_forward_optionss)
18:07:41 E     File "/work/chainer/chainer/testing/array.py", line 68, in assert_allclose
18:07:41 E       raise AssertionError(f.getvalue())
18:07:41 E   AssertionError: 
18:07:41 E   Not equal to tolerance rtol=0.001, atol=0.0001
18:07:41 E   
18:07:41 E   Mismatch: 3.33%
18:07:41 E   Max absolute difference: 0.00054932
18:07:41 E   Max relative difference: 0.00133648
18:07:41 E    x: array([[[-2.084918,  0.409576],
18:07:41 E           [-0.363258, -0.557226],
18:07:41 E           [ 1.296712,  5.226429]],...
18:07:41 E    y: array([[[-2.08488 ,  0.409581],
18:07:41 E           [-0.363256, -0.557228],
18:07:41 E           [ 1.296163,  5.22588 ]],...
18:07:41 E   
18:07:41 E   assert_allclose failed: 
18:07:41 E     shape: (5, 3, 2) (5, 3, 2)
18:07:41 E     dtype: float32 float32
18:07:41 E     i: (2, 2, 1)
18:07:41 E     x[i]: 0.41107428073883057
18:07:41 E     y[i]: 0.4105256199836731
18:07:41 E     relative error[i]: 0.0013364836340770125
18:07:41 E     absolute error[i]: 0.0005486607551574707
18:07:41 E     relative tolerance * |y[i]|: 0.0004105256199836731
18:07:41 E     absolute tolerance: 0.0001
18:07:41 E     total tolerance: 0.0005105256199836731
18:07:41 E   x: [[[-2.0849183   0.40957627]
18:07:41 E        [-0.36325765 -0.55722564]
18:07:41 E        [ 1.2967116   5.226429  ]]
18:07:41 E   
18:07:41 E       [[-0.7658379   0.07419053]
18:07:41 E        [ 0.7500052  -0.47575486]
18:07:41 E        [ 1.0481513   1.7667365 ]]
18:07:41 E   
18:07:41 E       [[ 0.08743405 -0.93879426]
18:07:41 E        [ 0.2873434  -0.38592124]
18:07:41 E        [ 4.483272    0.41107428]]
18:07:41 E   
18:07:41 E       [[-1.8458759  -0.68705523]
18:07:41 E        [ 0.304021    0.8170537 ]
18:07:41 E        [ 1.0541122   2.3461757 ]]
18:07:41 E   
18:07:41 E       [[-2.0749302  -0.50755703]
18:07:41 E        [-0.01045106 -0.35363   ]
18:07:41 E        [ 0.8636067   5.171902  ]]]
18:07:41 E   y: [[[-2.08488     0.40958092]
18:07:41 E        [-0.3632562  -0.5572276 ]
18:07:41 E        [ 1.296163    5.2258797 ]]
18:07:41 E   
18:07:41 E       [[-0.76581746  0.07419983]
18:07:41 E        [ 0.7500259  -0.47575536]
18:07:41 E        [ 1.0476025   1.7661879 ]]
18:07:41 E   
18:07:41 E       [[ 0.08744311 -0.9387715 ]
18:07:41 E        [ 0.28735608 -0.38592023]
18:07:41 E        [ 4.482723    0.41052562]]
18:07:41 E   
18:07:41 E       [[-1.845841   -0.6870359 ]
18:07:41 E        [ 0.30403394  0.81707555]
18:07:41 E        [ 1.0535635   2.345627  ]]
18:07:41 E   
18:07:41 E       [[-2.0748923  -0.50754005]
18:07:41 E        [-0.01044352 -0.35362846]
18:07:41 E        [ 0.86305803  5.1713533 ]]]
```

**Comment by niboshi** [comment]
https://jenkins.preferred.jp/job/chainer/job/chainer_pr/1876/TEST=CHAINERX_chainer-py3,label=mn1-p100/console

>`12:48:52 FAIL ../../repo/tests/chainer_tests/links_tests/normalization_tests/test_batch_renormalization.py::BatchRenormalizationTest_param_13_{dtype=float32, ndim=2, test=False}::test_forward_gpu`

**Comment by niboshi** [comment]
https://travis-ci.org/chainer/chainer/jobs/574189720

>`FAIL tests/chainer_tests/links_tests/normalization_tests/test_batch_renormalization.py::BatchRenormalizationTest_param_11_{ndim=1, test=False, dtype=float32}::test_forward_cpu`

```
E   assert_allclose failed: 
E     shape: (5, 3, 2) (5, 3, 2)
E     dtype: float32 float32
E     i: (1, 1, 0)
E     x[i]: 0.024260878562927246
E     y[i]: 0.024406611919403076
E     relative error[i]: 0.00597106060013175
E     absolute error[i]: 0.00014573335647583008
E     relative tolerance * |y[i]|: 2.4406611919403078e-05
E     absolute tolerance: 0.0001
E     total tolerance: 0.0001244066119194031
```

**Comment by niboshi** [comment]
https://jenkins.preferred.jp/job/chainer/job/chainer_pr/1883/TEST=chainer-py2,label=mn1-p100/console

>`14:28:36 FAIL tests/chainer_tests/links_tests/normalization_tests/test_batch_renormalization.py::BatchRenormalizationTest_param_13_{ndim=2, dtype=float32, test=False}::test_forward_gpu`

```
14:28:36 E   assert_allclose failed: 
14:28:36 E     shape: (5, 3, 2, 2) (5, 3, 2, 2)
14:28:36 E     dtype: float32 float32
14:28:36 E     i: (4, 2, 1, 0)
14:28:36 E     x[i]: -0.239266812801
14:28:36 E     y[i]: -0.240412011743
14:28:36 E     relative error[i]: 0.00476348493248
14:28:36 E     absolute error[i]: 0.00114519894123
14:28:36 E     relative tolerance * |y[i]|: 0.000240412011743
14:28:36 E     absolute tolerance: 0.0001
14:28:36 E     total tolerance: 0.000340412011743
```

**Comment by niboshi** [comment]
https://jenkins.preferred.jp/job/chainer/job/chainer_pr/2139/TEST=chainer-py2,label=mn1-p100/console

Occurred in #8198

```
17:05:44 FAIL tests/chainer_tests/links_tests/normalization_tests/test_batch_renormalization.py::BatchRenormalizationTest_param_21_{dtype=float64, ndim=2, test=False}::test_forward_gpu
17:05:44 FAIL tests/chainer_tests/links_tests/normalization_tests/test_batch_renormalization.py::BatchRenormalizationTest_param_23_{dtype=float64, ndim=3, test=False}::test_forward_cpu
```

Backport needed?

**Comment by niboshi** [comment]
@Crissman

**Comment by niboshi** [comment]
Backport PR: https://github.com/chainer/chainer/pull/8200

**Comment by niboshi** [comment]
Failure not replicated in the current v6 (52e7d1e28be831bb91a9c194c17f2e01c7091e55) in 100,000 trials in each of the following tests.

`tests/chainer_tests/links_tests/normalization_tests/test_batch_renormalization.py::BatchRenormalizationTest_param_39_{dtype=float64, eps=2e-05, ndim=3, test=False}::test_forward_cpu`

`tests/chainer_tests/links_tests/normalization_tests/test_batch_renormalization.py::BatchRenormalizationTest_param_47_{dtype=float64, eps=0.5, ndim=3, test=False}::test_forward_cpu`
