### ISSUE TITLE
ChainerMN's naive communicator does not work with cupy master

### ISSUE THREAD

**Issue by Hakuyume** [chainer/chainer#6925]
```
$ pip3 install \
    'git+https://github.com/chainer/chainer.git@1e3b666#egg=chainer' \
    'git+https://github.com/cupy/cupy.git@690997a#egg=cupy'
$ python3 -c 'import chainermn; chainermn.create_communicator("naive")'
Traceback (most recent call last):                                                                                    
  File "<string>", line 1, in <module>                                                                                
  File "/usr/local/lib/python3.6/dist-packages/chainermn/communicators/__init__.py", line 98, in create_communicator  
    from chainermn.communicators.naive_communicator \                                                                 
  File "/usr/local/lib/python3.6/dist-packages/chainermn/communicators/naive_communicator.py", line 1, in <module>    
    from chainermn.communicators import _memory_utility                                                               
  File "/usr/local/lib/python3.6/dist-packages/chainermn/communicators/_memory_utility.py", line 8, in <module>       
    import cupy as cp                                                                                                 
  File "/usr/local/lib/python3.6/dist-packages/cupy/__init__.py", line 11, in <module>                                
    from cupy import core  # NOQA                                                                                     
  File "/usr/local/lib/python3.6/dist-packages/cupy/core/__init__.py", line 1, in <module>                            
    from cupy.core import core  # NOQA                                                                                
  File "cupy/core/carray.pxi", line 50, in init cupy.core.core                                                        
AttributeError: type object 'cupy.core.core.Indexer' has no attribute '__reduce_cython__'
```

The following `Dockerfile` can reproduce this error.
```dockerfile
FROM nvidia/cuda:9.2-cudnn7-devel-ubuntu18.04

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    git \
    make \
    openssh-client \
    python3-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN curl -LO https://bootstrap.pypa.io/get-pip.py \
    && python3 get-pip.py --no-cache-dir \
    && rm get-pip.py

ENV OPENMPI_VERSION=3.0.1
RUN cd $(mktemp -d) \
    && curl -L https://www.open-mpi.org/software/ompi/v${OPENMPI_VERSION%.*}/downloads/openmpi-${OPENMPI_VERSION}.tar.bz2 | tar jxf - \
    && cd openmpi-${OPENMPI_VERSION} \
    && ./configure --with-cuda \
    && make -j $(nproc) \
    && make install \
    && cd - \
    && rm -rf $(pwd)

RUN echo /usr/local/lib/ > /etc/ld.so.conf.d/local.conf && ldconfig

RUN pip3 install --no-cache-dir \
    cython \
    mpi4py \
    'git+https://github.com/chainer/chainer.git@1e3b666#egg=chainer' \
    'git+https://github.com/cupy/cupy.git@690997a#egg=cupy'

RUN python3 -c 'import chainermn; chainermn.create_communicator("naive")'
```

**Comment by Hakuyume** [comment]
I could reproduce this error without chainer/chainermn.

**Comment by Hakuyume** [comment]
FYI: https://github.com/cupy/cupy/issues/2148
