### ISSUE TITLE
Cannot install chainer 1.5.0.2 from source

### ISSUE THREAD

**Issue by tscohen** [chainer/chainer#703]
I uninstalled chainer using "pip uninstall chainer", because of issue #702. When I try to install the latest version from source I get the following error:

```
Tacos-MacBook-Pro:chainer tsc$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 88, in <module>
    'build_ext': chainer_setup_build.chainer_build_ext,
  File "/Users/tsc/anaconda/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/Users/tsc/anaconda/lib/python2.7/site-packages/distribute-0.6.38-py2.7.egg/setuptools/dist.py", line 225, in __init__
    _Distribution.__init__(self,attrs)
  File "/Users/tsc/anaconda/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/Users/tsc/anaconda/lib/python2.7/site-packages/distribute-0.6.38-py2.7.egg/setuptools/dist.py", line 257, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/Users/tsc/anaconda/lib/python2.7/site-packages/distribute-0.6.38-py2.7.egg/pkg_resources.py", line 2027, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "/Users/tsc/anaconda/lib/python2.7/site-packages/distribute-0.6.38-py2.7.egg/pkg_resources.py", line 2237, in requires
    dm = self._dep_map
  File "/Users/tsc/anaconda/lib/python2.7/site-packages/distribute-0.6.38-py2.7.egg/pkg_resources.py", line 2466, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/Users/tsc/anaconda/lib/python2.7/site-packages/distribute-0.6.38-py2.7.egg/pkg_resources.py", line 2499, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/Users/tsc/anaconda/lib/python2.7/site-packages/distribute-0.6.38-py2.7.egg/pkg_resources.py", line 2496, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File "/Users/tsc/anaconda/lib/python2.7/site-packages/distribute-0.6.38-py2.7.egg/_markerlib/markers.py", line 109, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'sys_platform' is not defined
```

**Comment by unnonouno** [comment]
Humm, I haven't seen this error message. Which version of `setuptools` and `pip` do you use?
You can check `setuptools` like this:
```
$ python
>>> import setuptools
>>> setuptools.__version__
'18.5'
```
And, `pip`:
```
$ pip --version
pip 7.1.2 from ...
```

**Comment by tscohen** [comment]
I was running setuptools version 0.6 and pip version 7.1.2. After upgrading setuptools using "easy_install -U setuptools" the installation works. So that resolves this issue. Perhaps we should list this as a requirement? Or is it possible to automatically update setuptools during the installation process, if necessary?

My current installation does still suffer from issue #702.

**Comment by delta2323** [comment]
[This comment](http://stackoverflow.com/a/30739613) says update of distribute resolves the same error, although it is not certain that the fundamental reason is same. Since distribute is merged to setuptools (as far as I know), so I suspect the problem was the version of setuptools.

**Comment by unnonouno** [comment]
OK. We first need to investigate minimal required versions. If automatic update is possible, we fix setup.py to use it.

**Comment by delta2323** [comment]
Closed, as we do not support version 1 any longer. Please create a new issue if you encounter the same problem with newer versions. Thank you.
