### ISSUE TITLE
[Bug] ValueError: Function `...` (BernoulliLogProb) has a bug.

### ISSUE THREAD

**Issue by seiyab** [chainer/chainer#7057]
## Overview
When I calculate a gradient of `log_prob` of Bernoulli distribution, I got error message `(BernoulliLogProb) has a bug.`.

## Conditions
  - Chainer version ... 6.0.0rc1 
  - CuPy version ... I don't use CuPy.
  - Numpy version ... 1.16.2
  - OS/Platform Linux-4.9.125-linuxkit-x86_64-with-Ubuntu-18.04-bionic
  - CUDA/cuDNN version ... I don't use CUDA/cuDNN.

## Code to reproduce
```
import numpy as np
import chainer as ch
from chainer import distributions as dist
from chainer import functions as F

param_p = ch.Parameter(np.array(0.5))
bernoulli = dist.Bernoulli(param_p)
samples = F.cast(bernoulli.sample((10,)), np.float)
loss = np.sum(bernoulli.log_prob(samples))
loss.backward()
```
## Error messages, stack traces, or logs
```
Traceback (most recent call last):          
  File "bernoulli_bag.py", line 10, in <module>                                          
    loss.backward()   
  File "/usr/local/lib/python3.6/dist-packages/chainer/variable.py", line 1433, in backward
    _backprop_to_all([(node, grad_var)], retain_grad, loss_scale)                        
  File "/usr/local/lib/python3.6/dist-packages/chainer/variable.py", line 1667, in _backprop_to_all
    _check_grad_type(func, x, True, gx_elem.array)                                       
  File "/usr/local/lib/python3.6/dist-packages/chainer/variable.py", line 83, in _check_grad_type
    raise typ(detail + msg)                 
ValueError: Function `<property object at 0x7f592daf4a98>` (BernoulliLogProb) has a bug. 

Please report this error to the issue tracker with the stack trace,                      
the information of your environment, and your script:                                    
https://github.com/chainer/chainer/issues/new.                                           
Shape of data and grad mismatch             
grad: (10,) != data: ()  
```

**Comment by seiyab** [comment]
I'll send a pull request.
