### ISSUE TITLE
`link.to_cpu()` from chainerx array fails when `link` has state variables with gradient

### ISSUE THREAD

**Issue by corochann** [chainer/chainer#7310]
Testing under chainer==6.0.0 with chainerx built and cupy installed.
Testing environment has only 1 GPU.

Code to reproduce:
```
import numpy as np

import chainer
import chainer.links as L


# device = chainer.get_device(0)  # When using cupy, below code works.
device = chainer.get_device('native')

gru = L.GRU(10, 1)
gru.to_device(device)

x = np.zeros((1, 10), dtype=np.float32)
x = device.send(x)
y = gru(x)

# gru.reset_state()
gru.to_cpu()  # This cause ERROR 
print('done!')
```

which raises following error:
```
Traceback (most recent call last):
  File "tmp2.py", line 16, in <module>
    gru.to_cpu()
  File "/home/user/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/chainer/device_resident.py", line 75, in to_cpu
    self.__to_device(visitor)
  File "/home/user/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/chainer/device_resident.py", line 149, in __to_device
    self.device_resident_accept(to_device_visitor)
  File "/home/user/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/chainer/links/connection/gru.py", line 202, in device_resident_accept
    visitor.visit_variable(self.h)
  File "/home/user/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/chainer/device_resident.py", line 303, in visit_variable
    param.to_device(self._device)
  File "/home/user/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/chainer/variable.py", line 1139, in to_device
    self._to_device(device, allow_unchaining=False)
  File "/home/user/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/chainer/variable.py", line 1154, in _to_device
    '({}).'.format(device))
RuntimeError: A variable of a ChainerX array which requires gradients cannot be copied into non-chainerx device (@numpy).
```

 - When we use `device = chainer.get_device(0)` error does not happen.
 - In order to send chainerx array back to cpu, we need to call `reset_state()`, but it is inconvenient.

Can we consider workaround??

**Comment by emcastillo** [comment]
Hello,

The problem here is related to chainerx maintaining the computational graph.
The gru state requires the gradient to be computed for backpropagation and when it is copied out of chainerx the graph can be let in a non-consistent state.

In order to properly address this issue, we would like to know what you were intending to do and if you were expecting the computational graph to be cut.

Thanks!

**Comment by hvy** [comment]
Maybe it's okay to simply cut the ChainerX graph.
1. `to_{cpu,gpu,device}` for both `Variable` and `Links` with NumPy and CuPy in general breaks backprop when called in the middle of a computational graph, since backward function nodes will yield device mismatches.
1. Some users may temporarily transfer a device, and then transfer back? This will not work. A point is that a `Variable` or a `Link` gets in an "invalid state" when transferred. We could always cut the graph, even for NumPy and CuPy. We would then be able to avoid the "invalid state" saying instead that it becomes a leaf when transferred.

**Comment by hvy** [comment]
PR addressing this issue #7507.

**Comment by hvy** [comment]
This is still an issue.
