### ISSUE TITLE
Flaky test: `TestAdam`

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#7690]
https://jenkins.preferred.jp/job/chainer/job/chainer_pr/1490/TEST=chainer-py3,label=mn1-p100/

```
20:51:03 _ TestAdam_param_3_{adabound=False, amsgrad=False, dtype=float16, loss_scaling='static', use_placeholder=True}.test_linear_model_multi_gpu _
20:51:03 chainer/testing/parameterized.py:89: in new_method
20:51:03     utils._raise_from(e.__class__, s.getvalue(), e)
20:51:03 chainer/utils/__init__.py:106: in _raise_from
20:51:03     six.raise_from(new_exc.with_traceback(orig_exc.__traceback__), None)
20:51:03 chainer/testing/parameterized.py:78: in new_method
20:51:03     return base_method(self, *args, **kwargs)
20:51:03 chainer/testing/condition.py:80: in wrapper
20:51:03     fail()
20:51:03 chainer/testing/condition.py:51: in fail
20:51:03     instance.fail(msg)
20:51:03 E   AssertionError: Parameterized test failed.
20:51:03 E   
20:51:03 E   Base test method: TestAdam.test_linear_model_multi_gpu
20:51:03 E   Test parameters:
20:51:03 E     adabound: False
20:51:03 E     amsgrad: False
20:51:03 E     dtype: <class 'numpy.float16'>
20:51:03 E     loss_scaling: static
20:51:03 E     use_placeholder: True
20:51:03 E   
20:51:03 E   
20:51:03 E   (caused by)
20:51:03 E   AssertionError: 
20:51:03 E   Fail: 10, Success: 0
20:51:03 E   
20:51:03 E   The first error message:
20:51:03 E   Traceback (most recent call last):
20:51:03 E     File "/work/chainer/chainer/testing/condition.py", line 60, in <lambda>
20:51:03 E       lambda: f(ins, *args[1:], **kwargs),
20:51:03 E     File "/work/chainer/tests/chainer_tests/optimizers_tests/test_optimizers_by_linear_model.py", line 168, in test_linear_model_multi_gpu
20:51:03 E       self.assertGreater(cuda.to_cpu(accuracy.data), 0.9)
20:51:03 E   AssertionError: array(0.5, dtype=float16) not greater than 0.9
```

**Comment by emcastillo** [comment]
Seems that the error is related to `float16`, I changed the `@condition.retry(10)` to `@condition.retry(1). This allowed me to reproduce the failures in my environment and it only fails when float16 is used.
Maybe there is the need to use mixed-precission inside the classifier?

**Comment by niboshi** [comment]
FYI, I observed this error yesterday twice in a row.
Before that I have never seen it. It could be related to some recent change.
