### ISSUE TITLE
Easier to understand error when dataset failed to load

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#7781]
There are cases where dataset is incorrectly specified (e.g. giving an incorrect directory), resulting in an empty dataset.

The error provided in such cases is difficult to interpret for ordinary users:
```
Exception in main training loop: division by zero
Traceback (most recent call last):
  File "/home/niboshi/w/repos/chainer/chainer/training/trainer.py", line 313, in run
    while not stop_trigger(self):
  File "/home/niboshi/w/repos/chainer/chainer/training/triggers/interval_trigger.py", line 54, in __call__
    epoch_detail = updater.epoch_detail
  File "/home/niboshi/w/repos/chainer/chainer/training/updaters/standard_updater.py", line 141, in epoch_detail
    return self._iterators['main'].epoch_detail
  File "/home/niboshi/w/repos/chainer/chainer/iterators/serial_iterator.py", line 96, in epoch_detail
    return self.epoch + self.current_position / self._epoch_size
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "./train_mnist.py", line 135, in <module>
    main()
  File "./train_mnist.py", line 131, in main
    trainer.run()
  File "/home/niboshi/w/repos/chainer/chainer/training/trainer.py", line 349, in run
    six.reraise(*exc_info)
  File "/home/niboshi/conda/py3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/niboshi/w/repos/chainer/chainer/training/trainer.py", line 313, in run
    while not stop_trigger(self):
  File "/home/niboshi/w/repos/chainer/chainer/training/triggers/interval_trigger.py", line 54, in __call__
    epoch_detail = updater.epoch_detail
  File "/home/niboshi/w/repos/chainer/chainer/training/updaters/standard_updater.py", line 141, in epoch_detail
    return self._iterators['main'].epoch_detail
  File "/home/niboshi/w/repos/chainer/chainer/iterators/serial_iterator.py", line 96, in epoch_detail
    return self.epoch + self.current_position / self._epoch_size
ZeroDivisionError: division by zero
```

**Comment by niboshi** [comment]
Or perhaps it should work without any errors.

**Comment by niboshi** [comment]
`Trainer` is not designed to handle empty datasets because it operates in by-iteration basis.
The error message can be improved, though.
