### ISSUE TITLE
ImportError: undefined symbol: GOMP_critical_end

### ISSUE THREAD

**Issue by aksub99** [chainer/chainer#7815]
The following `ImportError` is seen when I try importing `chainer`. After some offline discussions with @asi1024 , I understand that this `ImportError` is probably caused after the changes made to `CMakeLists` in PR #7474 .
```
>>> import chainer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/akshay/chainer/chainer/__init__.py", line 10, in <module>
    from chainer import backends  # NOQA
  File "/home/akshay/chainer/chainer/backends/__init__.py", line 1, in <module>
    from chainer.backends import cuda  # NOQA
  File "/home/akshay/chainer/chainer/backends/cuda.py", line 45, in <module>
    from chainer.backends import _cpu
  File "/home/akshay/chainer/chainer/backends/_cpu.py", line 8, in <module>
    import chainerx
  File "/home/akshay/chainer/chainerx/__init__.py", line 8, in <module>
    from chainerx import _core
ImportError: /usr/local/cuda-9.0/lib64/libcusolver.so.9.0: undefined symbol: GOMP_critical_end
```

**Comment by hvy** [comment]
Thanks for the report, we'll look into it. It sure looks related to #7474 since that's the PR which introduced cuSOLVER. Meanwhile, is updating CUDA to 10 an option for you?

**Comment by hvy** [comment]
The error message is probably caused by cuSOLVER requiring `libgomp` (OpenMP) to be linked, but failing. In what environment did you install Chainer, could you maybe post the `-v` install log?

**Comment by aksub99** [comment]
Thanks for the response @hvy . I installed Chainer on a `Ubuntu 18.04.2` linux environment.
The installation completed normally without any errors. Would posting the log still be helpful?

**Comment by hvy** [comment]
I think we need a bit more information. Which version of Python are you using and what output do you get when running the following? You can wait with the output :)
```python
import ctypes.util import find_library
find_library('gomp')
# or
import ctypes
ctypes.cdll.LoadLibrary('libgomp.so')
```

**Comment by aksub99** [comment]
I am using `Python 3.6.7` .
The output I get is:
```
>>> from ctypes.util import find_library 
>>> find_library('gomp')
'libgomp.so.1'
>>> import ctypes
>>> ctypes.cdll.LoadLibrary('libgomp.so')
<CDLL 'libgomp.so', handle 1e75250 at 0x7f4bae0e87b8>
```

**Comment by toslunar** [comment]
I got the error, too.
```
ImportError: /usr/local/cuda/lib64/libcusolver.so.9.0: undefined symbol: GOMP_critical_end
```

```
>>> from ctypes.util import find_library
>>> find_library('gomp')
'libgomp.so.1'
>>> import ctypes
>>> ctypes.cdll.LoadLibrary('libgomp.so')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kataoka/.pyenv/versions/3.7.4/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/home/kataoka/.pyenv/versions/3.7.4/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libgomp.so: cannot open shared object file: No such file or directory
>>> ctypes.cdll.LoadLibrary('libgomp.so.1')
<CDLL 'libgomp.so.1', handle 244fbb0 at 0x2b4d7fbf41d0>
```

**Comment by aksub99** [comment]
@toslunar Upgrading from `cuda-9.0` to `cuda-10.1` solved the problem for me.

**Comment by kmaehashi** [comment]
@hvy ref: https://github.com/chainer/chainer/pull/2487

**Comment by hvy** [comment]
@toslunar Could you try adding the `-fopenmp` option as described in #2487 and see if that solved the problem?

**Comment by toslunar** [comment]
The following fixed the problem.  Could you rewrite it to add the flag only when it's needed?

```diff
diff --git a/chainerx_cc/CMakeLists.txt b/chainerx_cc/CMakeLists.txt
index 82d4b5c..af19fbc 100644
--- a/chainerx_cc/CMakeLists.txt
+++ b/chainerx_cc/CMakeLists.txt
@@ -92,7 +92,7 @@ if("${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU|Clang|Intel")
         add_definitions(-D_CRT_SECURE_NO_WARNINGS)
     else()
         set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -pthread")
-        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -Wall -Wextra -fPIC -pthread")
+        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -Wall -Wextra -fPIC -pthread -fopenmp")
     endif()
     set(CMAKE_CXX_FLAGS_RELEASE "-O2 -DNDEBUG")  # cmake -DCMAKE_BUILD_TYPE=Release
     set(CMAKE_CXX_FLAGS_DEBUG "-O0")  # cmake -DCMAKE_BUILD_TYPE=Debug
```
