### ISSUE TITLE
Pytest fails when importing cupy

### ISSUE THREAD

**Issue by belldandyxtq** [chainer/chainer#8123]
We found that pytest fails when trying to import cupy under the main directory of chainer after commit 406b198433ef9f4fd68b7d9baf57d4cdb05c51dc.

How to reproduce:

**Test File**
```
tianqi@host:chainer$ cat test.py
import cupy
```

**Versions**
```
pytest version 4.6.2
Python 3.7.2
```

**Errors with master**
```
tianqi@host:chainer$ git checkout master
Previous HEAD position was a75d9cd... Fix braced-scalar-init warning
Switched to branch 'master'
Your branch is up-to-date with 'original_repo/master'.
tianqi@host:chainer$ pytest test.py
================================================================================ test session starts =================================================================================
platform linux -- Python 3.7.2, pytest-4.6.2, py-1.8.0, pluggy-0.12.0
Test order randomisation NOT enabled. Enable with --random-order or --random-order-bucket=<bucket_type>
rootdir: repository/chainer, inifile: setup.cfg
plugins: random-order-1.0.4
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/_pytest/main.py", line 206, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/_pytest/main.py", line 249, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/pluggy/callers.py", line 182, in _multicall
INTERNALERROR>     next(gen)  # first yield
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/_pytest/warnings.py", line 151, in pytest_collection
INTERNALERROR>     config=config, ihook=config.hook, when="collect", item=None
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/contextlib.py", line 112, in __enter__
INTERNALERROR>     return next(self.gen)
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/_pytest/warnings.py", line 88, in catch_warnings_for_item
INTERNALERROR>     _setoption(warnings, arg)
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/_pytest/warnings.py", line 27, in _setoption
INTERNALERROR>     category = wmod._getcategory(category)
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/warnings.py", line 264, in _getcategory
INTERNALERROR>     m = __import__(module, None, None, [klass])
INTERNALERROR>   File "repository/tmp/chainer/chainer/__init__.py", line 96, in <module>
INTERNALERROR>     _environment_check.check()
INTERNALERROR>   File "repository/tmp/chainer/chainer/_environment_check.py", line 110, in check
INTERNALERROR>     _check_optional_dependencies()
INTERNALERROR>   File "repository/tmp/chainer/chainer/_environment_check.py", line 102, in _check_optional_dependencies
INTERNALERROR>     '''.format(name=name, pkgs=pkgs))
INTERNALERROR> UserWarning:
INTERNALERROR> --------------------------------------------------------------------------------
INTERNALERROR> Multiple installations of CuPy package has been detected.
INTERNALERROR> You should select only one package from from ['cupy-cuda101', 'cupy-cuda100', 'cupy-cuda92', 'cupy-cuda91', 'cupy-cuda90', 'cupy-cuda80', 'cupy'].
INTERNALERROR> Run `pip list` to see the list of packages currently installed, then
INTERNALERROR> `pip uninstall <package name>` to uninstall unnecessary package(s).
INTERNALERROR> --------------------------------------------------------------------------------

============================================================================ no tests ran in 2.48 seconds ============================================================================
tianqi@host:chainer$ 
```

**Errors with 406b198**
```
tianqi@host:chainer$ git checkout 406b198433ef9f4fd68b7d9baf57d4cdb05c51dc
HEAD is now at 406b198... Merge pull request #6653 from niboshi/warnings-as-errors
tianqi@host:chainer$ pytest test.py
================================================================================ test session starts =================================================================================
platform linux -- Python 3.7.2, pytest-4.6.2, py-1.8.0, pluggy-0.12.0
Test order randomisation NOT enabled. Enable with --random-order or --random-order-bucket=<bucket_type>
rootdir: repository/chainer, inifile: setup.cfg
plugins: random-order-1.0.4
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "pyenv/versions/3.7.2/lib/python3.7/site-packages/_pytest/main.py", line 206, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "pyenv/versions/3.7.2/lib/python3.7/site-packages/_pytest/main.py", line 249, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "pyenv/versions/3.7.2/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "pyenv/versions/3.7.2/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "pyenv/versions/3.7.2/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "pyenv/versions/3.7.2/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "pyenv/versions/3.7.2/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/pluggy/callers.py", line 182, in _multicall
INTERNALERROR>     next(gen)  # first yield
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/_pytest/warnings.py", line 151, in pytest_collection
INTERNALERROR>     config=config, ihook=config.hook, when="collect", item=None
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/contextlib.py", line 112, in __enter__
INTERNALERROR>     return next(self.gen)
INTERNALERROR>   File ".pyenv/versions/3.7.2/lib/python3.7/site-packages/_pytest/warnings.py", line 88, in catch_warnings_for_item
INTERNALERROR>     _setoption(warnings, arg)
INTERNALERROR>   File "pyenv/versions/3.7.2/lib/python3.7/site-packages/_pytest/warnings.py", line 27, in _setoption
INTERNALERROR>     category = wmod._getcategory(category)
INTERNALERROR>   File "pyenv/versions/3.7.2/lib/python3.7/warnings.py", line 264, in _getcategory
INTERNALERROR>     m = __import__(module, None, None, [klass])
INTERNALERROR>   File "repository/tmp/chainer/chainer/__init__.py", line 96, in <module>
INTERNALERROR>     _environment_check.check()
INTERNALERROR>   File "repository/tmp/chainer/chainer/_environment_check.py", line 110, in check
INTERNALERROR>     _check_optional_dependencies()
INTERNALERROR>   File "repository/tmp/chainer/chainer/_environment_check.py", line 102, in _check_optional_dependencies
INTERNALERROR>     '''.format(name=name, pkgs=pkgs))
INTERNALERROR> UserWarning:
INTERNALERROR> --------------------------------------------------------------------------------
INTERNALERROR> Multiple installations of CuPy package has been detected.
INTERNALERROR> You should select only one package from from ['cupy-cuda101', 'cupy-cuda100', 'cupy-cuda92', 'cupy-cuda91', 'cupy-cuda90', 'cupy-cuda80', 'cupy'].
INTERNALERROR> Run `pip list` to see the list of packages currently installed, then
INTERNALERROR> `pip uninstall <package name>` to uninstall unnecessary package(s).
INTERNALERROR> --------------------------------------------------------------------------------

============================================================================ no tests ran in 2.43 seconds ============================================================================
tianqi@host:chainer$
```
**No Error with a75d9cd**
```
tianqi@host:chainer$ git checkout a75d9cde77e626bd10f74a8472795687109dcedb
Previous HEAD position was 406b198... Merge pull request #6653 from niboshi/warnings-as-errors
HEAD is now at a75d9cd... Fix braced-scalar-init warning
tianqi@host:chainer$ pytest test.py
================================================================================ test session starts =================================================================================
platform linux -- Python 3.7.2, pytest-4.6.2, py-1.8.0, pluggy-0.12.0
Test order randomisation NOT enabled. Enable with --random-order or --random-order-bucket=<bucket_type>
rootdir: repository/chainer, inifile: setup.cfg
plugins: random-order-1.0.4
collected 0 items

============================================================================ no tests ran in 1.03 seconds ============================================================================
tianqi@host:chainer$
```

where, a75d9cde77e626bd10f74a8472795687109dcedb is the commit right before 406b198433ef9f4fd68b7d9baf57d4cdb05c51dc

**Comment by belldandyxtq** [comment]
**UPDATE**
With `nosetest`, the error disappears.

**Comment by belldandyxtq** [comment]
**Possible Cause**
`pytest` parses and imports the module under current directory

**Comment by shmurai** [comment]
I found that adding a line `ignore::ImportWarning` to `setup.cfg` BEFORE `ignore::chainer.warnings.PerformanceWarning` (IMPORTANT!) mitigates this issue.
It looks like `import cupy` can cause `ImportWarning`, which is currently treated as an error due to the instruction in `setup.cfg`.

**Comment by shmurai** [comment]
PR #8131 created

**Comment by belldandyxtq** [comment]
The main cause is described in #8138. Close this because it includes an irrelative issue caused by multiple cupy versions
