### ISSUE TITLE
pytest is causing error in Jenkins

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#8217]
Example:

https://jenkins.preferred.jp/job/chainer/job/chainer_pr/2162/TEST=CHAINERX_chainer-py3,label=mn1-p100/console

```
14:33:27 + pytest -rfEX --showlocals -m 'not slow and not ideep' /repo/tests/chainer_tests
14:33:28 Traceback (most recent call last):
14:33:28   File "/workspace/conda/envs/testenv/bin/pytest", line 10, in <module>
14:33:28     sys.exit(main())
14:33:28   File "/workspace/conda/envs/testenv/lib/python3.6/site-packages/_pytest/config/__init__.py", line 61, in main
14:33:28     config = _prepareconfig(args, plugins)
14:33:28   File "/workspace/conda/envs/testenv/lib/python3.6/site-packages/_pytest/config/__init__.py", line 182, in _prepareconfig
14:33:28     config = get_config()
14:33:28   File "/workspace/conda/envs/testenv/lib/python3.6/site-packages/_pytest/config/__init__.py", line 156, in get_config
14:33:28     pluginmanager.import_plugin(spec)
14:33:28   File "/workspace/conda/envs/testenv/lib/python3.6/site-packages/_pytest/config/__init__.py", line 530, in import_plugin
14:33:28     __import__(importspec)
14:33:28   File "/workspace/conda/envs/testenv/lib/python3.6/site-packages/_pytest/tmpdir.py", line 25, in <module>
14:33:28     class TempPathFactory(object):
14:33:28   File "/workspace/conda/envs/testenv/lib/python3.6/site-packages/_pytest/tmpdir.py", line 35, in TempPathFactory
14:33:28     lambda p: Path(os.path.abspath(six.text_type(p)))
14:33:28 TypeError: attrib() got an unexpected keyword argument 'convert'
```

**Comment by toslunar** [comment]
`python -W (warnings filters for pytest) -m pytest` to know this in advance.  With `attrs==19.1`, I got
```
% python -W default -m pytest tests
/path/to/site-packages/_pytest/assertion/rewrite.py:8: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/path/to/site-packages/_pytest/tmpdir.py:35: DeprecationWarning: The `convert` argument is deprecated in favor of `converter`.  It will be removed after 2019/01.
  lambda p: Path(os.path.abspath(six.text_type(p)))
============================= test session starts ==============================
```
