### ISSUE TITLE
`optimizer.use_fp32_update` on ChainerX model

### ISSUE THREAD

**Issue by toslunar** [chainer/chainer#8525]
The issue reported in #8382.

### Code to reproduce
```python
import chainer
import numpy


for device_spec in ['@numpy', '@cupy:0', 'native:0']:
    print(device_spec)
    device = chainer.backend.get_device(device_spec)

    with chainer.using_config('dtype', numpy.float16):
        model = chainer.Sequential(
            chainer.links.Linear(4, 3),
            chainer.functions.sum,
        )

    model.cleargrads()
    model.to_device(device)
    opt = chainer.optimizers.SGD()
    opt.use_fp32_update()
    opt.setup(model)

    x = numpy.random.randn(2, 4).astype(numpy.float16)
    x = device.send(x)
    y = model(x)
    y.backward()
    opt.update()
    print('ok')
```

### Error messages, stack traces, or logs
```
@numpy
ok
@cupy:0
ok
native:0
Traceback (most recent call last):
  File "pr8382.py", line 25, in <module>
    opt.update()
  File "/path/to/chainer/optimizer.py", line 886, in update
    param.update()
  File "/path/to/chainer/variable.py", line 1954, in update
    self.update_rule.update(self)
  File "/path/to/chainer/optimizer.py", line 250, in update
    self.__update(param)
  File "/path/to/chainer/optimizer.py", line 301, in __update
    param.array = fp32_param.array.astype(param.dtype)
  File "/path/to/chainer/variable.py", line 954, in array
    self._set_array(d)
  File "/path/to/chainer/variable.py", line 970, in _set_array
    'Cannot update the array of a Variable if either the '
ValueError: Cannot update the array of a Variable if either the existing or the new array requires backprop.
```

**Comment by takagi** [comment]
Fixed via #8382 .
