### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by Rakiba291** [chainer/chainer#8581]
Hi,
I am trying to train  a model and getting this error. I have looking into other references but seems no one has solved this issue yet. Could you please help me solve the error. Thanks.

```
-------------
File "C:\Users\Anaconda3\envs\rcnn\lib\site-packages\chainer\training\trainer.py", line 313, in run
    while not stop_trigger(self):
  File "C:\Users\Anaconda3\envs\rcnn\lib\site-packages\chainer\training\triggers\interval_trigger.py", line 81, in __call__
    if hasattr(updater, 'epoch_detail'):
  File "C:\Users\Anaconda3\envs\rcnn\lib\site-packages\chainer\training\updaters\standard_updater.py", line 111, in epoch_detail
    return self._iterators['main'].epoch_detail
  File "C:\Users\Anaconda3\envs\rcnn\lib\site-packages\chainer\iterators\serial_iterator.py", line 96, in epoch_detail
    return self.epoch + self.current_position / self._epoch_size
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "train.py", line 67, in <module>
    load_path=args.load, data_path=args.data)
  File "train.py", line 55, in main
    trainer.run()
  File "C:\Users\Anaconda3\envs\rcnn\lib\site-packages\chainer\training\trainer.py", line 349, in run
    six.reraise(*exc_info)
  File "C:\Users\Anaconda3\envs\rcnn\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\Anaconda3\envs\rcnn\lib\site-packages\chainer\training\trainer.py", line 313, in run
    while not stop_trigger(self):
  File "C:\Users\Anaconda3\envs\rcnn\lib\site-packages\chainer\training\triggers\interval_trigger.py", line 81, in __call__
    if hasattr(updater, 'epoch_detail'):
  File "C:\Users\Anaconda3\envs\rcnn\lib\site-packages\chainer\training\updaters\standard_updater.py", line 111, in epoch_detail
    return self._iterators['main'].epoch_detail
  File "C:\Users\Anaconda3\envs\rcnn\lib\site-packages\chainer\iterators\serial_iterator.py", line 96, in epoch_detail
    return self.epoch + self.current_position / self._epoch_size
ZeroDivisionError: division by zero
----
```
-->
  - Chainer version=6.0.0
  - CuPy version=6.0.0
  - OS/Platform=Windows 10, python: 3.6
  - CUDA/cuDNN version=9/7.1

----

**Comment by kmaehashi** [comment]
I guess the length of the dataset is zero. Please make sure that the data is correctly loaded.
