### ISSUE TITLE
No module named 'cupy.util'

### ISSUE THREAD

**Issue by iegorval** [chainer/chainer#8602]
I am trying to use Chainer, but I get the error `no module named 'cupy.util'. Note that the solution https://github.com/chainer/chainer/issues/8582 did not seem to help in my case (or I am doing something very wrong).

* Conditions
```
python -c 'import chainer; chainer.print_runtime_info()'
```
Platform: Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.29
Chainer: 7.7.0
ChainerX: Not Available
NumPy: 1.20.1
CuPy: Not Available (in `pip freeze`: cupy-cuda110==8.5.0)
iDeep: Not Available

Other:
CUDA Driver Version / Runtime Version: 11.3 / 11.0
CUDA Capability Major/Minor version number: 7.5
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0
 
* Code to reproduce
`import chainer
chainer.cuda.to_gpu([0, 0])`
* Error messages, stack traces, or logs
`/home/iegorval/Diploma/experiments/smalst/venv_smalst/lib/python3.8/site-packages/torch/nn/functional.py:3384: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn("Default grid_sample and affine_grid behavior has changed "
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/iegorval/Diploma/experiments/smalst/smal_eval.py", line 470, in <module>
    app.run(main)
  File "/home/iegorval/Diploma/experiments/smalst/venv_smalst/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/iegorval/Diploma/experiments/smalst/venv_smalst/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/iegorval/Diploma/experiments/smalst/smal_eval.py", line 367, in main
    outputs = predictor.predict(batch, rot=global_rotation)
  File "/home/iegorval/Diploma/experiments/smalst/nnutils/smal_predictor.py", line 100, in predict
    self.forward(cam_gt, trans_gt, pose_gt, betas_gt, rot)
  File "/home/iegorval/Diploma/experiments/smalst/nnutils/smal_predictor.py", line 166, in forward
    self.mask_pred = self.renderer.forward(self.pred_v, self.faces,
  File "/home/iegorval/Diploma/experiments/smalst/nnutils/nmr.py", line 200, in forward
    return Render.apply(self.renderer, verts, faces)
  File "/home/iegorval/Diploma/experiments/smalst/nnutils/nmr.py", line 115, in forward
    masks = renderer.forward_mask(vs, fs)
  File "/home/iegorval/Diploma/experiments/smalst/nnutils/nmr.py", line 47, in forward_mask
    self.faces = chainer.Variable(chainer.cuda.to_gpu(faces, self.cuda_device))
  File "/home/iegorval/Diploma/experiments/smalst/venv_smalst/lib/python3.8/site-packages/chainer/backends/cuda.py", line 413, in to_gpu
    check_cuda_available()
  File "/home/iegorval/Diploma/experiments/smalst/venv_smalst/lib/python3.8/site-packages/chainer/backends/cuda.py", line 143, in check_cuda_available
    raise RuntimeError(msg)
RuntimeError: CUDA environment is not correctly set up
(see https://github.com/chainer/chainer#installation).No module named 'cupy.util'`

**Comment by kmaehashi** [comment]
Hi, please use `cupy-cuda110==7.8.0` for Chainer v7.
