### ISSUE TITLE
import chainer error: 'raise TypeError(f"{cls} is not a generic class")'

### ISSUE THREAD

**Issue by hahaheihei09** [chainer/chainer#8619]
* Conditions

Hi, I scucessfully installed it using 'pip install chainer', but was unable to use. When I tried to import chainer, I got the following error. 

Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import chainer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yuge/tensorflow/venvp3/lib/python3.5/site-packages/chainer/__init__.py", line 10, in <module>
    from chainer import backends  # NOQA
  File "/home/yuge/tensorflow/venvp3/lib/python3.5/site-packages/chainer/backends/__init__.py", line 1, in <module>
    from chainer.backends import cuda  # NOQA
  File "/home/yuge/tensorflow/venvp3/lib/python3.5/site-packages/chainer/backends/cuda.py", line 46, in <module>
    from chainer.backends import intel64
  File "/home/yuge/tensorflow/venvp3/lib/python3.5/site-packages/chainer/backends/intel64.py", line 8, in <module>
    from chainer.configuration import config
  File "/home/yuge/tensorflow/venvp3/lib/python3.5/site-packages/chainer/configuration.py", line 5, in <module>
    from chainer import types  # NOQA
  File "/home/yuge/tensorflow/venvp3/lib/python3.5/site-packages/chainer/types.py", line 3, in <module>
    import typing_extensions as tpe  # NOQA
  File "/home/yuge/tensorflow/venvp3/lib/python3.5/site-packages/typing_extensions-4.0.1-py3.5.egg/typing_extensions.py", line 33
    raise TypeError(f"{cls} is not a generic class")
                                                  ^
SyntaxError: invalid syntax

->
 - Chainer version 7.8.1
  - CuPy version cupy-cuda110-8.6.0
  - OS/Platform ubuntu 16.04
  - CUDA/cuDNN version cuda_11.0/cuDNN8.0
  - etc.
* Code to reproduce
* Error messages, stack traces, or logs

**Comment by kmaehashi** [comment]
Could you try updating `pip``, then uninstall `typing_extensions` and reinstall `typing_extensions`? It seems `typing_extensions` 4.0.1 is installed which does not support Python 3.5.
