### ISSUE TITLE
Import of distributions causes problem with numpy.sctypes using numpy >= 2.0 releases

### ISSUE THREAD

**Issue by JeanJARDEL** [chainer/chainer#8632]
Python version 3.10.6

chainer==7.8.1
filelock==3.15.4
numpy==2.0.0
protobuf==5.27.1
six==1.16.0
typing_extensions==4.12.2

My python script :
`from chainer import distributions`

I get the following error :
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venv/lib/python3.10/site-packages/chainer/__init__.py", line 13, in <module>
    from chainer import distributions  # NOQA
  File "/tmp/venv/lib/python3.10/site-packages/chainer/distributions/__init__.py", line 3, in <module>
    from chainer.distributions.bernoulli import Bernoulli  # NOQA
  File "/tmp/venv/lib/python3.10/site-packages/chainer/distributions/bernoulli.py", line 7, in <module>
    import chainer.distributions.utils
  File "/tmp/venv/lib/python3.10/site-packages/chainer/distributions/utils.py", line 4, in <module>
    from chainer.functions.array import where
  File "/tmp/venv/lib/python3.10/site-packages/chainer/functions/__init__.py", line 25, in <module>
    from chainer.functions.array.as_strided import as_strided  # NOQA
  File "/tmp/venv/lib/python3.10/site-packages/chainer/functions/array/as_strided.py", line 10, in <module>
    index_dtype = {t().itemsize: t for t in np.sctypes['int']}
  File "/tmp/venv/lib/python3.10/site-packages/numpy/__init__.py", line 397, in __getattr__
    raise AttributeError(
AttributeError: `np.sctypes` was removed in the NumPy 2.0 release. Access dtypes explicitly instead.. Did you mean: 'dtypes'?
```

I couldn't find anyone having the same problem on StackOverflow and no issues mentioning this problem.

There should be a way to use np.dtypes instead, I didn't find a solution on my side. And I don't think defining this `index_dtype` here is the cleanest way either. If anyone has a clean solution, I'm all ears !

**Comment by kmaehashi** [comment]
The latest combination supported is Python 3.8 & NumPy 1.17. Please refer to the documentation for more details. :pray:
https://docs.chainer.org/en/stable/install.html
